### PR TITLE
Add LGTM.com code quality badges

### PR DESCRIPTION
**Pull request by sjvs**
Code quality is really good; these badges show that to users and contributors :slightly_smiling_face:

### CODE REVIEW

**Comment by seut** [comment]
@sjvs Thanks for this contribution. Could you please sign our CLA (https://crate.io/community/contribute/cla/) so we can merge it?

**Comment by sjvs** [comment]
@seut: all done!

**Comment by seut** [comment]
retest this please

**Comment by seut** [comment]
retest this please

**Comment by seut** [comment]
@sjvs thanks, just merged it.

**Pull request merged**
