### PR TITLE
Upgraded PostgreSQL Wire Protocol to 14

### PR DESCRIPTION
**Pull request by robd003**
https://github.com/crate/crate/issues/13418

## Summary of the changes / Why this improves CrateDB
Fix for ticket https://github.com/crate/crate/issues/13418

## Checklist

 - [X] Added an entry in `CHANGES.txt` for user facing changes
 - [X] Updated documentation & `sql_features` table for user facing changes
 - [X] Touched code is covered by tests
 - [X] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [X] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by robd003** [comment]
Will put a list of differences between postgresql 10 - >14 schemas here

**Comment by mfussenegger** [comment]
ok to test

**Comment by mfussenegger** [comment]
> Will put a list of differences between postgresql 10 - >14 schemas here

Did you have a chance to look at the differences? Otherwise the change looks good

**Comment by robd003** [comment]
@mfussenegger Haven't put together a full list of changes, will try to work on it this weekend.

Do you want me to bump the version to Postgres 15?

**Pull request merged**
