### PR TITLE
Integrate user and ssl-impl extension into server

### PR DESCRIPTION
**Pull request by mfussenegger**
See https://github.com/crate/crate/pull/10981

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mfussenegger** [comment]
Test failure is unrelated, see https://github.com/crate/crate/pull/10987

**Review by seut — COMMENTED** [review]
Lgtm, but looks like there was a mistake while moving the `AuthenticationWithSSLIntegrationTest.java ` class. It was moved to `extensions/ssl-impl`.

**Comment by mfussenegger** [comment]
> but looks like there was a mistake while moving the AuthenticationWithSSLIntegrationTest.java class. It was moved to extensions/ssl-impl.

Ah right I created it in `server` without removing it. Good catch :+1: 
Removed it now

**Comment by amotl** [comment]
Hi Mathias,

thanks for this patch. Apparently, the Windows tests might croak on this? At least, it is related to SSL - you have to judge if it is **actually** related or whether it is just flakyness.

```java
## FAILURE: Test executionError(io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest)
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest_FAE521244CB254BC-001\tempFile-002.tmp: java.nio.file.FileSystemException: C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest_FAE521244CB254BC-001\tempFile-002.tmp: The process cannot access the file because it is being used by another process
   C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest_FAE521244CB254BC-001\tempFile-001.tmp: java.nio.file.FileSystemException: C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest_FAE521244CB254BC-001\tempFile-001.tmp: The process cannot access the file because it is being used by another process
   C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest_FAE521244CB254BC-001: java.nio.file.DirectoryNotEmptyException: C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.http.HttpsTransportKeyStoreReloadIntegrationTest_FAE521244CB254BC-001
```

-- https://github.com/crate/crate/pull/10986/checks?check_run_id=1829040567#step:4:802

```java
## FAILURE: Test executionError(io.crate.protocols.postgres.SslReqHandlerIntegrationTest)
SslReqHandlerIntegrationTest > executionError FAILED
    java.io.IOException at [149250F54C1C7988]:0
Running: Test class io.crate.protocols.postgres.SslReqHandlerTest

java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.postgres.SslReqHandlerIntegrationTest_149250F54C1C7988-001\tempFile-001.tmp: java.nio.file.FileSystemException: C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.postgres.SslReqHandlerIntegrationTest_149250F54C1C7988-001\tempFile-001.tmp: The process cannot access the file because it is being used by another process
   C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.postgres.SslReqHandlerIntegrationTest_149250F54C1C7988-001: java.nio.file.DirectoryNotEmptyException: C:\Users\runneradmin\AppData\Local\Temp\io.crate.protocols.postgres.SslReqHandlerIntegrationTest_149250F54C1C7988-001
```

-- https://github.com/crate/crate/pull/10986/checks?check_run_id=1829040567#step:4:834

With kind regards,
Andreas.

**Review by amotl — COMMENTED** [review]
Apart from making the tests pass, this looks good to me.

**Comment by mfussenegger** [comment]
@amotl the test failures were unrelated to the changes in this PR. Could you have another look/approve?

**Review by amotl — APPROVED** [review]
> @amotl the test failures were unrelated to the changes in this PR. Could you have another look/approve?

On a semantic level, I trust both your work (thanks!) and the review by @seut. Of course you can have an acknowledgement, here you go.

However, I am still wondering about those files on Windows being locked as I haven't seen them before. Re-running them on behalf of https://github.com/crate/crate/pull/10986/checks?check_run_id=1856764617.

**Comment by amotl** [comment]
By the way, while probably also unrelated, I tried to take care of
```
(node:384) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
at https://github.com/eskatos/gradle-command-action/issues/22#issuecomment-769791704. Thanks @damccorm, ping @eskatos.

**Pull request merged**
