### PR TITLE
Test: Add a test to prevent any unexpected changes to function signatures

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
It would be good to add such test to prevent any mistakes from https://github.com/crate/crate/pull/16133.

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
TODO: Looks like `LAZY_ATTRIBUTES` can be removed. Since removing it will affect the ordinals of `Scalar.Feature`, I think it make sense to do it after https://github.com/crate/crate/pull/16133 which removes `NULLABLE` and `NON_NULLABLE`.

**Review by matriv — APPROVED** [review]
I agree to have a central place to test all the signatures, but maybe this adds extra burden when adding a new function. @mfussenegger what's your opinion on this?

(@jeeminso LGTM, but let's wait for another opinion before merging).

**Review by mfussenegger — COMMENTED** [review]
I'm not a fan of this. Having a central test case over all functions means having conflicts if many PRs adds functions and it also goes against my plan of moving most functions out of the server module.

I also don't really get the advantage over testing this on a case by case basis in the respective function unit test?

**Comment by jeeminso** [comment]
Thank you, once https://github.com/crate/crate/pull/16133 and https://github.com/crate/crate/pull/16174 are merged this new test will have less value as the PRs try to make it less error prone in tagging the functions with appropriate features. And comes with the downsides mentioned. I will only use them locally for developing the PRs. Closing.

**Pull request closed without merging**
