### PR TITLE
Chore: Update `3RD-PARTY-NOTICES.md`

### PR DESCRIPTION
**Pull request by amotl**
Just a regular incantation of `./gradlew generateLicenseNotes`.

P.S.: While the corresponding plugin may currently croak on CI (#13319), it still worked on my machine.

### CODE REVIEW

**Review by BaurzhanSakhariev — APPROVED** [review]

**Comment by amotl** [comment]
This currently fails on the _Add PR to CrateDB project board_ step. Is someone able to fix it?

```
Run gh api graphql -F contentId=$PR_ID -f query='
gh: The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.
{"data":{"addProjectNextItem":null},"errors":[{"type":"NOT_FOUND","path":["addProjectNextItem"],"locations":[{"line":3,"column":5}],"message":"The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement."}]}
Error: Process completed with exit code 1.
```

-- https://github.com/crate/crate/actions/runs/3585820867/jobs/6044488117

**Comment by amotl** [comment]
retest this please

**Review by matriv — APPROVED** [review]

**Comment by matriv** [comment]
> This currently fails on the _Add PR to CrateDB project board_ step. Is someone able to fix it?
> 
> ```
> Run gh api graphql -F contentId=$PR_ID -f query='
> gh: The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.
> {"data":{"addProjectNextItem":null},"errors":[{"type":"NOT_FOUND","path":["addProjectNextItem"],"locations":[{"line":3,"column":5}],"message":"The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement."}]}
> Error: Process completed with exit code 1.
> ```
> 
> Maybe just swap `addProjectNextItem` to `addProjectV2Item`, and `projectNextItem` to `projectV2Item`?
> 
> https://github.com/crate/crate/blob/40e09cdf69b1d07b7cadd5cd0655c3faf7cec9db/.github/workflows/project.yml#L14-L21
> 
> -- https://github.com/crate/crate/actions/runs/3585820867/jobs/6044488117

There was this attempt: https://github.com/crate/crate/pull/13210/files but I think it didn't work.

**Comment by amotl** [comment]
> There was an attempt at #13210, but I think it didn't work.

I see. So, just ignore this step until it has been resolved?

**Comment by amotl** [comment]
_Add PR to CrateDB project board_ apparently worked again on #13323. Maybe GitHub is running regular brownouts on the old API version endpoints?

-- https://github.com/crate/crate/actions/runs/3592805646/jobs/6048965866

**Pull request merged**
