### PR TITLE
Backport: Preparation for dark-mode documentation

### PR DESCRIPTION
**Pull request by msbt**
## Summary of the changes / Why this improves CrateDB

This is basically the same PR as https://github.com/crate/crate/pull/16997, but this time around only for older versions since that was forgotten in the initial PR.

> I've been working on https://github.com/crate/crate-docs-theme/pull/546 version for our docs and while testing various repositories, a few minor issues came up with the reference docs. The images used are transparent PNGs and don't work on darker backgrounds (text becomes unreadable). Until we get proper svg graphics that adjust with the theme, this should fix the most immediate issues. I also removed a hardcoded table color in [/docs/appendices/resiliency.rst](https://github.com/crate/crate/blob/master/docs/appendices/resiliency.rst?plain=1#L85).
>
> Obviously some things we'll only see when it's live, but if you know of any other imagery or hardcoded styling, let me know.
>
> Checklist doesn't apply, since this is just imagery and styling for the docs. Also not sure if this needs backporting, wdyt?

### CODE REVIEW

**Comment by amotl** [comment]
@Mergify?

**Comment by amotl** [comment]
Do you think we need to manually back-port this, @BaurzhanSakhariev? Does Mergify not work on PRs not targeted to `master`?

**Comment by BaurzhanSakhariev** [comment]
@mergifyu backport 5.8

**Comment by BaurzhanSakhariev** [comment]
We need to merge source first.

**Comment by msbt** [comment]
can we do that on the initial PR then? https://github.com/crate/crate/pull/16997

**Comment by BaurzhanSakhariev** [comment]
>@BaurzhanSakhariev can we do that on the initial PR then? https://github.com/crate/crate/pull/16997

Already did, here is auto-created PR - https://github.com/crate/crate/pull/17038

Closing this

**Pull request closed without merging**
