### PR TITLE
Add assertion for doc-value-aggregator in top-k tests

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

This change is because I want to enforce in the tests that doc-values support must be present.

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]
lgtm but I wonder if this wouldn't be more flexible with a dedicated `assertSupportsDocValueAggregator(signature, types)`

**Comment by mkleen** [comment]
> lgtm but I wonder if this wouldn't be more flexible with a dedicated `assertSupportsDocValueAggregator(signature, types)`

Good idea. I will do this as a follow-up.

**Comment by mfussenegger** [comment]
> > lgtm but I wonder if this wouldn't be more flexible with a dedicated `assertSupportsDocValueAggregator(signature, types)`
> 
> Good idea. I will do this as a follow-up.

Why as follow up? If you think it is a good idea we should do it instead of this.

**Comment by mkleen** [comment]
> > > lgtm but I wonder if this wouldn't be more flexible with a dedicated `assertSupportsDocValueAggregator(signature, types)`
> > 
> > 
> > Good idea. I will do this as a follow-up.
> 
> Why as follow up? If you think it is a good idea we should do it instead of this.

Ok, no problem. The main reason for a follow-up is because i am on something else right now and i just needed this change.

**Comment by mkleen** [comment]
Sorry, I misunderstood the comment. I wasn't aware that the assertion exists already. I thought it needs to be implemented.

**Comment by mfussenegger** [comment]
> Sorry, I misunderstood the comment. I wasn't aware that the assertion exists already. I thought it needs to be implemented.

I thought so as well - but even then, it would only have been an unnecessary back and forth to not change it immediately.

**Pull request merged**
