### PR TITLE
copy edit

### PR DESCRIPTION
**Pull request by mechanomi**
## Summary of the changes / Why this improves CrateDB

docs copy edit

### CODE REVIEW

**Comment by mfussenegger** [comment]
A commit message that is a bit more descriptive would be great.

**Comment by mechanomi** [comment]
@mfussenegger I left off the information about what file was being copy edited because that information is already a part of the commit information

however, per your comment, I have edited the commit message to add that information

**Comment by mfussenegger** [comment]
> left off the information about what file was being copy edited because that information is already a part of the commit information

It helps when skimming the log to easily judge if a commit might contain interesting changes. Otherwise we could also simply have a "changed a bunch of things" commit message for all commits.

**Comment by mechanomi** [comment]
@mfussenegger gotcha! thx!

**Pull request merged**
