### PR TITLE
Fix `GraalVM Security Guide` missing link

### LINKED ISSUE #10913: Missing link
###  Documentation feedback

 
- Page title: User-defined functions
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/user-defined-functions.html
- Source: https://github.com/crate/crate/blob/4.3/docs/general/user-defined-functions.rst

---

https://crate.io/docs/crate/reference/en/4.3/general/user-defined-functions.html#javascript

```Please refer to `GraalVM Security Guide`_ for more detailed information```

In this section the link to "GraalVM Security Guide" is not rendered. Likely because it's used within bold text and nested inline markup isn't supported.

### PR DESCRIPTION
**Pull request by HoussemNasri**
Fixes #10913
## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by amotl — APPROVED** [review]

**Comment by amotl** [comment]
Hi Houssem,

thanks again for this patch. It looks like the base branch is still not up to date, see comment above. Sorry for the hassle. Do you want to try another time to branch off the most recent head? Otherwise, let us know if we should cherry-pick your commit. Maybe @mechanomi can do it.

With kind regards,
Andreas.

**Comment by HoussemNasri** [comment]
Thank you Andreas, you have been a huge help, I assume everything should work now after I merged crate/master into my master.

**Comment by amotl** [comment]
Hi Houssem,

thanks a stack for your patience. Actually, we are **almost** set. You can now observe your PR includes two commits: One "merge commit" and the real one actually bringing in your change.

As we are very strong on keeping a linear commit history, we usually don't merge things into each other but use `git rebase` operations instead. Now, let's see if we can integrate your patch by squashing your commits into a single one.

With kind regards,
Andreas.

P.S.: As I recognize you might be keen on improving your skills (around git), I would kindly like to encourage you to setup a testing repository on your end and play around with different tutorials found on the interwebs outlining how to use rebase operations.

**Comment by amotl** [comment]
retest this please

**Comment by amotl** [comment]
@seut, @mfussenegger: This patch has been verified successfully by CI. Can we integrate it by using the "Update branch" button followed by "Squash and rebase" instead of having to nag Houssem about it again?

**Comment by amotl** [comment]
Hi Houssem,

Mergify will take care of rebasing your patch and removing the merge commit introduced to the PR. So, everything will be fine on the technical side. May I still humbly ask you to sign the CLA at [1] even while it's just a one-character-fix?

Thanks already and with kind regards,
Andreas.

[1] https://crate.io/community/contribute/cla/

**Comment by HoussemNasri** [comment]
I signed the CLA and updated my comment.
Thanks you, I am looking forward to contribute more to this project.

**Comment by amotl** [comment]
> I signed the CLA and updated my comment.

Thanks!

> Thanks you, I am looking forward to contribute more to this project.

Thank you as well. Also looking forward.

**Comment by amotl** [comment]
Retest this please.

**Pull request merged**
