### PR TITLE
Change calls to deprecated Loggers#getLoggers to LogManager#getLoggers

### PR DESCRIPTION
**Pull request by mkleen**
## Checklist

 - [ ] User relevant changes are recorded in ``CHANGES.txt``
 - [X] Touched code is covered by tests
 - [ ] Documentation has been updated if necessary
 - [X] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mkleen** [comment]
> can we delete the deprecated method now?

good point, done!

**Comment by seut** [comment]
retest this please

**Comment by mfussenegger** [comment]
@seut I don't think that this is flaky, but rather that the built plugins use the logger API that is being removed

**Comment by mkleen** [comment]
> @seut I don't think that this is flaky, but rather that the built plugins use the logger API that is being removed

**Comment by mkleen** [comment]
The integration tests with the jar for the example plugin were failing. I fixed the example plugins now and add the new jars.

**Pull request merged**
