### PR TITLE
Remove copy_to on upgrade

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Follow up to https://github.com/crate/crate/commit/e06b5f087e1b2a992ad78cc239015ac077e09afa

We have to remove it from the metadata on upgrade otherwise it will stay deprecated forever. 

We even have an assertion to have only one of copy_to or sources, see [comment](https://github.com/crate/crate/pull/14026#discussion_r1186097764). 

It's still fine to keep code handling "copy_to" though, as we sometimes need to handle not yet upgraded metadata.

Also tested crate-qa on the path UpgradePath('5.3.x', 'repo with this PR'),

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
I think we can't remove it unitl all code goes through the indexer code-path. 
Anything that's still processed using the legacyInsert path wouldn't store the values for the fulltext index fields.

**Comment by BaurzhanSakhariev** [comment]
>  legacyInsert

Good point, thanks. Will re-open this later, once we remove `legacyInsert`

**Comment by BaurzhanSakhariev** [comment]
> I think we can't remove it unitl all code goes through the indexer code-path.

Hi @mfussenegger, can you have another look? 

We can remove `copy_to` after merging https://github.com/crate/crate/pull/14683 (but only from upgrader to avoid having it in new tables, `copy_to` handling code is still around)

**Review by mfussenegger — COMMENTED** [review]
Isn't this missing the related copyTo logic in the field mappers?
If we remove it from the mapping, we should also be able to remove any logic that accessed it.

E.g. by following the trail of https://github.com/crate/crate/blob/c0adb3764bad9aaac5ec487d98a85c1bc0c8c409/server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java#L49

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
