### PR TITLE
Allow schema and table names to start with '_'

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Resolves https://github.com/crate/crate/issues/13578

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by matriv — APPROVED** [review]
Left a [question on the issue](https://github.com/crate/crate/issues/13578#issuecomment-1415992278) otherwise it looks good!

**Comment by jeeminso** [comment]
> Left a [question on the issue](https://github.com/crate/crate/issues/13578#issuecomment-1415992278) otherwise it looks good!

Thanks again for catching it. 👍

**Comment by matriv** [comment]
> > Left a [question on the issue](https://github.com/crate/crate/issues/13578#issuecomment-1415992278) otherwise it looks good!
> 
> Thanks again for catching it. +1

We're fine, just wanted to double check with @proddata to not miss something from the original use case.

**Comment by matriv** [comment]
@jeeminso https://github.com/crate/crate/issues/13578#issuecomment-1418693710 Seems that Postgres allow prefix `_` even without quotes.

**Comment by jeeminso** [comment]
Thank you!

**Pull request merged**
