### PR TITLE
Ensure RemoteClusters & replication service are closed on node shutdown

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Review by seut — APPROVED** [review]
👍

**Comment by mfussenegger** [comment]
retest this please

Jenkins connection hiccups (still?)

**Comment by mfussenegger** [comment]
@seut pushed a fixup, they still didn't get closed.

**Review by seut — APPROVED** [review]

**Comment by mfussenegger** [comment]
retest this please

**Pull request merged**
