### PR TITLE
tests/pgwire: randomly force binary transfer

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Comment by mfussenegger** [comment]
@seut please review

**Comment by seut** [comment]
there a still some test which a forcing binary always, is this on purpose?

**Comment by mfussenegger** [comment]
yes prepareThreshold -1 also causes the client to use server-side prepared statements immediately and the tests which use it only make sense if that is the case.

**Comment by seut** [comment]
lgtm

**Pull request merged**
