### PR TITLE
Fix filtering by unbounded numeric literal, `= <numeric>::numeric`

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Initial attempt https://github.com/crate/crate/pull/16829 with narrowed scope.

Fixes:
```
cr> create table t (a numeric(4,2));
CREATE OK, 1 row affected (1.642 sec)
cr> insert into t values (1.11);
INSERT OK, 1 row affected (2.536 sec)
cr> insert into t values (11.11);
INSERT OK, 1 row affected (1.567 sec)
cr> select * from t where a = 1.111::numeric;  -- 1.111 has scale = 3 so it can be turned into a MatchNoDocsQuery
+-------+
|     a |
+-------+
| 11.11 |
+-------+
SELECT 1 row in set (1.843 sec)
cr> select * from t where a =111::numeric;  -- the unscaled value of 111 was 111 which was identical to the unscaled value of 1.11.
+------+
|    a |
+------+
| 1.11 |
+------+
SELECT 1 row in set (0.004 sec)
```
Please see the test cases added for more.

https://github.com/crate/crate/blob/a1f77cfb706fb3fb470a58e5d0dad58eb679ade6/docs/appendices/release-notes/5.9.1.rst?plain=1#L118-L120 is enough that we do not need an extra release entry.

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
Hi @seut, @matriv, I tried to narrow the scope from my initial PR, please take a look. Thank you

**Review by seut — COMMENTED** [review]
Looks good, but missing a changes entry.

**Review by seut — APPROVED** [review]
👍

**Comment by matriv** [comment]
> Looks good, but missing a changes entry.

Apologies for being a bit late, isn't this a valid request ^^ ?

**Comment by matriv** [comment]
thank you @jeeminso! 
I tried it out as well, sorry for being a bit late with the review.

**Pull request merged**
