### PR TITLE
Create a glossary (including related improvements for the main docs)

### PR DESCRIPTION
**Pull request by mechanomi**
parent issue: https://github.com/crate/tech-writing-domain/issues/382

this PR is going to collect changes needed to add a glossary to the reference manual

I have decided to stage this as a series of relatively-atomic commits to make the review process easier. once the PR is ready and approved, I will squash the commits down into a single commit

for the most part, changes will be limited to:

- expanding `glossary.rst`
- peppering cross-references throughout the docs that link back to the glossary

I may perform some very light copyediting while adding those cross-references. however, strictly speaking, this is beyond the scope of work. limiting edits for existing material as is necessary for the implementation of the glossary will keep the size of this work manageable
 
please see the commit messages for specific info

I am looking for two types of feedback:

- general feedback re what has been changed
- reviewing my definitions for accuracy

I will do my best to define terms as they are added. however, a good portion of that work is going to be based on reviewing and synthesizing information from multiple sources (e.g., our docs, ES docs, other third-party docs). this work will require scrutiny from someone with more hands-on experience with the CrateDB internals 

additionally, it would be ideal if I could pair up with one person on this and get iterative feedback nice and early as things progress.  I would like to avoid having to go back to make large revisions to my approach. for example, if I receive feedback after defining and cross-linking 30 terms asking me to reduce the number of cross-references, a lot of effort is potentially going to be thrown away

### CODE REVIEW

**Comment by mechanomi** [comment]
removed placeholder terms per https://github.com/crate/tech-writing-domain/issues/382#issuecomment-783526319

**Comment by mechanomi** [comment]
@mkleen this is ready for review!

some notes:

- I tried to do my work in an atomic fashion but there is a bit of noise in there. sorry about that. if you'd like me to re-organize the changes, I can do that
- I tried to describe the changes in the commit messages, so I will avoid adding any explanation here. some of the commit messages have extended descriptions (some of them quite detailed). hopefully, this helps
- once you're happy with this PR, I plan to squash the changes

let me know whether you think we can merge this directly to master as-is, with the plan being to add more terms on a PR-by-PR basis. I think this will work because each addition is logically separate. if you think it would be better to merge to a feature branch, we can do that too

as I worked on this, it became clear to me that in some instances, simply adding a glossary definition was not sufficient to properly explain the concept. this is true when the existing documentation is incomplete or confusing (IMO). I have taken the opportunity to improve sections of the main documentation as a part of this work

I am particularly interested in getting verification that my explanations and definitions are technically accurate. although, any sort of feedback is of course welcome!! <3

in the meantime, I plan to review the other documentation projects (tutorials, howto guides, and so on) and add cross-references to the terms I have defined in this PR

**Comment by mechanomi** [comment]
additional tasks:

- [ ] add nginx redirects for filename changes

**Review by mkleen — APPROVED** [review]
👍 Really good work! Don't forget to stash everything to one commit, please.

**Comment by mechanomi** [comment]
added redirect to https://github.com/crate/salt/pull/2499/files

**Pull request merged**
