### PR TITLE
Nodesettingstest - windows

### PR DESCRIPTION
**Pull request by senchi**
I've removed the app/config symlinks from git index, instead I'm dynamically copying needed (default) configuration form the src/main/dist/config directory where it is needed (to app/config).

AFAIK, those symlinks' only purpose was to serve as default configuration for these NodeSettingsTests, so by copying them manually we achieve exactly the same goal, to have a "default" configuration for the tests.

Please let me know if this solution is OK for you guys or if you have a better one!

Thanks

### CODE REVIEW

**Comment by senchi** [comment]
Here the core build seems to be failed with following messag:
* What went wrong:
Cannot expand ZIP '/home/travis/build/crate/crate/core/build/classes/shared' as it is not a file.

Also the :docs:itest failed!

Like mentioned in #1642, if you haven't done so already, please dedicate a wiki place or similar where we could keep track of those "flaky" tests and issues

**Comment by mfussenegger** [comment]
I think it would be okay to just copy crate.yml and logging.yml directly instead of the whole directory tree.

**Comment by senchi** [comment]
OK, I've changed the code now to copy those two files specifically.

Thanks

**Comment by mfussenegger** [comment]
Closing this since it got outdated.

**Pull request closed without merging**
