### PR TITLE
Document `array_upper` behavior on empty array

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

The behavior is surprising enough to justify mentioning it in the docs.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by seut** [comment]
Same happens on `array_length`, maybe at all array scalars?

**Comment by mfussenegger** [comment]
> Same happens on `array_length`, maybe at all array scalars?

I changed the `array_length` to document it as alias to `array_upper` to avoid repeating the same thing.

**Review by seut — APPROVED** [review]
👍

**Comment by BaurzhanSakhariev** [comment]
do we need this in 4.8?

**Comment by mfussenegger** [comment]
> do we need this in 4.8?

Not sure. It's not really a fix

**Pull request merged**
