### PR TITLE
DigestBlobTests, removed redundand stream close, added content check on final file

### PR DESCRIPTION
**Pull request by senchi**

### CODE REVIEW

**Comment by senchi** [comment]
Hi,

I've rebased now again, but some tests, which are not related to my changes, still fail.

If I get some more free time, I'll have a look into those.
If you guys have any tips for me where to look first that would be helpful!

Thanks

**Comment by mfussenegger** [comment]
which tests are you referring too? We've some that are known to be flaky (especially on travis)

**Comment by senchi** [comment]
e.g. GroupByAggregateTest > selectGroupByAggregateMinOrderByMin and GroupByAggregateTest > classMethod..
You can checkout the Travis logs here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/50062583/log.txt

Do you have a wiki somewhere with a list of those "flaky" tests?
This should probably be put in the backlog and as soon as someone has free time he can look into it, what do you think?

Thanks

**Comment by mfussenegger** [comment]
that one is flaky (in fact I think all in GroupByAggregateTest are since I've changed the ensureGreen to ensureYellow in https://github.com/crate/crate/commit/ff1a38fb7815607894b9110a2f62e304cc481828)

Not sure if tracking it in a wiki makes sense as it shouldn't be the case that we've the same tests being flaky for a long time.

**Pull request merged**
