### PR TITLE
Allow cast between timestamp data types.

### PR DESCRIPTION
**Pull request by kovrus**
## Checklist

 - [ ] User relevant changes are recorded in ``CHANGES.txt``
 - [x] Touched code is covered by tests
 - [ ] Documentation has been updated if necessary
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by kovrus** [comment]
```
io.crate.protocols.postgres.SslReqHandlerIntegrationTest > testReloadSslContextOnKeyStoreChange FAILED
```

seems to be flaky :/ not sure what can be done here except raising the timeout for the assertion.

**Comment by mfussenegger** [comment]
> not sure what can be done here except raising the timeout for the assertion. might be related to stale resources on jenkins? 

Sounds good

**Comment by kovrus** [comment]
👍 sure, i'll add `timestamp without time zone` for the rest of scalars that use timestamp data types.

**Comment by kovrus** [comment]
retest this please

**Comment by kovrus** [comment]
retest this please

**Pull request merged**
