### PR TITLE
reproduction

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
```

org.elasticsearch.ElasticsearchTimeoutException: Timeout while running `create table t2 (col1 integer, col2 string) clustered into 10 shards`
	at __randomizedtesting.SeedInfo.seed([B37AA2673C72CDDE:A484121952819FDB]:0)


[i.c.i.StaticInformationSchemaQueryTest] before test
[i.c.i.StaticInformationSchemaQueryTest] [StaticInformationSchemaQueryTest#testIsNotNull]: setting up test
[i.c.i.StaticInformationSchemaQueryTest] [StaticInformationSchemaQueryTest#testIsNotNull]: all set up test
[i.c.p.s.SetSessionPlan   ] [T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits
[o.e.c.m.MetadataCreateIndexService] [masterService#updateTask][T#1]]] [q.t1] creating index, cause [api], shards [7]/[0]
[o.e.c.r.a.AllocationService] [masterService#updateTask][T#1]]] updating number_of_replicas to [1] for indices [q.t1]
[o.e.c.m.MetadataCreateIndexService] masterService#updateTask][T#1]]] [q.t2] creating index, cause [api], shards [10]/[0]
[o.e.c.r.a.AllocationService] [masterService#updateTask][T#1]]] updating number_of_replicas to [1] for indices [q.t2]
[2024-07-29T03:17:42,124][ERROR][o.e.t.IntegTestCase      ] [[Time-limited test]] Timeout on SQL statement: create table t2 (col1 integer, col2 string) clustered into 10 shards org.elasticsearch.ElasticsearchTimeoutException: Timeout while running `create table t2 (col1 integer, col2 string) clustered into 10 shards`
```

`./mvnw -pl server test -Dtest=io.crate.integrationtests.StaticInformationSchemaQueryTest -Dtests.method=testIsNotNull -Dtests.seed=B37AA2673C72CDDE -Dtests.locale=pt-AO -Dtests.timezone=America/Nome -Dtests.iters=20`

got 4 failures out of 20 iterations

### CODE REVIEW

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
I have it running with 20iters on each run, but wrapped with an `untilfail.sh` script
I have 0 failures both on 5.7 and 5.8 branches locally, after ~1h.

**Comment by matriv** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
For me it fails quote often locally on 5.8, 5.7 and even 5.6 branch. Not a blocker for 5.8.1, proceeding.

**Pull request closed without merging**
