### PR TITLE
Don't use a symlink path for selecting current release notes

### PR DESCRIPTION
**Pull request by seut**
Symlinks created on *nix systems and commited into git won't work under windows and such will break building the windows distribution.

See related jenkins failure https://jenkins.crate.io/job/CrateDB/job/Release/job/tarball/job/release_crate_tarball_x64_windows/50/.

### CODE REVIEW

**Review by amotl — APPROVED** [review]
Thanks for finding the root cause. 💯

**Comment by seut** [comment]
@mergifyio refresh

**Comment by matriv** [comment]
@mergifyio backport 5.3

**Comment by matriv** [comment]
@mergifyio backport 5.2

**Pull request merged**
