### PR TITLE
adds filtering support to the nested loop operation

### PR DESCRIPTION
**Pull request by seut**
use integrated filter now instead of adding a filter projection to the nested loop

### CODE REVIEW

**Comment by seut** [comment]
@dobe pls review

**Comment by seut** [comment]
@mfussenegger can you pls continue reviewing (fixup) ?

**Comment by mfussenegger** [comment]
I think the equals/hashCode implementation of the RowFilter isn't really required since it is never used in a Set/HashMap etc. so identity equality would be enough.

Anyway. Lgtm

**Comment by seut** [comment]
the Predicate interface enforces at least the equals() implementation... hashCode can be removed sure (I generated both ;-)

**Pull request merged**
