### PR TITLE
tests: Use data node session when running a query

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Follow up to https://github.com/crate/crate/commit/42fbef6de34df0df62462c9080a8502719be6c89

~~Session object was not used~~ UPD: Did some tests with intentional wrong replica value and test was passing with many repetitions. 

Reverted to the very initial state but reduced 30 selects to 10 as I confirmed locally that it's enough.

Relates to https://github.com/crate/crate/pull/15272#discussion_r1438104671 and  https://github.com/crate/crate/pull/15272#discussion_r1438130014

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
Something is wrong here, I tried sending some ransom value in `addGeneratedValues() `and got this tests passed with this PR, with master state (not using session) and also with running select 30 times.

Figuring out why I can store different values and it's not caught by assertions.

**Comment by BaurzhanSakhariev** [comment]
> Something is wrong here, I tried sending some random value in `addGeneratedValues() `and got this test passed with this PR, with master state (not using session) and also with running select 30 times.
> 
> Figuring out why I can store different values and it's not caught by assertions.

Looks like executing query against 2 data node doesn't guarantee  that we are fetching primary/replica.

I intentionally updated `Index.addGeneratedValues `to return some static wrong value which is never equal to random function in tests returning values <=100. Locally tests still passed and on CI with 100 Repeat =100 I had 92 failures, so at least 8 times it hit primary twice.

I added `ensureGreen`, removed where = PK, and did 10 selects in a row  (similar to what we do in `test_generated_non_deterministic_value_is_consistent_on_primary_and_replica`) on only with such setup I managed to get constant failures with "intentionally wrong Indexer"

**Review by matriv — APPROVED** [review]
thx for explanation!

**Pull request merged**
