### PR TITLE
Enable annotation processing for benchmarks

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

Enable annotation processing in maven compiler plugin to get jmh benchmarks working again.

Annotation processing is disabled by default from jdk 22 https://inside.java/2023/10/23/quality-heads-up/ which breaks the jmh benchmark execution because no annotations are processed resulting in:

```
> java --add-modules jdk.incubator.vector -jar benchmarks/target/benchmarks.jar RowsBatchIteratorBenchmark
WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
	at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
	at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:124)
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:252)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:208)
```

https://stackoverflow.com/a/79096948

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
We [updated](https://github.com/crate/crate/commit/b0b0b95f9b8c24bb4814f1e3db0187767c462218) bundled JDK to 22 in 5.8. 

Should we backport this to 5.8?

**Review by BaurzhanSakhariev — APPROVED** [review]

**Review by matriv — APPROVED** [review]
thank you!

**Comment by matriv** [comment]
> We [updated](https://github.com/crate/crate/commit/b0b0b95f9b8c24bb4814f1e3db0187767c462218) bundled JDK to 22 in 5.8.
> 
> Should we backport this to 5.8?

and 5.9, I agree.

**Comment by mkleen** [comment]
👍

**Pull request merged**
