### PR TITLE
Added debug logging for job logs addition/removal

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Relates to https://github.com/crate/support/issues/395

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
I also wanted to add some prefix/suffix to "color" 3 possible log id sources (bulkExec, quickExec, singleExec) and then via debug logging to see which one doesn't have `remove` counterparts for add-s but opted out since UUID is not a string.

**Comment by BaurzhanSakhariev** [comment]
https://jenkins.crate.io/job/CrateDB/job/crate_on_pr/17418/testReport/junit/io.crate.gcs/GCSBlobContainerRetriesTests/testReadBlobWithReadTimeouts/

retest this please

**Review by mfussenegger — COMMENTED** [review]
I don't really see what we'd gain by this.
The log would just mirror `sys.jobs` and `sys.jobs_log` except


> Do you think encoding job source in UUID would be helpful to at least narrow down the problem?

Encoding info into the uuid could be done, but this particular case seems way too special cased.

**Comment by BaurzhanSakhariev** [comment]
>Encoding info into the uuid could be done, but this particular case seems way too special cased.

I didn't get this, we could encode more info in general or introduce a dedicated method for Sessions and encode info only there?

**Pull request closed without merging**
