### PR TITLE
Upgrade Lucene to 9.4.2 and other libs to latest version

### PR DESCRIPTION
**Pull request by matriv**

### CODE REVIEW

**Comment by matriv** [comment]
No changes between `9.4.0` and `9.4.2` for the test files we override.

**Comment by matriv** [comment]
Unrelated `io.crate.integrationtests.disruption.seqno.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability`: timed out

**Comment by matriv** [comment]
retest this please

**Comment by mkleen** [comment]
Can we separate the version bumps of the libs ? Are they depending on each other ?

**Comment by mkleen** [comment]
> Can we separate the version bumps of the libs ? Are they depending on each other ?

ah you did that already.

**Review by mkleen — APPROVED** [review]
👍

**Pull request merged**
