### PR TITLE
git ignore all data and logs folders

### PR DESCRIPTION
**Pull request by seut**

### CODE REVIEW

**Comment by mfussenegger** [comment]
Where are those folders coming from? I don't have those?

**Comment by chaudum** [comment]
I haven't had them neither, but I know that I remove them from the ignore files with my last commit https://github.com/crate/crate/pull/5589/files#diff-b68a7d013d8bf578693d7dc4fc726945L2

**Comment by seut** [comment]
If I start a node, I have these folders under app/

**Comment by mfussenegger** [comment]
Could we make the path more specific then? We've a `io.crate.data` package, with this gitignore addition it would also ignore new classes that we add there.

**Comment by chaudum** [comment]
I think having multiple gitignore files in several folders is a bad practice because you completely lose the overview of what is ignored and what not. that is also why I consolidated the ignore file.
I would rather add

```
app/logs
app/data
```

to the gitignore on root

**Comment by chaudum** [comment]
right. maybe also move it down to https://github.com/crate/crate/pull/5608/files#diff-a084b794bc0759e7a6b77810e01874f2R42

```
app/data/
app/logs/
```

**Comment by seut** [comment]
@mfussenegger good point. @chaudum yep will change

**Pull request merged**
