### PR TITLE
WIP: Add "table" to non-reserved keywords

### PR DESCRIPTION
**Pull request by seut**
This WIP commit adds `table` to non-reserved keywords. All tests passes, but I'm not sure if this is a good idea.
Relates #8961.

PostgreSQL allows to use `table` unquoted as a column alias, e.g.
```
SELECT table_schema AS schema, table_name AS table FROM information_schema.tables;
 schema | table 
--------+-------
 public | t1
(1 row)
```

while it forbids using it as a table_name, e.g.
```
create table table (id int);
ERROR:  syntax error at or near "table"
LINE 1: create table table (id int);
```

By adding it to the non-reserved keywords, it could be also used as a table name, which did not raise any issues when I did some basic tests (creating the table, querying it + system tables).

@mfussenegger @kovrus whats your input here?

### CODE REVIEW

**Comment by kovrus** [comment]
`table` is a reserved word in all SQL standards and probably most dialects including [PostgreSQL](https://www.postgresql.org/docs/current/sql-keywords-appendix.html). It seems that some database allows using it as identifiers in certain places but only if it follows certain rules, see https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15

Adding the `table` to the keyword to the non-reserved keywords won't be a breaking change, but it is not clear what kind of side effects we will face as a result, also it might affect the future extension of the parser grammar by making it more ambiguous.

I think there should be a way how we can support using `table` as an alias without removing it from the reserved keywords.
Also, in pg is it the case for only the `table` word or for all keywords?

**Comment by mfussenegger** [comment]
I've similar concerns as raised by @kovrus 

> I think there should be a way how we can support the usage of table as an alias without removing it from the reserved keywords.

Do you have a concrete idea how we'd accomplish that?

**Comment by kovrus** [comment]
> Do you have a concrete idea how we'd accomplish that?

I would need to look at it. Just a thought from the top of my head, maybe we can just implement some of `enter<AST NODE>` visitor methods and just quote the keyword identifier in some cases?

**Comment by seut** [comment]
@kovrus @mfussenegger 
Thank you a lot for this valuable input. 
I've created an issue out of this discussions, see https://github.com/crate/crate/issues/10818.

**Pull request closed without merging**
