### PR TITLE
Rename GCS classes to GoogleCloudStorage

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

Follow-up https://github.com/crate/crate/pull/15598

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
What's wrong with the abbreviation? Not everyone has ulti-wide monitors.

**Comment by mkleen** [comment]
> What's wrong with the abbreviation? Not everyone has ulti-wide monitors.

The main reason for this was to stay consistent with the naming of the open-search gcs plugin. However, I am also ok with the abbreviation.

**Comment by matriv** [comment]
I'm fine with both of them, but maybe the existing one (the abbreviation) is better as it's shorter.

**Comment by mkleen** [comment]
Let's rename once everyone has ultra-wide monitors :-)

**Pull request closed without merging**
