### PR TITLE
improve top level index pages

### PR DESCRIPTION
**Pull request by nslater**

### CODE REVIEW

**Comment by nslater** [comment]
basing this on `nomi/reshuffle-sql-ref` but will re-base to master once the `nomi/reshuffle-sql-ref` branch is merged, and then merge this pr

**Comment by nslater** [comment]
see https://github.com/crate/crate/pull/6241

**Comment by mfussenegger** [comment]
PR_itests is failing?

`[Errno 2] No such file or directory: '/var/lib/jenkins/workspace/CrateDB/crate_pr_itests/blackbox/docs/src/doc_tests/../../use/ddl/basics.txt'`

**Comment by nslater** [comment]
this work has been superseded

**Pull request closed without merging**
