### PR TITLE
Adding elasticsearch phonetic analyzer / tokenizer

### PR DESCRIPTION
**Pull request by robd003**
## Summary of the changes / Why this improves CrateDB
Let's you match results phonetically

## Checklist

 - [X] User relevant changes are recorded in ``CHANGES.txt``
 - [X] Touched code is covered by tests
 - [X] Documentation has been updated if necessary
 - [X] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [X] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by robd003** [comment]
Fixing the test cases, will push another commit

**Comment by mfussenegger** [comment]
ok to test

**Comment by seut** [comment]
@robd003 Thanks a lot for this contribution, we will look into this asap.

**Comment by robd003** [comment]
@suet I'm going to work on fixing the test cases this weekend. What else do you need so that we can get this merged in?

**Comment by marregui** [comment]
Hi @robd003 what would be your approach on solving the test cases?. Thank you

**Comment by robd003** [comment]
@marregui Could I get some help from the Crate staff to fix the test cases?

**Comment by seut** [comment]
@robd003 
I've added a couple of commits to fix the tests and add documentation for the new token filter.
If you're ok with this, I'd continue squashing and merging this feature once approved.

**Comment by robd003** [comment]
@seut Thanks a bunch! Let's get this merged in :)

**Comment by marregui** [comment]
retest this please

It seems the gradle daemon was killed under the hood.

**Comment by seut** [comment]
@robd003 
We've merged in in, thanks again a lot for this contribution!

**Pull request merged**
