### PR TITLE
Fix some spelling mistakes

### PR DESCRIPTION
**Pull request by asdf2014**
## Summary of the changes / Why this improves CrateDB

Fix some spelling mistakes

## Checklist

 - [x] User relevant changes are recorded in ``CHANGES.txt``
 - [x] Touched code is covered by tests
 - [x] Documentation has been updated if necessary
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mfussenegger** [comment]
ok to test

**Comment by mfussenegger** [comment]
Thank you for the contribution :+1: 

We'll merge this once we've sorted out some issues we're currently having with our testing infrastructure.

**Comment by asdf2014** [comment]
@mfussenegger You are welcome. Thanks for your approval.

**Comment by mfussenegger** [comment]
retest this please

**Comment by mfussenegger** [comment]
retest this please

**Comment by mfussenegger** [comment]
retest this please

**Comment by mfussenegger** [comment]
retest this please

**Pull request merged**
