### PR TITLE
Remove unused FromRowWithSubscript

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Need it in the drop-column branch in order not to deal with unused method

### CODE REVIEW

**Comment by mkleen** [comment]
> Need it in the drop-column branch in order not to deal with unused method

This pr removes unused methods from the ValueExtractor which is relevant for the drop-column branch.

**Review by mkleen — APPROVED** [review]

**Comment by BaurzhanSakhariev** [comment]
LR unrelated failure

retest this please

**Comment by BaurzhanSakhariev** [comment]
https://github.com/Mergifyio refresh

**Comment by BaurzhanSakhariev** [comment]
https://github.com/Mergifyio rebase

**Pull request merged**
