### PR TITLE
Allow Parallel Restore Operations

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

https://github.com/elastic/elasticsearch/commit/c5b3ac557857da9d8571e4fdcb8eaf6d4a7b7b11

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mkleen — APPROVED** [review]
💯 👍

**Comment by seut** [comment]
Why are these changes not applied?
- https://github.com/elastic/elasticsearch/pull/36397/files#diff-a0853be4492c052f24917b5c1464003d
- https://github.com/elastic/elasticsearch/pull/36397/files#diff-5811e62586066fe46b8c59c7e5d1aaf1

**Comment by mfussenegger** [comment]
> Why are these changes not applied?
> 
> * https://github.com/elastic/elasticsearch/pull/36397/files#diff-a0853be4492c052f24917b5c1464003d

Parts were applied in https://github.com/crate/crate/commit/4170a7bdac4a6ef632bbfbf330b708a6902d6a1e 

> * https://github.com/elastic/elasticsearch/pull/36397/files#diff-5811e62586066fe46b8c59c7e5d1aaf1

I'm confused about this one, isn't that this here https://github.com/crate/crate/pull/10468/files#diff-5811e62586066fe46b8c59c7e5d1aaf1 ?

**Comment by seut** [comment]
> Parts were applied in 4170a7b

Ah my fault, was reading the wrong line.

> I'm confused about this one, isn't that this here https://github.com/crate/crate/pull/10468/files#diff-5811e62586066fe46b8c59c7e5d1aaf1 ?

Right, I must have missed that. Sorry!

**Review by seut — APPROVED** [review]

**Pull request merged**
