### PR TITLE
Increase timeouts in MasterDisruptionIT

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

See

- https://github.com/crate/crate/commit/c646b689e10be76a15f84568e15481d21f1647ac
- https://github.com/elastic/elasticsearch/commit/55d6ef298ac23fca2961194e078ca28de10e826d

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by seut** [comment]
Afaik increasing the timeouts is only needed when https://github.com/elastic/elasticsearch/pull/51803 is applied.

The current issue with the flaky `MasterDistruptionIT.testVerifyApiBlocksDuringPartition` can be reproduced locally and I wonder if not something is broken as in this failing scenario the isolated node is the master and is not stepping down as a master even after it recognizes that the followers are gone. I think we should dive deeper here.

Reproduce args:
```./gradlew :server:test -Dtests.seed=14C3DBBAA3FB1D55 -Dtests.class=io.crate.integrationtests.disruption.discovery.MasterDisruptionIT -Dtests.nightly=true -Dtests.crate.slow=true -Dtests.method="testVerifyApiBlocksDuringPartition"```

**Comment by mfussenegger** [comment]
> Afaik increasing the timeouts is only needed when [elastic/elasticsearch@a051321](https://github.com/elastic/elasticsearch/commit/a0513217dba) and [elastic/elasticsearch@32c30c9](https://github.com/elastic/elasticsearch/commit/32c30c989ff4b4141a40a81da3594a1448a4e9cb) is applied.

Yes but we applied https://github.com/crate/crate/commit/c646b689e10be76a15f84568e15481d21f1647ac already, so the timeout increases are afaik already necessary for the MasterDisruptionIT.

We could investigate why the `testSeqNoCASLinearizability` was failing already despite not having caught up with the Lucene metadata storage, but I'm not sure if it is worth doing?


> The current issue with the flaky `MasterDistruptionIT.testVerifyApiBlocksDuringPartition` can be reproduced locally and I wonder if not something is broken as in this failing scenario the isolated node is the master and is not stepping down as a master even after it recognizes that the followers are gone. I think we should dive deeper here.
> 

Yes I reproduced it locally and after increasing the timeouts it doesn't fail anymore.
If there were an issue with the master not stepping down, shouldn't it still fail even with the timeout increase?

**Comment by seut** [comment]
> Yes but we applied c646b68 already, so the timeout increases are afaik already necessary for the MasterDisruptionIT.
> Afaik MasterDisruptionIT also only started failing after c646b68 got merged.

Ah ok right.

> We could investigate why the testSeqNoCASLinearizability was failing already despite not having caught up with the Lucene metadata storage, but I'm not sure if it is worth doing?

Yep maybe not worth doing.

> Yes I reproduced it locally and after increasing the timeouts it doesn't fail anymore.
> If there were an issue with the master not stepping down, shouldn't it still fail even with the timeout increase?

It also did not always fail locally, I guess you've run in repeated already to ensure its not flaky anymore...
I wonder if there is some kind of race condition, but we will see anyhow because then it should fail even with increase timeouts.

**Review by seut — APPROVED** [review]

**Comment by mfussenegger** [comment]
> It also did not always fail locally, I guess you've run in repeated already to ensure its not flaky anymore...

Yes I ran

```
until-error ./gradlew :server:test -Dtests.seed=14C3DBBAA3FB1D55 -Dtests.class=io.crate.integrationtests.disruption.discovery.MasterDisruptionIT -Dtests.nightly=true -Dtests.crate.slow=true -Dtests.method="testVerifyApiBlocksDuringPartition" -Dtests.nightly=true -Dtests.locale=gsw-LI -Dtests.timezone=America/Jujuy -Dtests.iters=20 --fail-fast
```

but with flaky stuff you never know for sure.

>  but we will see anyhow because then it should fail even with increased timeouts.

Right, if it keeps failing I'll have a closer look.

**Pull request merged**
