### PR TITLE
Fix perf regression caused by nested Fetch operators

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Addresses https://github.com/crate/crate/issues/15210#issuecomment-1868599482

With the new rule 'move_limit_beneath_join' we can have nested limit operators:
```
+----------------------------------------------------------------------------+
| QUERY PLAN                                                                 |
+----------------------------------------------------------------------------+
| Eval[name AS employee, name AS office] (rows=unknown)                      |
|   └ Fetch[name, office_id, id, name] (rows=unknown)                        |
|     └ Limit[50000::bigint;0] (rows=unknown)                                |
|       └ NestedLoopJoin[LEFT | (office_id = id)] (rows=unknown)             |
|         ├ Rename[name, office_id, id] AS e (rows=unknown)                  |
|         │  └ Fetch[name, office_id, id] (rows=unknown)                     |
|         │    └ Limit[50000;0] (rows=unknown)                               |
|         │      └ Collect[doc.employees | [_fetchid] | true] (rows=unknown) |
|         └ Rename[o._fetchid] AS o (rows=unknown)                           |
|           └ Collect[doc.offices | [_fetchid] | true] (rows=unknown)        |
+----------------------------------------------------------------------------+
```
But because RewriteToQueryThenFetch failed to reach(and rewrite) 'Collect[employees ..]', RewriteToQueryThenFetch added another Fetch on top of the inner limit which caused a perf regression.

With this change, RewriteToQueryThenFetch adds only a single Fetch operator:
```
+-----------------------------------------------------------------------------------------+
| QUERY PLAN                                                                              |
+-----------------------------------------------------------------------------------------+
| Eval[name AS employee, name AS office] (rows=unknown)                                   |
|   └ Fetch[name, office_id, id, name] (rows=unknown)                                     |
|     └ Limit[50000::bigint;0] (rows=unknown)                                             |
|       └ NestedLoopJoin[LEFT | (office_id = id)] (rows=unknown)                          |
|         ├ Rename[e._fetchid, office_id, id] AS e (rows=unknown)                         |
|         │  └ Limit[50000;0] (rows=unknown)                                              |
|         │    └ Collect[doc.employees | [_fetchid, office_id, id] | true] (rows=unknown) |
|         └ Rename[o._fetchid] AS o (rows=unknown)                                        |
|           └ Collect[doc.offices | [_fetchid] | true] (rows=unknown)                     |
+-----------------------------------------------------------------------------------------+
```

perf before fix:
```
## Running Query:
   Statement:
     select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
   Concurrency: 1
   Iterations: 250
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [01:09<00:00,  3.59 requests/s]
Runtime (in ms):
    mean:    259.329 ± 1.751
    min/max: 253.723 → 455.401
Percentile:
    50:   256.915 ± 14.128 (stdev)
    95:   269.488
    99.9: 455.401
```

perf after fix:
```
## Running Query:
   Statement:
     select e.name as employee, o.name as office from employees e left join offices o on e.office_id = e.id limit 50000
   Concurrency: 1
   Iterations: 250
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [00:13<00:00, 19.17 requests/s]
Runtime (in ms):
    mean:    33.245 ± 0.629
    min/max: 30.720 → 91.633
Percentile:
    50:   31.895 ± 5.075 (stdev)
    95:   41.622
    99.9: 91.633

```

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
Hi @mkleen I just realized that this is a known issue, https://github.com/crate/crate/pull/15227#discussion_r1433977031. Could you have a look at this draft? I think it should resolve the perf issue but if not I would just close this and move on.

**Comment by mkleen** [comment]
> Hi @mkleen I just realized that this is a known issue, [#15227 (comment)](https://github.com/crate/crate/pull/15227#discussion_r1433977031). Could you have a look at this draft? I think it should resolve the perf issue but if not I would just close this and move on.

HI @jeeminso,

this looks good. Let's wrap this up. Thanks a lot!

**Comment by mkleen** [comment]
The actual issue is multiple limit operators in the original query. The nested fetch operators are just a result of that.

**Review by mkleen — APPROVED** [review]
good work! 👍

**Pull request merged**
