### PR TITLE
reuse content builder on COPY FROM CSV

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Reusing `XContentBuilder` is a valid scenario - there is a [test](https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java#L74-L91) for it in ES repo.

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
Reusing is a valid scenario - there is even a [test](https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java#L74-L91) for it in ES repo. 

Currently facing [this](https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java#L90) minor issue with flush:
> // we get a space at the start here since it thinks we are not in the root object (fine, we will ignore it in the real code we use)

**Comment by BaurzhanSakhariev** [comment]
Last commit mixes 2 approaches with suppliers/callables, adds some overhead to both, but we can roughly see the magnitude - looks not that big difference, only 5% better

```
Benchmark                                                      Mode  Cnt   Score   Error  Units
CsvReaderBenchmark.measureFileReadingIteratorForCSVReuseFalse  avgt   25  90,267 ± 1,406  us/op
CsvReaderBenchmark.measureFileReadingIteratorForCSVReuseTrue   avgt   25  86,027 ± 0,986  us/op
```

However, with reusing XContentBuilder we can actually go to the next step - resolve type once on reading first values line and then instead of using` field(f).value(Object v)` which uses `unknownValue(value, Map.of());` with lots of `instanceof`  =- so we can tune reused object a little bit.

**Comment by mfussenegger** [comment]
I think re-using the builder instance could be encapsulated within the CsvParser. That would make the impact of the change much smaller, reduce the coupling and would probably still yield close to the 5% of performance improvement

**Comment by BaurzhanSakhariev** [comment]
> I think re-using the builder instance could be encapsulated within the CsvParser

That was my initial intention, the only reason of propagating reused instance throughout different levels was need to close it at the upper level together with `currentReader` as their lifecycle is somehow correlated.

**Pull request closed without merging**
