### PR TITLE
Added a TimeZone parameter response for Django psycopg2 clients

### PR DESCRIPTION
**Pull request by robd003**
Issue: https://github.com/crate/crate/issues/7468

### CODE REVIEW

**Comment by mfussenegger** [comment]
ok to test

**Comment by mfussenegger** [comment]
Thanks for your contribution. The change is looking good but we require a [signed CLA](https://crate.io/community/contribute/cla/) in order to merge it.

If you could also provide a minimal django snippet that shows this issue, or contribute to [crate-qa](https://github.com/crate/crate-qa) (see `tests/client_tests`) a small test case that would be terrific and prevent us from breaking things in the future.

**Comment by robd003** [comment]
@mfussenegger I've already signed the CLA and put my GitHub username in the agreement. Do you need me to link to the document somehow?

I'll go look at writing a test for crate-qa.

**Comment by mfussenegger** [comment]
> I've already signed the CLA and put my GitHub username in the agreement. Do you need me to link to the document somehow?

Sorry, I just double checked. Turns out the list was slightly outdated.

**Pull request merged**
