### PR TITLE
Add ConcurrentSnapshotsIT tests

### PR DESCRIPTION
**Pull request by matriv**
## Summary of the changes / Why this improves CrateDB

Follows: https://github.com/crate/crate/pull/13263

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by matriv** [comment]
`testConcurrentSnapshotWorksWithOldVersionRepo` is not backported so far, it's quite complex to do so, will have another try and update the PR description accordingly, if it's skipped after all.

**Comment by mkleen** [comment]
See commit messages.

**Comment by mkleen** [comment]
All tests except `testConcurrentOperationsLimit` are passing. There are a few issue with all the tests:
- All calls referring to `awaitClusterState` using a `ClusterStateObserver` will time out, what works is to switch to a busy wait, but it is not elegant.
- `waitForBlock` will block the whole the operation may not proceed
- The tests executes very slow. The same tests in elasticsearch takes around 2 minutes, this version takes 6 minutes on my local machine.

**Comment by mfussenegger** [comment]
Going to integrate this over several PRs, see https://github.com/crate/crate/pull/13478 & https://github.com/crate/crate/pull/13483

**Pull request closed without merging**
