### PR TITLE
Fix ClassCastException when building Lucene queries involving nested arrays

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Fixes https://github.com/crate/crate/issues/16299. It will take quite a bit of time to build as optimized queries as non-nested arrays. We could start by preventing the exceptions/support slow queries.

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
I think we should handle it this way and let generating improved queries to be a feature, WDYT @seut @romseygeek @matriv

**Comment by matriv** [comment]
From what I see in our docs, we even forgot to drop the note that you cannot define nested arrays in `create table`, so maybe it's fine to treat this as a feature. If so, I'd say that we should provide a fix, so that we don't throw an ugly `ClassCastException`. Let's hear other's opinion first.

**Comment by mfussenegger** [comment]
> From what I see in our docs, we don't mention anything about what is supported on nested arrays, so maybe it's fine to treat this as a feature

You can also get nested arrays with something like:

```sql
create table tbl (os array(object as(xs int[])))
```

Some queries also work, e.g.:

```sql
insert into tbl (os) values ([{xs = [1, 2, 3]}, {xs=[8, 9]}]);
select * from tbl where [1, 2, 3] = any(os['xs']);
```

We should be able to handle queries on nested arrays somewhat efficiently by pre-filtering them with a TermsQuery - in the index the values are de-duplicated and flattened out - and a second filter that uses the generic function query.

**Comment by jeeminso** [comment]
Thanks @mfussenegger , then do you see this as a bug?

**Comment by mfussenegger** [comment]
> Thanks @mfussenegger , then do you see this as a bug?

Yes but imho we should come up with a proper fix that ensures there's no `ClassCastException` thrown in the first place.
Adding the logic as it's currently in this PR could mask other bugs.

**Comment by jeeminso** [comment]
https://github.com/crate/crate/issues/16299#issuecomment-2357069370, closing.

**Pull request closed without merging**
