### PR TITLE
Use correct regex case-insensitive match operator

### PR DESCRIPTION
**Pull request by jayeff**
## Summary of the changes / Why this improves CrateDB

This fixes operator for "Matches regular expression (case insensitive)" as documented on [Comparison Operators doc page](https://crate.io/docs/crate/reference/en/4.7/general/builtins/comparison-operators.html#where-clause-operators) and now matches correctly documented operator on [Selecting data doc page](https://crate.io/docs/crate/reference/en/4.7/general/dql/selects.html#regular-expressions)

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jayeff** [comment]
retest this please

**Comment by seut** [comment]
@Mergifyio rebase

**Comment by jayeff** [comment]
retest this please

**Review by mfussenegger — APPROVED** [review]

**Comment by jayeff** [comment]
@Mergifyio rebase

**Pull request merged**
