### PR TITLE
Update licensing boilerplates

### PR DESCRIPTION
**Pull request by norosa**
this PR closes https://github.com/crate/crate/issues/11184

the scope of changes necessary to fully satisfy the work identified in https://github.com/crate/crate/issues/11184 was bigger than I expected. thankfully, the changes are very repetitive and my editor was able to make quick work of most of this

I split my work into sections to make things easier for me and anybody who wants to review:

- Make sure that all appropriate files have the standard "commercial license" paragraph (first commit)
- Standardize our company name (three commits)
- Add the boilerplate to all files that appear to be missing it (last commit)

(we might want to squash these before merging?)

the commits can be applied separately, so if it is desired, I can cherry-pick them into separate PRs

the middle three commits are not required for https://github.com/crate/crate/issues/11184. I added them because they were very easy to automate and I figured I may as add them while I'm making changes here. if they make the review too difficult, I can drop them from this PR no problem

the last commit is the one that required the most judgment on my part (with regards to which files to update). these changes probably deserve the most scrutiny

each commit message has an extended description describing the method I used to make the change (including heuristics, and so on)

you may notice that the number of empty newlines before and after the boilerplate varies from file to file. when updating an existing boilerplate section, I attempted to make no other modifications. for files that required me to add a boilerplate, I tried to match the local conventions in each instance (with regards to file type, surrounding content, and so on)

### CODE REVIEW

**Review by amotl — APPROVED** [review]
I took a look at some samples and I believe it will be good to go if CI doesn't complain. That was indeed a huge editing task, thanks a stack!

**Comment by norosa** [comment]
@amotl thanks! not sure re backporting. will defer to @mfussenegger or @seut

**Review by seut — APPROVED** [review]
👍 great, thanks!

**Comment by seut** [comment]
@norosa Related to backport, we could do but no strong opinion here, I'd treat it as optional. Also I don't see issues related to future backports and file conflicts as only headers are changed.

**Comment by norosa** [comment]
thanks, both! I will omit the backporting

**Pull request merged**
