### PR TITLE
Add Helm chart serveable by GitHub pages/Helm Hub

### PR DESCRIPTION
**Pull request by OJFord**
## Summary of the changes / Why this improves CrateDB

See helm/charts#16318 for background on the
chart's development.

helm/charts is now deprecated, and moving to a sort of open registry
model - anyone can create and use their own Helm repository (of which
helm/charts' `stable` and `incubator` dirs are large examples) and
optionally register it with Helm Hub so that users can easily discover
it.

This commit packages the chart from above PR such that it can be served
by GitHub pages. With that in place, a PR can be made to
https://github.com/helm/hub for the repo's inclusion on
https://hub.helm.sh.

## Checklist

 - [ ] User relevant changes are recorded in ``CHANGES.txt``
 - [x] Touched code is covered by tests
 - [ ] Documentation has been updated if necessary
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

(If you agree with the principle I'll update docs appropriately with how to use it - I just anticipate that might change as a result of review.)

### CODE REVIEW

**Comment by mfussenegger** [comment]
Thank you for the contribution and efforts you put into creating a helm chart for CrateDB.

I'm not sure if `crate/crate` is the best place to host this. The core contributors to CrateDB itself are not necessarily people who have k8s knowledge, even less so with the helm system on top. So I'd rather keep this separate. (So that changes to the helm chart also don't trigger our CI, and that if there is special CI tasks for the helm charts, that we don't need to run them on each change to CrateDB itself)

So either we'd have to create a `crate/helm` repo, or something that we've had in our minds is creating a `crate-community` organization for projects that are community maintained. What do you think of that?

**Comment by OJFord** [comment]
@mfussenegger Yep, that makes total sense to me, particularly because `docs` (which is the mandatory sub-directory for GH pages) is already a symlink to other docs, and is what I alluded to:

> If you agree with the principle I'll update docs appropriately with how to use it - I just anticipate that might change as a result of review.

🙂 

Of course, I couldn't PR to 'new repository', so I thought easiest to have the conversation here, and then I can move it to your preferred location.

**Comment by mfussenegger** [comment]
We've created a new repository (https://github.com/crate/helm-charts), could you create the PR against that repo? I'll close the PR here now.

We might use the same repo also for other helm charts in the future, so maybe you can put the CrateDB helm chart into a `cratedb` folder.

Thank you again for your efforts.

**Comment by OJFord** [comment]
Great, thanks!

**Pull request closed without merging**
