### PR TITLE
Fix create snapshot of concrete tables only

### LINKED ISSUE #11365: CREATE SNAPSHOT TABLES stores too much data
**CrateDB version**: 4.5.1

**Problem description**:

`CREATE SNAPSHOT TABLE` back ups too much data. Not only schema and records for the corresponding table is stored but additionally all...

* partitioned tables (without records)
* views
* user defined functions
* users
* privileges

After running `RESTORE SNAPSHOT ALL` these are all restored.

**Expected behaviour**: Only table `a` and `a` records are restored

**Steps to reproduce**:

Start with an empty cluster and create sample entities:

```
create table a (a text);
insert into a (a) values ('a'), ('b');

create table b (b text) partitioned by (b);
insert into b (b) values ('a'), ('b');

create view v as select name from sys.nodes;

create user usera;
GRANT DML TO usera;

create function one() returns integer language javascript as 'function one() { return 1; }';
```

Afterwards add a new repository and create a snapshot for table `a`:

```
CREATE REPOSITORY testrepo TYPE fs WITH (location='testrepo', compress=true);
CREATE SNAPSHOT testrepo.snap TABLE a;
```

Now go to a new empty cluster. Add the repository and do a restore all:

```
CREATE REPOSITORY testrepo TYPE fs WITH (location='testrepo', compress=true);
RESTORE SNAPSHOT testrepo.snap ALL;
```

Table `a` + records, `b` (without records), view, UDF, user and privilege are restored.

### PR DESCRIPTION
**Pull request by seut**
The ``CREATE SNAPSHOT`` logic always included the global meta state
even if only concrete (partitioned) tables or partitions were defined
to be stored.
Thus more metada data was stored as the user wanted to.

This commit changes the logic now to only include possible partition
table templates beside the concrete indices but no gobal meta state.
The global state is only stored if ``ALL`` is used.

Fixes #11365.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Doesn't this mean that it is no longer possible to take a snapshot of a subset of the tables of a cluster and restore it including the users and everything?

Say you have a production cluster and want to create a snapshot for a staging environment, but you don't want to include the largest tables, or all partitions of the largest tables.

We' need to have some kind of `CREATE SNAPSHOT METADATA` equivalent?


We recently extended the RESTORE command with the `data_sections` options, isn't that good enough to only restore the tables?

**Comment by mfussenegger** [comment]
On second thought I guess you could still take a full snapshot and then only restore the individual tables. But that would mean that you always have to add all tables to the snapshot.

I'm not sure which is worse and I'm also not sure if it is a good idea to backport this behavior change as a fix.

**Comment by seut** [comment]
@mfussenegger 

> Doesn't this mean that it is no longer possible to take a snapshot of a subset of the tables of a cluster and restore it including the users and everything?

Yes right, but a) I'm not sure if this is really the expected behaviour and b) it also restores empty partition tables even when the are not part of the wanted subset (templates were restored).

> We' need to have some kind of CREATE SNAPSHOT METADATA equivalent?

Right, but this would be a feature and couldn't be backported.
I plan to follow up here and support it at master (4.6) only.

> We recently extended the RESTORE command with the data_sections options, isn't that good enough to only restore the tables?

True, but users expected that the `RESTORE ALL` only restores what they explicitly stored on snapshot creation.
I think the "it restores empty partition tables even that they were not explicitly included on snapshot creation" is the biggest issue with the current state.

**Comment by mfussenegger** [comment]
> I think the "it restores empty partition tables even that they were not explicitly included on snapshot creation" is the biggest issue with the current state.

Could we limit the change to only exclude them, but still include the remaining meta data? 

I agree that the behavior is not fully intuitive and might not match that expecations of a user, but changing it to exclude all metadata could break existing workflows

**Comment by seut** [comment]
> Could we limit the change to only exclude them, but still include the remaining meta data?

> I agree that the behavior is not fully intuitive and might not match the expecations of a user, but changing it to exclude all metadata could break existing workflows

We could but I think the existing workflow were broken by the new ``RESTORE ALL`` behaviour introduced in ``4.5.0``.
Before that, ``RESTORE ALL`` never restored anything beside tables, now it does. That's why it now users complain that more data is restored than they expected (caused by more data is stored than expected).

**Review by mfussenegger — APPROVED** [review]
> We could but I think the existing workflows were broken by the new RESTORE ALL behaviour introduced in 4.5.0.
Before that, RESTORE ALL never restored anything beside tables, now it does.

Ah gotcha. What a mess 🤷

So the plan was to exclude metadata with `CREATE SNAPSHOT TABLES` with this fix, but also follow up and add an option to only snapshot the metadata without tables?


If so - okay I'm convinced :)

**Comment by seut** [comment]
Yes its a mess ;) I should have a explained the current situation more detailed, sorry.

**Pull request merged**
