### PR TITLE
Fix is-node-master flag in UDC ping task

### PR DESCRIPTION
**Pull request by seut**
`clusterService.localNode().isMasterNode()` tells if the current
node *can* be a master node (has the master node role), but not
if it *is* the current master node.

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
Is it internal improvement and not affecting some user facing things, i.e not a fix and don't need a CHANGES entry?

**Review by BaurzhanSakhariev — APPROVED** [review]
Left a comment - LGTM if changes are not needed

**Comment by seut** [comment]
> Is it internal improvement and not affecting some user facing things, i.e not a fix and don't need a CHANGES entry?

Yes as the UDC ping task result is only used internally by Crate.io to collect CrateDB usages, this change does not affect any user.

**Comment by seut** [comment]
@BaurzhanSakhariev I've pushed another commit to rename the `Rename DiscoveryNode.isMasterNode()` to `isMasterEligibleNode()` to avoid any further confusion and misuse.

**Review by BaurzhanSakhariev — APPROVED** [review]
Good idea to rename 👍

**Pull request merged**
