### PR TITLE
start ExecutionSubContext in reverse order

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Comment by bogensberger** [comment]
ack

**Comment by seut** [comment]
if subContexts is not a concurrent map anymore, all accesses to it must be synchronized, not only the remove call. otherwise this leads to race conditions on concurrent get/remove calls.

**Comment by mfussenegger** [comment]
Afaik the `get` doesn't need to be synchronized as it is more or less just a lookup in an array. 
As long es there are no concurrent put operations that might resize the array that should be safe. (Though, since the underlying array isn't volatile `get` might return values that have already been removed, but in this case this doesn't really result in any kind of errors)

**Comment by chaudum** [comment]
ack

**Pull request merged**
