### PR TITLE
Update config module name

### PR DESCRIPTION
**Pull request by mechanomi**
the upstream name has changed in most recently docs theme package

- [x] add min version for theme (https://github.com/crate/crash/pull/309#discussion_r339545930)

### CODE REVIEW

**Comment by mfussenegger** [comment]
Does this need backporting on all release branches, so that new doc builds on those branches keep working?

**Comment by mechanomi** [comment]
@mfussenegger yes, good catch. there's also this: https://github.com/crate/crash/pull/309#discussion_r339545930

I'll come back to this PR once the new theme is released and take care of both issues

**Comment by mechanomi** [comment]
waiting for crate/crate-docs-theme#162

**Comment by mfussenegger** [comment]
Another option would be to wrap the import into a `try, except ImportError`, so that this can already be merged and is compatible for both crate-doc-themes version.

**Comment by mechanomi** [comment]
retest this please

**Pull request merged**
