### PR TITLE
Fix `GraalVM Security Guide` missing link

### LINKED ISSUE #10913: Missing link
###  Documentation feedback

 
- Page title: User-defined functions
- Page URL: https://crate.io/docs/crate/reference/en/latest/general/user-defined-functions.html
- Source: https://github.com/crate/crate/blob/4.3/docs/general/user-defined-functions.rst

---

https://crate.io/docs/crate/reference/en/4.3/general/user-defined-functions.html#javascript

```Please refer to `GraalVM Security Guide`_ for more detailed information```

In this section the link to "GraalVM Security Guide" is not rendered. Likely because it's used within bold text and nested inline markup isn't supported.

### PR DESCRIPTION
**Pull request by HoussemNasri**
Fixes #10913

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mechanomi — APPROVED** [review]

**Comment by mechanomi** [comment]
thank you for your contribution, @HoussemNasri!

**Comment by seut** [comment]
ok to test

**Comment by seut** [comment]
@HoussemNasri Thank you a lot for that fix. May I ask you to point this PR to the MASTER branch instead?

**Comment by HoussemNasri** [comment]
> @HoussemNasri Thank you a lot for that fix. May I ask you to point this PR to the MASTER branch instead?

Should I create another PR or there is a faster way?

**Comment by amotl** [comment]
> Should I create another PR or there is a faster way?

You can edit it by pressing "edit" on the right hand side of the top of the page.

**Comment by HoussemNasri** [comment]
@amotl Like that?

**Comment by amotl** [comment]
Thanks. Now we see that there are many conflicting files. So, I humbly ask you to rebase your branch on top of the current "master" branch.

> Should I create another PR?

If you don't know how to perform the rebase operation easily, it might well be a good idea to submit a new PR, given that the change is really small.

**Comment by HoussemNasri** [comment]
Thanks for replying, Unfortunately, I am not familiar with rebase, since it's only a small change I will close this PR and open a new one.

**Pull request closed without merging**
