### PR TITLE
Exclude test code from codeql

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Comment by bmunkholm** [comment]
Thanks! Should we perhaps add yamllint to our auto checks in general?

**Review by bmunkholm — APPROVED** [review]

**Comment by mfussenegger** [comment]
Is there a way to test this without merging?

Github checks shows a configuration not found error:

https://github.com/crate/crate/pull/17058/checks?check_run_id=33530436724

Despite this now using a inline `config:` property?

**Comment by seut** [comment]
> Is there a way to test this without merging?
> 
> Github checks shows a configuration not found error:
> 
> https://github.com/crate/crate/pull/17058/checks?check_run_id=33530436724
> 
> Despite this now using a inline `config:` property?

Maybe by temporarily adding an 
```
on:
  workflow_dispatch:```

so you could trigger it manually on this branch?

**Comment by mfussenegger** [comment]
Based on https://github.com/crate/crate/actions/runs/12031546960/job/33541327071 it looks like it ran but the scanned files in https://github.com/crate/crate/security/code-scanning/tools/CodeQL/status/ still show tests.

@seut can you take over so I can focus on the relation metadata stuff? I thought this was a quick change to fit in between tests & reviews otherwise I wouldn't have started with it.

**Comment by seut** [comment]
@mfussenegger Yes sure, I'll take it over.

**Comment by seut** [comment]
@mfussenegger
It seems to me that the results at https://github.com/crate/crate/security/code-scanning/tools/CodeQL/status/ only show the results of the latest commit merged to master. Thus the changed inside the PR will only be visible after merging. Let's merge it?

**Pull request merged**
