### PR TITLE
Bump version to 5.6.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**

### CODE REVIEW

**Comment by matriv** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Review by matriv — APPROVED** [review]

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
@Mergifyio update

**Comment by BaurzhanSakhariev** [comment]
@Mergifyio refresh

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Comment by matriv** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Pull request merged**
