### PR TITLE
Update to Lucene 8.8.2

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

https://lucene.apache.org/core/8_8_2/changes/Changes.html

We could follow up on this at some point and make the compression per column
configurable or change some of the defaults. (E.g. `_id`)

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mkleen — APPROVED** [review]
👍

**Comment by mkleen** [comment]
There is nothing really exciting for us in the 8.8.2 release.

**Comment by mfussenegger** [comment]
> There is nothing really exciting for us in the 8.8.2 release.

It includes the 8.8.0 changes - which contains https://issues.apache.org/jira/browse/LUCENE-9378 among others. I think that is quite interesting.

**Comment by mkleen** [comment]
Ah of course. I missed that.

**Pull request merged**
