### PR TITLE
added documentation for srv discovery settings

### PR DESCRIPTION
**Pull request by chaudum**

### CODE REVIEW

**Comment by mfussenegger** [comment]
ack

**Comment by samek** [comment]
Hi, 

first of all very good feature - I was really wanting it. 

Is there a way to setup config in a way that it ignores the 4200 port ? 

We're using mesos-dns and if I dig _cratew._tcp.marathon.mesos SRV
 

    ; <<>> DiG 9.8.1-P1 <<>> _cratew._tcp.marathon.mesos SRV
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51426
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 3
     
    ;; QUESTION SECTION:
    ;_cratew._tcp.marathon.mesos.   IN      SRV
     
    ;; ANSWER SECTION:
    _cratew._tcp.marathon.mesos. 1  IN      SRV     0 0 4200 cratew-22476-s36.marathon.mesos.
    _cratew._tcp.marathon.mesos. 1  IN      SRV     0 0 4200 cratew-43456-s13.marathon.mesos.
    _cratew._tcp.marathon.mesos. 1  IN      SRV     0 0 4200 cratew-44541-s33.marathon.mesos.
    _cratew._tcp.marathon.mesos. 1  IN      SRV     0 0 4300 cratew-22476-s36.marathon.mesos.
    _cratew._tcp.marathon.mesos. 1  IN      SRV     0 0 4300 cratew-43456-s13.marathon.mesos.
    _cratew._tcp.marathon.mesos. 1  IN      SRV     0 0 4300 cratew-44541-s33.marathon.mesos.
     
    ;; ADDITIONAL SECTION:
    cratew-22476-s36.marathon.mesos. 1 IN   A       10.0.0.191
    cratew-43456-s13.marathon.mesos. 1 IN   A       10.0.0.129
    cratew-44541-s33.marathon.mesos. 1 IN   A       10.0.0.86


I get both ports 4200 and 4300. 

Now When starting crate with srv discovery It tries to connect to 4200 since it was returned from the dns. 

     [2015-07-29 09:54:11,891][WARN ][transport.netty          ] [U-Go Girl] exception caught on transport layer [[id: 0xa0bac41b, /10.0.0.136:55064 :> cratew-44541-s33.marathon.mesos/10.0.0.86:4200]], closing connection
     java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50) 


question is "is that a problem" and if there's a solution for it?

Thanks.

**Comment by chaudum** [comment]
@samek 
thanks for pointing that out. that is indeed a problem!
there are quite some discussions on github concerning this issue, having multiple ports per application/task.
https://github.com/mesosphere/marathon/issues/1112
with mesos 0.22 you have the ability to name ports (http://craigwickesser.com/2015/03/mesos-022-release/), but I haven't found an answer whether this is implemented in mesos-dns 0.2 already (https://github.com/mesosphere/mesos-dns/issues/107)

**Comment by samek** [comment]
bummer. 

I'll probably patch mesos-dns then to have _tcp0/1. entries - I'll rather use this discovery method  and have host networking then fiddling with weave (and multicast) as we are now.

**Comment by dobe** [comment]
since this only results in a warning, it seems to be ok to wait for the mesos guys to fix this

**Pull request merged**
