### PR TITLE
Adjust "crate-node" auxiliary program to use the bundled Java runtime

### PR DESCRIPTION
**Pull request by amotl**
Hi there,

@proddata discovered a flaw when trying to run the auxiliary `crate-node` program shipped within the distribution bundles. Thank you very much. After shipping CrateDB with the bundled Java runtime, this has not been adjusted appropriately.

## Observations

Those error messages reveal different conditions on Windows (no Java installed) and macOS (older Java runtime installed).

### Windows
```sh
PS C:\opt\crate> .\bin\crate-node.bat

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

### macOS
```sh
$ ./bin/crate-node
Error: LinkageError occurred while loading main class org.elasticsearch.cluster.coordination.NodeToolCli
	java.lang.UnsupportedClassVersionError: org/elasticsearch/cluster/coordination/NodeToolCli has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 58.0
```

## Mitigation
This patch adjusts the contents of the generated start scripts by Gradle's `CreateStartScripts` task type. It will prevent a) to accidentally use any system-wide Java installation and b) will adjust the program to use the bundled Java runtime.

## Outlook
We can also use this patch as a reference to bring an issue to Gradle in order to improve the vanilla start script templates [1]. I believe having an out-of-the-box option there to generate start scripts using a bundled Java runtime is nothing that is very much esoteric.

With kind regards,
Andreas.

P.S.: In order to debug such situations on Linux and macOS machines, I created a gist which walks you through the steps how to conveniently invoke CrateDB on Windows by using ready-made Docker Windows images through a Vagrant-managed VM. This makes approaching such flaws almost effortless compared to the expenditure needed to manually install such an environment.

[1] https://github.com/gradle/gradle/tree/v6.8.3/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins
[2] https://gist.github.com/amotl/69046c2c4a8e6744b1d6cde3f9523119

### CODE REVIEW

**Comment by amotl** [comment]
Hi again,

I also just created https://github.com/gradle/gradle/issues/16418 in order to bring this to the attention of the Gradle developers.

With kind regards,
Andreas.

**Comment by nkev** [comment]
- Page title: Quick Install on Windows
- Page URL: https://crate.io/docs/crate/tutorials/en/latest/install-run/windows.html
- Source: https://github.com/crate/crate-tutorials/blob/master/docs/install-run/windows.rst

I'm not sure if this is relevant to this issue but I followed the instructions in URL above to install `crate-4.4.2` on Windows 10 but no matter what I do I get the error `JAVA_HOME environment variable must be set` The `JAVA_HOME` variable **is** set:

```BASH
PS C:\WINDOWS\system32> cd "C:\Users\me\Downloads\crate-4.4.2"
PS C:\Users\me\Downloads\crate-4.4.2> ./bin/crate
JAVA_HOME environment variable must be set
PS C:\Users\me\Downloads\crate-4.4.2> $env:JAVA_HOME
C:\Program Files\Java\jdk-11.0.10
PS C:\Users\me\Downloads\crate-4.4.2> ./bin/crate.bat
JAVA_HOME environment variable must be set
PS C:\Users\me\Downloads\crate-4.4.2>
```
I tried restarting the computer and also tried `crate.bat` instead with the same result. What am I doing wrong?

**Comment by amotl** [comment]
Hi Nuri,

thank you very much for your report. Can I humbly ask you to create another issue with that observation? By doing so, we will be able to discuss it more appropriately. I believe it might be beyond this PR.

With kind regards,
Andreas.

**Comment by proddata** [comment]
Hi @nkev  :)

Did you download the Windows specific package?
https://cdn.crate.io/downloads/releases/cratedb/x64_windows/
https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-4.4.2.zip

May I ask you to move that conversation to https://community.crate.io/ ?

**Comment by nkev** [comment]
Hi guys, 

Sorry for the late reply, I'm in Sydney and just got into the office (yes we're back in the office here!).

@amotl I see you already created another issue, I will respond there.

@proddata  Yes I downloaded this one:

image

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
