### PR TITLE
Move CSV settings to copyCopyFromSettings.

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Other schemes can import from CSV file, we must include CSV settings to the common list

Follows https://github.com/crate/crate/commit/bb978c50516ad161986425b0f9c201460f856b21

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
Not (yet) a problem because we don't have such validation in plugins (neither S3 nor Azure which is progress).

This PR combined with https://github.com/crate/crate/commit/bb978c50516ad161986425b0f9c201460f856b21 might look like it's going against documented state but it's not.

From [docs](https://cratedb.com/docs/crate/reference/en/latest/sql/statements/copy-from.html#delimiter)

> The option is only supported when using the CSV format, otherwise, it will be ignored.

We document that we silently ignore related to each other settings but they are used under same scheme.

New change is meant to reject, for example, Azure settings when using S3.

**Comment by BaurzhanSakhariev** [comment]
unrelated test_graceful_stop_concurrent_queries

retest this please

**Comment by BaurzhanSakhariev** [comment]
Another option is don't do validation and keep silently ignoring unknown/irrelevant settings. Then I will close this PR and revert previous one.

I mainly added validation due to setings being passed as generic Map and had concern that OpenDAL might return some cryptic error when encountering unexpected settings).

**Review by jeeminso — APPROVED** [review]
Since this is more of a fix for https://github.com/crate/crate/commit/bb978c50516ad161986425b0f9c201460f856b21 we can merge this first then think about reverting afterwards.

**Pull request merged**
