### PR TITLE
Fix memory leak caused by antlr cache growing over time

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
https://github.com/prestodb/presto/commit/7eb85a22e35f782387d0cdcb78abe79eee4cd645

Addresses memory leak when executing queries against HTTP endpoint, caused by antlr cache. BTW, there are quite some issues on antlr memory leaks https://github.com/antlr/antlr4/search?q=leak&type=issues

Steps to reproduce:

~~cr8 run-spec specs/insert_single.py localhost:4200~~

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
As shown in screenshots, memory is still growing after the patch but slope is slightly gentler slope.

**Comment by mkleen** [comment]
we don't do backports from presto.

**Comment by BaurzhanSakhariev** [comment]
> You can address that as a normal commit without the presto reference.

I removed bp prefix and rephrase commit message. I think it's still fine to refer to the presto commit as it was anyway derived?

**Comment by BaurzhanSakhariev** [comment]
`cr8 run-spec specs/insert_single.py localhost:4200` is not a correct way to test antlr cache load:

I checked against local build with some outputs, we just parse same statement 
`"insert into id_int_value_str (id, value) values (?, ?)"` many times which even with a shared cache not going to produce new entries. 

Looking into using `generate_rnd_queries`

**Comment by BaurzhanSakhariev** [comment]
Not sure we need this patch for "insert many values into multi column table". 

Problem is that parser needs all values in a context:
https://github.com/crate/crate/blob/master/libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java#L1403 
and 
https://github.com/crate/crate/blob/master/libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java#L787.

If statement looks like insert  into table_with_100_cols values (val1, .... val100), (. ),   -- values repeated 10K times it's too much to parser to swallow.

See https://github.com/crate/crate/pull/13907/files#diff-1c9cb84809bd31c95a74eb1787c99d95e6b05c0f479dbb172d239bb09add3ad0L331-R331

**Comment by mkleen** [comment]
Thanks for the feedback. However, the patch looks still like a good candidate to have. So maybe keep it open for review.

**Comment by BaurzhanSakhariev** [comment]
> However, the patch looks still like a good candidate to have. So maybe keep it open for review.

Regarding caches: it's indeed can be a problem, but I think it can be simpler:
The author of the linked patch [says](https://github.com/trinodb/trino/pull/3186#issuecomment-601951933) it was inspired by [comment](https://github.com/antlr/antlr4/issues/499#issuecomment-38159752) from an antlr maintainer.

we can replace all this by smth like 
```
lexer.setInterpreter(new LexerATNSimulator(lexer, lexer.getATN(), lexer.getInterpreter().decisionToDFA, new PredictionContextCache()));
parser.setInterpreter(new ParserATNSimulator(parser, parser.getATN(), parser.getInterpreter().decisionToDFA, new PredictionContextCache()))
```

or maybe even don't create `PredictionContextCache()` if we basically refuse from caching and replace antlers static shred cache with our static shared no-op cache (return null on get, do nothing on put).

**Comment by mkleen** [comment]
> or maybe even don't create `PredictionContextCache()` if we basically refuse from caching and replace antlers static shred cache with our static shared no-op cache (return null on get, do nothing on put).

Antlr is probably caching a reason. So we need to check if this does not have any other performance implications.

**Comment by BaurzhanSakhariev** [comment]
> > or maybe even don't create `PredictionContextCache()` if we basically refuse from caching and replace antlers static shred cache with our static shared no-op cache (return null on get, do nothing on put).
> 
> Antlr is probably caching for a reason. So we need to check if disabling the cache does not have any other performance implications.

After reading a [comment](https://github.com/antlr/antlr4/issues/1944#issuecomment-314462179), I had an impression that cache is vital if we parse multiple files. In our case it's grammar + all different queries in a user's app (should not be too many, unless it doesn't have some autogenerated selects).

Agree, this needs to be checked thoroughly before disabling cache.

**Comment by BaurzhanSakhariev** [comment]
Closing it as I'm not sure investigating cache disabling effect is a priority.

To address parsing large statements we agreed to add a clarification to docs that one should not use too many `VALUES`

**Pull request closed without merging**
