### PR TITLE
Using Kahan summation algorithm for doubles and floats in SUM operation

### PR DESCRIPTION
**Pull request by Wiewiogr**
## Summary of the changes / Why this improves CrateDB
In this PR i have implemented Kahan summation algorithm for SUM aggregation for floats and doubles.
Issue : https://github.com/crate/crate/issues/10543.

I wasn't sure about how I should structure my code. SumAggregation class was already pretty big, so I have moved KahanSummationFor[Double/Float] to separate classes, is it ok?

Also I have created separate classes for Doubles and Floats because it allows us to use primitive double and float types, generic implementation would have been cleaner but we will have to use "big" Floats and Doubles and allocate that values which will generate GC pressure. 

I did not add any new test to SumAggregation class, because there are already tests checking double and float summations.

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mfussenegger** [comment]
ok to test

**Comment by mfussenegger** [comment]
> I wasn't sure about how I should structure my code. SumAggregation class was already pretty big, so I have moved KahanSummationFor[Double/Float] to separate classes, is it ok?

Yep that's okay.


> I did not add any new test to SumAggregation class, because there are already tests checking double and float summations.

Sounds good. But I think we should have one test that ensures that the kahan summation is wired up.

Maybe the tests in 

https://github.com/crate/crate/blob/c49ecea33f41c98f4c7fb92afcc911c9cb9dc276/server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java#L83-L95

Could be changed so that it would fail without using Kahan summation.


Overall looks very good. Nicely done :+1:

**Comment by mfussenegger** [comment]
The checkstyle task is failing:

```
:server:checkstyleMain

[ant:checkstyle] [ERROR] /var/lib/jenkins/workspace/CrateDB/crate_on_pr/server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java:207:41: 'lambda arguments' has incorrect indentation level 40, expected level should be 16. [Indentation]

[ant:checkstyle] [ERROR] /var/lib/jenkins/workspace/CrateDB/crate_on_pr/server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java:218:41: 'lambda arguments' has incorrect indentation level 40, expected level should be 16. [Indentation]
```

**Comment by Wiewiogr** [comment]
Thanks for your review.
New version with fixed style and tests in SumAggregationTest suite is pushed.

**Review by mfussenegger — APPROVED** [review]
nice work :+1:

We'll merge this in a bit

**Pull request merged**
