### PR TITLE
Docs: Add a prelude to the ssl configuration section

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Comment by mfussenegger** [comment]
@jodok maybe you've also some input here on how to further improve the docs? (See also:  https://crate.io/docs/reference/en/latest/administration/ssl.html )

**Comment by jodok** [comment]
error
i see an rendering error.

**Comment by jodok** [comment]
my only suggestion to the text would be to provide a bash script that does all the magic of cert creation... but that's probably a separate story.

**Comment by mfussenegger** [comment]
@jodok yep I fixed that within this PR: https://github.com/crate/crate/pull/5801/files#diff-f51b9c7e1b957fc9fa0cfc084e1438c7R130

**Pull request merged**
