### PR TITLE
Unify optimize calls between top-level select and sub-select

### PR DESCRIPTION
**Pull request by mfussenegger**
Side effect of the change is that this now enables fetch optimization
for sub-queries.

### CODE REVIEW

**Comment by mfussenegger** [comment]
Good call. Looks like this makes it worse in some cases:

## Three node cluster

```
Q: select * from articles where id in (select id from colors where coolness > 0) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |       88.784 ±   24.866 |     76.193 |     84.462 |     89.902 |    327.791 |
|   V2    |       92.580 ±   27.771 |     80.273 |     88.493 |     91.625 |    335.170 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   4.19%                           +   4.66%
There is a 84.93% probability that the observed difference is not random, and the best estimate of that difference is 4.19%
The test has no statistical significance

Q: select * from articles where id in (select id from colors where coolness > 0 limit 100) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        4.599 ±    2.740 |      3.106 |      4.121 |      4.438 |     29.793 |
|   V2    |        5.395 ±    1.312 |      4.142 |      5.122 |      5.517 |     14.346 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +  15.93%                           +  21.65%
There is a 99.98% probability that the observed difference is not random, and the best estimate of that difference is 15.93%
The test has statistical significance

Q: select * from articles where id in (select id from colors where coolness > 0 limit 10) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        3.274 ±    1.143 |      2.350 |      3.161 |      3.458 |     16.142 |
|   V2    |        2.901 ±    1.261 |      2.202 |      2.683 |      2.993 |     17.781 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  12.08%                           -  16.36%
There is a 99.79% probability that the observed difference is not random, and the best estimate of that difference is 12.08%
The test has statistical significance

Q: select * from articles where id not in (select id from colors where coolness > 0) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |      414.548 ±    9.325 |    401.679 |    412.644 |    417.640 |    462.819 |
|   V2    |      424.616 ±   11.068 |    408.753 |    423.037 |    427.560 |    478.425 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   2.40%                           +   2.49%
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 2.40%
The test has statistical significance
```


## Single node cluster


```
# Results (server side duration in ms)
V1: 5.8.0-e0a9b0b6782cc893871e9cdf1a19d49729e85a1f
V2: 5.8.0-f388324fba1b2ea85de6a3a52d3a17e9476189d5

Q: select * from articles where id in (select id from colors where coolness > 0) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |       85.310 ±   22.863 |     79.978 |     82.517 |     84.617 |    399.319 |
|   V2    |       89.104 ±   23.844 |     83.179 |     85.835 |     87.945 |    410.937 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   4.35%                           +   3.94%
There is a 89.49% probability that the observed difference is not random, and the best estimate of that difference is 4.35%
The test has no statistical significance

Q: select * from articles where id in (select id from colors where coolness > 0 limit 100) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        1.902 ±    1.807 |      1.224 |      1.567 |      1.959 |     22.871 |
|   V2    |        2.988 ±    0.906 |      2.306 |      2.761 |      3.176 |     13.415 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +  44.41%                           +  55.17%
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 44.41%
The test has statistical significance

Q: select * from articles where id in (select id from colors where coolness > 0 limit 10) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        1.062 ±    0.147 |      0.854 |      1.045 |      1.106 |      2.450 |
|   V2    |        1.185 ±    0.167 |      0.998 |      1.157 |      1.230 |      2.832 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +  10.93%                           +  10.19%
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 10.93%
The test has statistical significance

Q: select * from articles where id not in (select id from colors where coolness > 0) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |      429.877 ±    9.959 |    421.066 |    428.179 |    431.825 |    546.776 |
|   V2    |      416.736 ±   10.045 |    408.934 |    414.852 |    418.107 |    525.040 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -   3.10%                           -   3.16%
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 3.10%
The test has statistical significance
```



Relates a bit to:

- https://github.com/crate/crate/issues/11285 and we could also consider having a cost model for fetch/non-fetch (https://github.com/crate/crate/issues/14146)

I'll put this on hold for now. After https://github.com/crate/crate/issues/15548 where we may eliminate some of the differences we can decide on how to proceed here.

**Comment by romseygeek** [comment]
I've brought this up-to-date locally, and there are a few failing tests, mainly around `Eval` phases missing in plans:
```
[ERROR]   CorrelatedSubqueryITest.test_where_exists_with_correlated_subquery:225
expected:
  "Eval[x]
    └ Filter[EXISTS (SELECT x FROM (empty_row))]
      └ CorrelatedJoin[x, (SELECT x FROM (empty_row))]
        └ Rename[x] AS t
          └ TableFunction[generate_series | [generate_series] | true]
        └ SubPlan
          └ Eval[x]
            └ Limit[1;0]
              └ TableFunction[empty_row | [x] | true]
  "
 but was:
  "Eval[x]
    └ Filter[EXISTS (SELECT x FROM (empty_row))]
      └ CorrelatedJoin[x, (SELECT x FROM (empty_row))]
        └ Rename[x] AS t
          └ TableFunction[generate_series | [generate_series] | true]
        └ SubPlan
          └ Limit[1;0]
            └ TableFunction[empty_row | [x] | true]
```

Are these expected changes?

**Comment by romseygeek** [comment]
> Are these expected changes?

I think these are related to c7ea2e0005c1c8ad583373e47ebb93f156c8b9f5 and are expected, so I'll fix them.

**Comment by romseygeek** [comment]
It looks as though it doesn't make a measureable difference on the queries tested above:
```

Q: select * from articles where id in (select id from colors where coolness > 0) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |       33.604 ±   13.451 |     29.918 |     31.234 |     32.573 |    208.353 |
|   V2    |       33.326 ±   15.248 |     29.891 |     30.748 |     31.450 |    233.762 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -   0.83%                           -   1.57%
There is a 15.29% probability that the observed difference is not random, and the best estimate of that difference is 0.83%
The test has no statistical significance

Q: select * from articles where id in (select id from colors where coolness > 0 limit 100) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        1.710 ±    1.945 |      0.970 |      1.137 |      1.281 |     24.015 |
|   V2    |        1.488 ±    0.562 |      1.129 |      1.399 |      1.552 |      8.694 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  13.87%                           +  20.72%
There is a 87.77% probability that the observed difference is not random, and the best estimate of that difference is 13.87%
The test has no statistical significance

Q: select * from articles where id in (select id from colors where coolness > 0 limit 10) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        0.833 ±    0.094 |      0.707 |      0.813 |      0.852 |      1.351 |
|   V2    |        0.825 ±    0.093 |      0.706 |      0.811 |      0.866 |      1.727 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -   1.03%                           -   0.22%
There is a 63.48% probability that the observed difference is not random, and the best estimate of that difference is 1.03%
The test has no statistical significance

Q: select * from articles where id not in (select id from colors where coolness > 0) limit 10000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |      404.490 ±    9.796 |    400.342 |    401.866 |    402.570 |    466.668 |
|   V2    |      404.974 ±   20.045 |    400.631 |    402.198 |    402.876 |    659.557 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   0.12%                           +   0.08%
There is a 24.10% probability that the observed difference is not random, and the best estimate of that difference is 0.12%
The test has no statistical significance
```

**Comment by BaurzhanSakhariev** [comment]
>It looks as though it doesn't make a measureable difference on the queries tested above:

A query that got notably worse in the first benchmark is

`select * from articles where id in (select id from colors where coolness > 0 limit 100) limit 10000`

   It was +15.93% on multi-node, +  44.41%  on a single node.
   
Looks like results got better in the last benchmark?
-  13.87%

**Comment by romseygeek** [comment]
> Looks like results got better (- 13.87%) for this query in the last benchmark?

The mean improved, but the median got worse (+20.72%).  These runs are quite noisy, however, and the benchmark reports no statistical significance to the differences.  I think it's probably worth merging in any case as it improves the code?

**Comment by mfussenegger** [comment]
I'd say get it in. If nightly benchmarks show regressions we can still investigate or revert.

**Review by romseygeek — APPROVED** [review]

**Comment by romseygeek** [comment]
@Mergifyio squash title+body

**Comment by romseygeek** [comment]
retest this please

**Pull request merged**
