### PR TITLE
#14640 Support lowercase yyyy in to_char

### PR DESCRIPTION
**Pull request by rebdiaz**
Add support for lowercase 'yyyy' pattern to `to_char`
for timestamps and intervals which behaves exactly the same
as the uppercase `YYYY` pattern. This makes it compatible with
PostgreSQL which supports the lowercase `yyyy`.

Closes: #14640

### CODE REVIEW

**Comment by matriv** [comment]
ok to test

**Review by matriv — APPROVED** [review]
@rebdiaz Thanks a lot!

Added a commit to add doc changes and changes entry for the next release, and I'll take it from here to merge it.

**Review by BaurzhanSakhariev — APPROVED** [review]
Thanks!

**Comment by matriv** [comment]
Thx again for this contribution @rebdiaz !

I'd like to kindly ask you for any next contributions that you create a branch in your fork, and not use `master`, thx!

**Pull request merged**
