### PR TITLE
Print info about remaining ForkJoinPool threads

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
https://wacklig.pipifein.dev/github/crate/crate/case/io.crate.expression.operator.any.AnyEqOperatorTest/testArrayEqAnyNestedArrayDoesNotMatch
and 
https://wacklig.pipifein.dev/github/crate/crate/case/io.crate.expression.predicate.MatchPredicateTest/testGetStringDefaultMatchType

failed with active thread count on ForkJoinPool

```
expected: 0
 but was: 1
	at __randomizedtesting.SeedInfo.seed([E886A44AC68DB2F:76802B7792616C42]:0)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.crate.lucene.CrateLuceneTestCase.assertNoActiveCommonPoolThreads(CrateLuceneTestCase.java:207)
```

Adding a timeout to wait for those active threads to finish.

### CODE REVIEW

**Review by matriv — APPROVED** [review]
thank you! maybe also wait for @mfussenegger to check it as well.

**Review by mfussenegger — COMMENTED** [review]
This seems to point to an actual issue in that there are still threads running?

**Comment by BaurzhanSakhariev** [comment]
> This seems to point to an actual issue in that there are still threads running?

Yes. We migrated tests to use JDK `HttpClient` in https://github.com/crate/crate/commit/10fc003d4ad2986671b9b01f769388bb78e4a26c. My thinking here is that we can have http-client-dependant tests still running in parallel and not yet finished. 

If problem persists even after the reasonable timeout then it probably means we have an actual problem somewhere.

**Comment by mfussenegger** [comment]
> We migrated tests to use JDK HttpClient in https://github.com/crate/crate/commit/10fc003d4ad2986671b9b01f769388bb78e4a26c. My thinking here is that we can have http-client-dependant tests still running in parallel and not yet finished.

All the tests using the http client wait for the result. That they're still running shouldn't be the case, and if it is it is a mistake.

That we get these failures from query tests, and not any http integration tests is also suspicious. 
We could try do something like this instead:

```diff
diff --git a/server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java b/server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
index ae609e22ee7..435778a515b 100644
--- a/server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
+++ b/server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
@@ -42,10 +42,11 @@
 
 import java.io.Closeable;
 import java.io.IOException;
 import java.net.http.HttpClient;
 import java.nio.file.Path;
+import java.util.Map;
 import java.util.Random;
 import java.util.concurrent.ForkJoinPool;
 import java.util.concurrent.ForkJoinWorkerThread;
 
 import org.apache.lucene.analysis.Analyzer;
@@ -202,11 +203,26 @@ public void tearDown() throws Exception {
         luceneTestCase.tearDown();
     }
 
     @After
     public void assertNoActiveCommonPoolThreads() throws Exception {
-        assertThat(ForkJoinPool.commonPool().getActiveThreadCount()).isEqualTo(0);
+        ForkJoinPool commonPool = ForkJoinPool.commonPool();
+        StringBuilder sb = new StringBuilder();
+        if (commonPool.getActiveThreadCount() > 0) {
+            Map<Thread, StackTraceElement[]> allStackTraces = Thread.getAllStackTraces();
+            for (var entry : allStackTraces.entrySet()) {
+                Thread thread = entry.getKey();
+                if (thread instanceof ForkJoinWorkerThread) {
+                    sb.append(thread.getName());
+                    StackTraceElement[] stacktrace = entry.getValue();
+                    for (StackTraceElement stackTraceElement : stacktrace) {
+                        sb.append("\n    at").append(stackTraceElement);
+                    }
+                }
+            }
+        }
+        assertThat(commonPool.getActiveThreadCount()).as(sb.toString()).isEqualTo(0);
     }
 
     public void setIndexWriterMaxDocs(int limit) {
         luceneTestCase.setIndexWriterMaxDocs(limit);
     }
```

To get a better idea of what's actually running

**Comment by BaurzhanSakhariev** [comment]
>We could try do something like this instead:

Thanks, applied

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
