### PR TITLE
Release delayed messages on close channel

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

Ensurse that any buffered messages get immediately released if a channel is
closed.

For example if a client is disconnected this should ensure that the messages
are still getting released. I'm not entirely sure if this was a problem in practice, as the future would have triggered eventually anyway(?)

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by seut — APPROVED** [review]
👍 good spot

> I'm not entirely sure if this was a problem in practice, as the future would have triggered eventually anyway(?)

I also think that this may only be related to a combination of client disconnects and test suite tear downs (hitting the leak detection too early in that case?).

**Comment by mfussenegger** [comment]
Looks like this causes the ssl blackbox tests to get stuck. I'll have another look

**Comment by mfussenegger** [comment]
pushed a fixup

**Comment by mfussenegger** [comment]
Fix for the GHA windows failure is [here](https://github.com/crate/crate/pull/11045)

**Review by seut — APPROVED** [review]

**Pull request merged**
