### PR TITLE
Improve sys.allocations performance

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

See commits. Main improvement is in the second commit:

Evaluate decision lazy in sys.allocations

The decision computation is quite expensive. Making it lazy improves the
performance for cases where there are many shards but only a subset of
records are selected because of a filter on a cheaper column:

    Q: select * from sys.allocations where shard_id = 4
    C: 15
    | Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
    |   V1    |       96.166 ±   15.395 |     66.254 |     95.679 |    106.930 |    138.741 |
    |   V2    |        1.671 ±    3.188 |      0.826 |      1.398 |      1.659 |     72.324 |
    ├---------┴-------------------------┴------------┴------------┴------------┴------------┘
    |               - 193.17%                           - 194.24%
    There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 193.17%
    The test has statistical significance

See https://github.com/crate/crate-benchmarks/pull/216 for the benchmark case

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by seut — COMMENTED** [review]
Great! I think this is worth a changes entry.

**Review by kovrus — APPROVED** [review]
🐎

**Comment by mfussenegger** [comment]
> Great! I think this is worth of adding a changes entry.

Good point. I added one - could you check?

**Review by seut — APPROVED** [review]
👍

**Pull request merged**
