### PR TITLE
Mention support of GEO POINT in column store docs

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Porting it to 5.3 since it's a fix

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
Hi @matriv can you please take a look? 

Do you think we need to fix container types mention as well? 

We store doc values for arrays (deduplicated, depending on inner type and without nulls) but don't use it for aggregations, we even have dedicated `ArrayViaDocValuesUnsupported` exception. However, we utilize those doc values in some [specific cases](https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java#L204) of `array_length` where absence of duplicates and nulls doesn't affect the result.

**Comment by BaurzhanSakhariev** [comment]
Sorry, should be other way around, will swap GP with GS

**Review by matriv — APPROVED** [review]
Thx!

**Comment by BaurzhanSakhariev** [comment]
retest this please 

https://jenkins.crate.io/job/CrateDB/job/crate_on_pr/7875/testReport/junit/io.crate.integrationtests/LogicalReplicationITest/test_subscription_state_order/

**Comment by BaurzhanSakhariev** [comment]
another one LR failure

retest this please

**Pull request merged**
