### PR TITLE
Add last-reviewed metadata to some docs

### PR DESCRIPTION
**Pull request by mechanomi**
zaps some whitespace too

### CODE REVIEW

**Review by autophagy — COMMENTED** [review]
Would it be worth adding some information to https://github.com/crate/crate/blob/master/devs/docs/write_docs.rst about how this metadata is generated and what it means?

**Comment by autophagy** [comment]
@mechanomi Also, would you be able to ammend the commit with a more detailed description of why these are being added, etc? Just so that if anyone looks at the commit log they can see why.

**Review by seut — CHANGES_REQUESTED** [review]
Could you please elaborate why this is really needed, wouldn't it be enough to use git log (maybe with some filter on commit messages, e.g. prefix doc related commits)?
This feels a bit overdone to me and I worry that this will be outdated soon. This is another point people have to know about and keep in mind.
I'd really prefer to use git instead.

If this is really the way we want to go, a verbose commit message including the reasoning for doing so would be important as mika already suggested.

**Comment by mechanomi** [comment]
hey folks. thanks for the feedback. there's some detailed information on the tech writing wiki here:

https://github.com/crate/tech-writing-domain/wiki#quality-assurance

specifically: https://github.com/crate/tech-writing-domain/wiki/How-and-why-to-flag-documents-for-review

to summarize: this metadata is added by tech writers to specific docs that are at a high risk of becoming out-of-date. the metadata value reflects the last time a tech writer performed a "stale pages" review (https://github.com/crate/tech-writing-domain/wiki/How-to-perform-a-stale-pages-review)

we can't use Git metadata, because files get updated for all kinds of reasons. for example, to add content in an isolated fashion, make small edits, etc.

we specifically want to keep track of when an a whole-document review has taken place from (see https://github.com/crate/tech-writing-domain/wiki/How-to-perform-a-documentation-review for what this means)

this is the simplest possible thing that I am able to come up with that solves this problem. (e.g., tracking this information in a separate place introduces even more problems)

there is no requirement for engineers to do anything here. this is a piece of metadata that is intended to be added, updated, and managed by the tech writing team

as such, I don't think there's any necessary addition to https://github.com/crate/crate/blob/master/devs/docs/write_docs.rst -- though perhaps we could add a small footnote mentioning that there are additional QA processes in effect, managed by the tech writing team, which may result in pieces of metadata being added to the document

if you follow the instructions on https://github.com/crate/tech-writing-domain/wiki/How-to-perform-a-stale-pages-review you'll see that the CSV file generates two dates per document: last modified and last reviewed. both are important to keep track of from the perspective of QA

side note: a CSV isn't the easiest thing to use. we have plans to wrap a simple UI around this data to produce a docs QA dashboard (see https://github.com/crate/tech-writing-domain/issues/329)

@autophagy @seut with this additional information, can you let me know your thoughts and what you'd like me to do? thanks so much!

**Comment by mechanomi** [comment]
@autophagy @seut based on your feedback, I removed the original commit and instead preformed a light copyedit on these files. that has given me the opportunity to enter the "copyedit" keyword into the commit message, which marks these files as having been reviewed (satisfying the original purpose of this issue)

see the commit message for more info: https://github.com/crate/crate/pull/10609/commits/f6ff9da9832364ae2312883fc8271c3fb1f0b6c9

**Comment by mechanomi** [comment]
@seut can you re-review, please?

**Review by seut — APPROVED** [review]

**Pull request merged**
