### PR TITLE
Logical replication

### PR DESCRIPTION
**Pull request by seut**
This is a draft PR for tracking the state of the logical replication feature.
The logical replication makes it possible to synchronize tables between different clusters.
This feature will closely follow the [logical replication](https://www.postgresql.org/docs/current/logical-replication.html) specification by PostgreSQL while internally is heavily inspired by and partly derived of OpenSearch's [CCR plugin](https://github.com/opensearch-project/cross-cluster-replication).

## Minimal implementation:
- [x] Implement `CREATE/DROP PUBLICATION` (#11827)
- [x] Backport remote connection management from ElasticSearch's 7.10 branch (#11823)
- [x] Minimal logical replication support, triggered by `CREATE SUBSCRIPTION` (#11830) 
- [x] Support `DROP SUBSCRIPTION` (#11897, #12112)
- [x] Track and apply table mapping changes. (https://github.com/crate/crate/pull/11874)
- [x] Track and apply table setting changes. (https://github.com/crate/crate/pull/11933)     
- [ ] Support and validate all connection strategy settings (sniff, proxy) inside our analyzer and pass them to the strategy instances
- [x] User + privileges awareness of publication (#11842, #11872)
- [x] Expose subscriptions and their current state (pg_subscription, pg_subscription_rel) #11917
- [x] Documentation (#11821, #11835)
    - [x] Document settings (#12142)
    - [x] Softdelete requirements (#12138)
    - [x] Connection info (#12136)

## Handle things that break:
- [x] Validate if a table which a subscription would create already exists (Done by #11830)
       Possible options how to act on that:
     - [x] Raise error to the user on subscription creation for current tables.
     - ~[x] (Silently) Ignore existing tables while replicating which were not available on subscription creation and log a warning~
     - ~[ ] If the table is a replicated table, continue replication~
- [x] Retry changes tracker on failure (e.g. node disconnects, timeouts, etc.) (Done by #11830)
- [x] Block writes at subscribed/following tables on the subscriber (#11929)
- [x] ~Handle failures on initial repository restore (retry on timeouts, etc)~
      We've decided to expose possible failures via `pg_subscription` instead and let the user handle it (#11944)
- [ ] Extensive (resilient) tests
      - Ported a few tests 
      - Adding some test cases that also compare seqNo would be good 

## Handle new partitions/tables:
- [x] Track, replicate and follow new partitions or tables of a publication (#12206)
- [x] Track, replicate and follow dropped partitions or tables of a publication (#12251)
    - DELETE on partitioned table drops partitions --> need to treat it like regular data manipulation and replicate it 
    -  DROP tables on subscriber (users can delete the subscription to prevent it) 

## Handle edge cases:
- [x] Dropping tables that are part of a subscribed publication
    - [x] Re-create table afterwards
- [ ] Creating a publication for all tables; create subscription on the same cluster subscribing to its own publication; Create new table
- [ ] Dropping a publication for which there are active subscriptions

## Optional:
- [ ] Support publications and subscriptions on individual partitions 
- [ ] Support connection tunneling over the pgwire protocol
- [ ] Support `ALTER PUBLICATION` 
- [ ] Support `ALTER SUBSCRIPTION` (enable/disable replication, change connection info)
- [ ] Read changes from translog or lucene's in-memory segments (do we need to do that?)
       Currently only changes flushed to disk are recognized by the shard changes tracker.
       OpenSearch's CCR plugin has a logic to read operations from translog, see https://github.com/opensearch-project/cross-cluster-replication/blob/main/src/main/kotlin/org/opensearch/replication/action/changes/TransportGetChangesAction.kt#L103
- [ ]  Port resiliency snapshot tests

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]
Didn't really review as the individual PRs were already reviewed. Let's get this in - we can can polish things as follow up if necessary

**Comment by seut** [comment]
retest this please

**Comment by seut** [comment]
retest this please

internal jenkins CI issues (some runners couldn't be started)

**Comment by seut** [comment]
retest this please

**Comment by seut** [comment]
retest this please

**Pull request merged**
