### PR TITLE
Fix documentation link for backup-restore in some 4.3.2-4 releases

### PR DESCRIPTION
**Pull request by seut**
The release info for v4.3.2-4.3.4 contains an invalid link for
the backup-restore hint.
All other versions use the correct link so this seems to be a mistake.

Fixes sphinx linkcheck failures.

### CODE REVIEW

**Comment by amotl** [comment]
See also 9c93140.

**Comment by seut** [comment]
Ah I see, but I really wonder why we only link to the blog post in 3 older releases, all other link to the documentation. Why is this inconsistent?

**Comment by jeeminso** [comment]
> Ah I see, but I really wonder why we only link to the blog post in 3 older releases, all other link to the documentation. Why is this inconsistent?

I will fix the remaining links, before I just grepped for broken ones

**Comment by seut** [comment]
@jeeminso @amotl I don't think that the blog post really adds some value, it only addionionally mentions the CRASH CLI while hiding lot of important information like how to see the current status of a triggered snapshot. I'd really prefer linking to the documentation directly instead.

**Comment by amotl** [comment]
All right, then let's go with your 1d0e4e4 from #11866.

**Comment by seut** [comment]
@amotl 
> All right, then let's go with your 1d0e4e4. I will remove my 1494a0a from #11857.

As all agreed on that now, I've reopened this PR.

**Review by amotl — APPROVED** [review]

**Pull request merged**
