### PR TITLE
Move docs to top level dir

### PR DESCRIPTION
**Pull request by mechanomi**
## Summary of the changes / Why this improves CrateDB

we have just added an "edit on GitHub" button to our docs theme. for this to work as the feature is currently implemented, the docs for each project must be located under `docs/` at the top level of the repository

this PR swaps the `docs` symlink at the top level with the `blackbox/docs` directory. the end result is that the docs live at `docs/` and all of the tests and scripts under `blackbox/` continue to work

admittedly, it's a little awkward having to run `./blackbox/bin/sphinx dev` to build the docs that live under `./docs`, but this discrepancy will be gone once I get around to upgrading this repository to use the still-in-beta Crate Docs Utils (which will switch it to a Makefile based workflow so you can just cd into `./docs` and run `make dev`)

### CODE REVIEW

**Comment by seut** [comment]
@mechanomi we have `buildDocs` gradle task, isn't it usable?

**Comment by mechanomi** [comment]
> @mechanomi we have `buildDocs` gradle task, isn't it usable?

it is. the Crate Docs Utils is a standard set of tools and a standard way of working with the documentation across all of our projects

when I bring it over to crate/crate, I will take care to update the `buildDocs` task so that it hooks into the same system and continues to work (just like how at the moment it hooks into the underlying Sphinx build tools)

**Comment by mechanomi** [comment]
addendum: what I mean to say is that at the moment, you can build the docs with the `buildDocs` task if you wish. or you can use the lower-level `bin/sphinx` command directly

with the introduction of the Crate Docs Utils, nothing much will change. you will still be able to use the `buildDocs` task. or you will be able to use the lower level `make` system (see https://github.com/crate/croud/blob/master/DEVELOP.rst#working-on-the-documentation for some info about what it looks like in practice)

the benefit here is that `make dev` is baseline functionality for every `docs` directory for every one of our public projects

**Comment by mfussenegger** [comment]
> which will switch it to a Makefile based workflow so you can just cd into ./docs and run make dev

I'm not really happy with introducing another build tool into this repo. The build system we've in place is already complicated enough as it is. Adding another build tool to our build will make things even more complicated.

I'd rather we find a way to integrate the docs utils we want in a way that integrates better with the existing tooling we have within this project.

**Comment by mechanomi** [comment]
the Makefile is just a fancy wrapper around the `sphinx-build` executable. we already have a wrapper around that tool, written in shell, at `blackbox/bin/sphinx`. so all we've done is change the language of the wrapper from shell to make

in fact, the Makefile sets up the Python environment necessary to run that executable. at the moment, we have a script called `bootstrap.py` to do that. so, in fact, we're going from two shell scripts to one Makefile

I've already written a fairly featureful integration for versioned stule guide linting (RST syntax, Vale style guides, etc) in make. I don't want to have to repeat that work in another language just for crate/crate and then maintain two separate versions of it. that doesn't seem like a good trade-off to me when the only benefit is that we avoid the use of `make`

hooking Gradle into the standard docs build interface the Crate Docs Utils provides should be very simple. and it's just as many layers of build indirection (i.e., three) as we had before

before:

- Gradle ->
- our custom shell script ->
- `sphinx-build`

after:

- Gradle ->
- our custom Makefile->
- `sphinx-build`

**Comment by mechanomi** [comment]
also, I should note: we don't have to solve this problem right now. I am nowhere near close to bringing the Crate Docs Utils to crate/crate. I am introducing it one project at a time, and I plan do do crate/crate last, once the wrinkles are ironed out

for the purposes of this PR, the only thing to note is that the build infrastructure for Sphinx still lives under `blackbox/` -- which, even if the Crate Docs Utils do not land in crate/crate as set out above, still makes sense to me. everything works exactly as it did before

**Comment by seut** [comment]
retest this please

```
> Task :blackbox:gtest

test_graceful_stop_concurrent_queries (test_decommission.TestGracefulStopDuringQueryExecution) ... FAIL


======================================================================

FAIL: test_graceful_stop_concurrent_queries (test_decommission.TestGracefulStopDuringQueryExecution)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/var/lib/jenkins/workspace/CrateDB/crate_on_pr@2/blackbox/test_decommission.py", line 351, in test_graceful_stop_concurrent_queries

    self.assertEqual(errors, [])

AssertionError: Lists differ: [ProgrammingError('SQLActionException[ShardNotFoundException: no such shard]')] != []


First list contains 1 additional elements.

First extra element 0:

ProgrammingError('SQLActionException[ShardNotFoundException: no such shard]')


- [ProgrammingError('SQLActionException[ShardNotFoundException: no such shard]')]

+ []


----------------------------------------------------------------------

Ran 1 test in 40.430s


FAILED (failures=1)


> Task :blackbox:gtest FAILED
```

**Pull request merged**
