### PR TITLE
gha: Update vale-action

### PR DESCRIPTION
**Pull request by mfussenegger**
Started to fail on other PRs, likely due to runner image changes:

```
/node_modules/undici/lib/global.js:26
  return globalThis[globalDispatcher]
  ^

ReferenceError: globalThis is not defined
    at getGlobalDispatcher (/node_modules/undici/lib/global.js:26:3)
    at Object.<anonymous> (/node_modules/undici/lib/global.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:[10](https://github.com/crate/crate/actions/runs/6454164142/job/17519134396?pr=14819#step:4:11))
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:[12](https://github.com/crate/crate/actions/runs/6454164142/job/17519134396?pr=14819#step:4:13))
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:[17](https://github.com/crate/crate/actions/runs/6454164142/job/17519134396?pr=14819#step:4:18))
    at require (internal/modules/cjs/helpers.js:25:[18](https://github.com/crate/crate/actions/runs/6454164142/job/17519134396?pr=14819#step:4:19))
    at Object.<anonymous> (/node_modules/undici/index.js:18:54)
```

### CODE REVIEW

**Review by amotl — APPROVED** [review]
Thank!

**Comment by seut** [comment]
@mergifyio refresh

**Comment by seut** [comment]
@Mergifyio backport 5.4

**Comment by matriv** [comment]
@mergifyio backport 5.3

**Comment by matriv** [comment]
https://github.com/Mergifyio backport 5.2

**Pull request merged**
