### PR TITLE
Cpu used in os column of sys.nodes fixed

### PR DESCRIPTION
**Pull request by aslanbekirov**

### CODE REVIEW

**Comment by kovrus** [comment]
did you figure out why it happens, could it be that it is casting exception `(short)`

**Comment by mfussenegger** [comment]
Can we have a test for this?

**Comment by seut** [comment]
yes we know why this is happening, its an edge case bug I produced: if sigar is loaded and cpu.sys() is 0 it will never adds sys() and user() but will go to the 'sigar-not-loaded-all-values-are-default' branch

**Comment by seut** [comment]
as discussed, pls update/add tests

**Comment by seut** [comment]
lgtm

**Comment by seut** [comment]
forgot: changes entry missing

**Comment by mfussenegger** [comment]
lgtm

**Pull request merged**
