### PR TITLE
hardcode docutils==0.16

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
it started to pick up docUtils 0.18 and failing (Sphinx 3.3.1 is not compatible to it causing linkcheck failures), similar to [sphinx/issues/9841](https://github.com/sphinx-doc/sphinx/issues/9841)

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
I am seeing linkcheck failures from several of previous commits on 4.6, was wondering to fix it before releasing 4.6.5

**Comment by seut** [comment]
@jeeminso 
As we always build docs based on feature branches and not hotfix version (so `4.6`) we can also backport it after the release. a failed linkcheck rule should not block any builds.

**Review by seut — APPROVED** [review]

**Comment by amotl** [comment]
Hi.

Please even pin the version of docutils to 0.16. For a rationale, see https://github.com/crate/crate-tutorials/pull/59 and https://github.com/crate/crate-docs-theme/issues/252. TLDR; docutils 0.17 started using new semantic tags of HTML5, where our `crate-docs-theme` is not yet prepared for.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Do you have any clue why it would pick up 0.18 and not honor the explicit version pinning I introduced the other day on the upstream package?

> `docutils==0.16`
>
> -- https://github.com/crate/crate-docs-theme/blob/0.18.0/setup.py#L61

**Comment by jeeminso** [comment]
> @jeeminso As we always build docs based on feature branches and not hotfix version (so `4.6`) we can also backport it after the release. a failed linkcheck rule should not block any builds.

@seut, Thanks for explanation, I proceeded with the release but `create_tag.sh` script aborted with the same docs error. I still could adjust the script to ignore doc build step and create the [tag]( https://github.com/crate/crate/releases/tag/4.6.5 ) Would this be fine?

**Comment by jeeminso** [comment]
> Do we have any clue why it would pick up 0.18 and not honor the explicit version pinning I introduced the other day on the upstream package?
> 
> > `docutils==0.16`
> > -- https://github.com/crate/crate-docs-theme/blob/0.18.0/setup.py#L61

I am not too sure but initially I saw two errors that are the same. One for linkcheck action and the other for jenkins ci build which re-ran and passed. I am thinking somehow it was able to pick up the older version.

**Comment by jeeminso** [comment]
retest this please

**Pull request merged**
