### PR TITLE
Narrow range of bigint to account for null-sentinel

### PR DESCRIPTION
**Pull request by mfussenegger**
To be able to work with `long` primitive values using doc-values ORDER
BY operations use Long.MIN_VALUE and Long.MAX_VALUE as sentinel value in
place for `NULL` values.

If you inserted these values and selected them with a query using ORDER
BY you therefore got `NULL` as result instead of the actual values.

To address that, this restricts the supported range for these types.

### CODE REVIEW

**Comment by mfussenegger** [comment]
@seut could you take a look at the approach? If it's okay I'll extend it to cover the other types (the diff covers only long so far)

I'm also not sure if this should be backported, or if we should rather have this as behavior change in 5.9 or 5.10

**Comment by seut** [comment]
@mfussenegger Looks good to me, I also cannot think of a better simple solution. Using the lower/upper limit seems more artificial than a common use-case, so I don't think we must keep supporting it. As this is a breaking change, I wouldn't backport it.

**Comment by mfussenegger** [comment]
Looks like only long range needs to be restricted because we always use `long` null sentinel:

https://github.com/crate/crate/blob/97df37bfca0ee48d42d7aaa58213c41d29ae7e27/server/src/main/java/io/crate/execution/engine/sort/LuceneSort.java#L213-L214

```
cr> create table tbl (b byte, s smallint, i int, l long);
CREATE OK, 1 row affected (0.539 sec)

cr> insert into tbl (b, s, i, l) values (127, 32767, 2147483647, 9223372036854775807);
SQLParseException[Value 9223372036854775807 exceeds allowed range for column of type bigint]

cr> insert into tbl (b, s, i, l) values (127, 32767, 2147483647, 9223372036854775806);
INSERT OK, 1 row affected (0.025 sec)
cr> select b from tbl order by b;
+-----+
|   b |
+-----+
| 127 |
+-----+
SELECT 1 row in set (0.044 sec)
cr> select s from tbl order by s;
+-------+
|     s |
+-------+
| 32767 |
+-------+
SELECT 1 row in set (0.003 sec)
cr> select i from tbl order by i;
+------------+
|          i |
+------------+
| 2147483647 |
+------------+
SELECT 1 row in set (0.003 sec)
cr> select l from tbl order by l;
+---------------------+
|                   l |
+---------------------+
| 9223372036854775806 |
+---------------------+
SELECT 1 row in set (0.003 sec)
```

**Review by seut — APPROVED** [review]
👍

**Pull request merged**
