### PR TITLE
Fix subscript handling on top of other relations

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

In a query like

    SELECT obj['x'] FROM (SELECT obj ...) AS t GROUP BY obj['x']

a invalid logical plan was created. It looked as follows:

    RootBoundary[address['postcode']]
    GroupBy[address['postcode'] | ]
    Boundary[_fetchid]
    Boundary[_fetchid]
    FetchOrEval[_fetchid]
    Collect[doc.users | [_fetchid, address['postcode']] | All]

Currently the `Collect` operator is trying to detect columns that are
not intermediately used. If it finds any, it substitutes them with a
`_fetchId`. This `_fetchId` is later picked up by the `FetchOrEval`
operator and resolved to the actual columns that have been selected.

In the scenario above, the parent was using `obj['x']` and the child had
`obj`, but several components weren't taking the relationship between
those into consideration.

So the `Collect` operator assumed that `obj` is unused, but it got
`obj['x']` as used column, which it couldn't interpret because the
`RelationBoundary` operator couldn't handle the mapping. There was no
`<PARENT_REL>.obj['x'] -> <CHILD_REL>.obj['x']` entry.

This raises the question why we have a special notation for lookups into
objects in the first place. We could also always build functions. One
reason is that we've index structures for the nested columns for an
object which we want to utilize.

A `lookup obj -> extract key 'x'` execution would fully load `obj` and
then parse it to extract the key. That can be an expensive operation if
`obj` is large. Especially compared to the alternative execution: Using
a column oriented data structure that we have specifically for
`obj['x']`.

Note that this fix doesn't yet utilize this. Instead we've:

    RootBoundary[address['postcode']]
    GroupBy[address['postcode'] | ]
    Boundary[address]
    Boundary[address]
    Collect[doc.users | [address] | All]

We could follow up with optimizer rules to optimize this scenario.

An alternative approach to fix this was in https://github.com/crate/crate/pull/9519

Which changed the `obj['x']` lookup on the sub-relation to change the
sub-relation itself.

    SELECT obj['x'] FROM (SELECT obj ...) AS t GROUP BY obj['x']

    would become

    SELECT obj['x'] FROM (SELECT obj, obj['x'] ...) AS t GROUP BY obj['x']

This approach looks simpler, but also seems to break semantics: It
introduces the notation that a child relation is modifying its outputs
due to the actions of a parent relation.

## Checklist

 - [ ] User relevant changes are recorded in ``CHANGES.txt``
 - [ ] Touched code is covered by tests
 - [ ] Documentation has been updated if necessary
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mfussenegger** [comment]
I'm still not sure whether we should go with https://github.com/crate/crate/pull/9519 instead or not. Which is why I've tried to elaborate a bit on the issue in the description. 

@seut @kovrus would be great to get your inputs here.

**Comment by seut** [comment]
@mfussenegger This approach looks quite simple and okaish, although without an optimizer to add the subscript to the `Collect` phase, a possible subscript inside the `ORDER BY` clause would result in a `FILTER` instead of Lucene-based sorting, which would result in a huge performance and memory impact.
Imho we should merge this only with the related optimizer rule in-place.

**Comment by mfussenegger** [comment]
@seut The ORDER BY case didn't even work. I pushed a second commit to fix it.

I'm not sure if the optimizer rule is in scope of a fix.

We'll need some kind of column prune optimization for it to work. And the current relation boundary + fetch optimization logic might interfere with it. Afaik https://github.com/crate/crate/pull/9519 would have a similar problem. If I understand it right, it would select the object column in addition to the subscript. Given that our evaluation is not lazy enough, we'd still pay the price for loading the full object.


I can follow up on it, and then depending on the scope we can still decide whether to backport it or not, but I'd keep it separate from this.

**Comment by seut** [comment]
Relates #9477.

**Pull request merged**
