### PR TITLE
Update JDBC to 42.3.5

### PR DESCRIPTION
**Pull request by mfussenegger**

### CODE REVIEW

**Review by BaurzhanSakhariev — APPROVED** [review]

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
retest this please

**Comment by BaurzhanSakhariev** [comment]
@seut, I saw `io.crate.integrationtests.disruption.discovery.DiskDisruptionIT.testGlobalCheckpointIsSafe` [failure](https://jenkins.crate.io/job/CrateDB/job/crate_on_pr/1460/testReport/junit/io.crate.integrationtests.disruption.discovery/DiskDisruptionIT/testGlobalCheckpointIsSafe/ ) 3 times on this PR, not sure how it's related to JDBC update though but a bit worrying to merge it

**Comment by seut** [comment]
@BaurzhanSakhariev yes I think we should look closer into this and such postpone after the 4.8 release

**Comment by mfussenegger** [comment]
> I saw io.crate.integrationtests.disruption.discovery.DiskDisruptionIT.testGlobalCheckpointIsSafe [failure](https://jenkins.crate.io/job/CrateDB/job/crate_on_pr/1460/testReport/junit/io.crate.integrationtests.disruption.discovery/DiskDisruptionIT/testGlobalCheckpointIsSafe/) 3 times on this PR, not sure how it's related to JDBC update though but a bit worrying to merge it

Something changed in the jdbc client regarding setting the default schema. The `DiskDisruptionIT` failed because all inserts failed due to unknown table errors. Fixed it now.

**Pull request merged**
