### PR TITLE
Replace crate.io with cratedb.com in README

### PR DESCRIPTION
**Pull request by michaelkremmel**
Replace crate.io with cratedb.com in README

- Update `crate.io` links to `cratedb.com` to reflect our domain change
- Fix some typos.

### CODE REVIEW

**Review by seut — APPROVED** [review]

**Comment by mfussenegger** [comment]
Please try to use more descriptive commit messages. E.g. "Replace crate.io with cratedb.com in README" still fits the 60 char commit message title.

**Comment by michaelkremmel** [comment]
Thank you for the feedback @mfussenegger, I've changed it now and I'll also try my best to be more descriptive going forward.

**Comment by michaelkremmel** [comment]
Thank you @matriv for the feedback, no need to apologize from your side if I'm doing something wrong. Please bear with me as I'm still learning how to do it correctly. It is literally my first pull request in this project. I hope it is better now.

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
> Thank you @matriv for the feedback, no need to apologize from your side if I'm doing something wrong. Please bear with me as I'm still learning how to do it correctly. It is literally my first pull request in this project. I hope it is better now.

No worries, I've adjusted the commit message myself, not sure if you can do it from github UI.
Otherwise you need to do it locally with `git rebase -i origin/master` and choose to `reword` the commit or with `git commit --amend` and then force push (`git push -f`).

**Comment by michaelkremmel** [comment]
Thank you, I've seen that you have changed it. Indeed I've tried to change it from the UI before. Thank you for the information on how to do it properly. But I hope next time I can come up with a proper commit message right from the start.

**Pull request merged**
