### PR TITLE
Remove caching in table parameters

### PR DESCRIPTION
**Pull request by mkleen**
This removes the caching of settings and mappings in table parameters.
If the settings/mappings methods are called and the builders are afterwards
mutated, then settings/mappings will be cached and not reflecting the latest state.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]

**Comment by seut** [comment]
@mkleen Looks like a fix, should it be backported?

**Comment by mkleen** [comment]
I ran into this while working on another task. So you would suggest to backport that ?

**Comment by mkleen** [comment]
This does not fix an actual user issue, but it is definitely fixing a wrong behavior in the code base.

**Comment by mkleen** [comment]
These methods are used heavily, but it looks never twice. However, i think it's a good to backport this. Should this go with a change entry ?

**Comment by seut** [comment]
What change entry would you then suggest if it never caused an issue?

**Comment by mkleen** [comment]
Good point, lets skip it.

**Comment by mkleen** [comment]
Both 4.7 and 4.8 ?

**Pull request merged**
