### PR TITLE
Generate new identifiers on snapshot of swapped table

### PR DESCRIPTION
**Pull request by mfussenegger**
Follow up to https://github.com/crate/crate/commit/24d7e94b055dc41d90ba9b01a87dc3274d32ef7a (and no changes, because 5.4.4 wasn't released yet)
The fix resulted in snapshots taken before swapping a table to become
unusable.

The reason was that the `index_metadata_identifiers` which are global
per repository-data only pointed to the _new_ metaUUID:

For example, on snapshot 1:

    metaUUID=M1, index=t02, indexId=I1, indexUUID=U1
    metaUUID=M2, index=t01, indexId=I2, indexUUID=U2

    index_metadata_identifiers: {
      U1-_na_-2-1: M1,
      U2-_na_-2-1: M2
    }

On snapshot 2, after swapping t01 and t02:

    Discard metaUUID=M2, newMetaUUID=M3, index=t02, indexId=I1, indexUUID=U2
    Discard metaUUID=M1, newMetaUUID=M4, index=t01, indexId=I2, indexUUID=U1

    index_metadata_identifiers: {
      U1-_na_-2-1: M4,
      U2-_na_-2-1: M3
    }

U1 (now I2) is pointing to M4, which contained M1 (I1) before the swap.
But on the filesystem in the repository was:

    /indices
      /I2
        /meta-M4.dat
        /meta-M2.dat
        /3
        /1
        /2
        /0
      /I1
        /meta-M3.dat
        /meta-M1.dat
        /0
        /3
        /1
        /2

On a restore of the first snapshot (U1, I1) it found `M4` in the
`index_metadata_identifiers`, and tried to look for `/I1/meta-m4.dat` on
the filesystem.

The solution is to generate a new `identifiers` key, so that we have the
following data after the second snapshot:

      index_metadata_identifiers: {
        "U2-U1-2-1": "M3",
        "U2-_na_-2-1": "M2",
        "U1-_na_-2-1": "M1",
        "U1-U2-2-1": "M4"
      }

And the snapshots themselves reference the correct identifier:

    {
      "name": "s2",
      "uuid": "xIhl-ubiTMWxCPRQbXjJng",
      "state": 1,
      "index_metadata_lookup": {
        "I1": "U2-U1-2-1",
        "I2": "U1-U2-2-1"
      },
      "version": "5.5.0"
    },
    {
      "name": "s1",
      "uuid": "TpqnN1x-SoSGO8IE_y8n5Q",
      "state": 1,
      "index_metadata_lookup": {
        "I1": "U1-_na_-2-1",
        "I2": "U2-_na_-2-1"
      },
      "version": "5.5.0"
    }

### CODE REVIEW

**Comment by mfussenegger** [comment]
Looks like there is still an issue if swapping the tables back and forth multiple times. I'll have another look

**Comment by mfussenegger** [comment]
@seut added a fixup that changes the approach: Include the indexName in the identifiers.

That means we should have:


```
First snapshot:
    metaUUID=M1, index=t02, indexId=I1, indexUUID=U1
    metaUUID=M2, index=t01, indexId=I2, indexUUID=U2
    index_metadata_identifiers: {
      t02-U1-_na_-2-1: M1,
      t01-U2-_na_-2-1: M2
    }

Second snapshot after swap:
    index_metadata_identifiers: {
      t02-U1-_na_-2-1: M1,
      t02-U2-_na_-2-1: M3,
      t01-U2-_na_-2-1: M2
      t01-U1-_na_-2-1: M4
    }
```

It seems to fix the flakyness I saw with the first variant of the fix when swapping tables multiple times.

**Review by seut — APPROVED** [review]
👍

**Comment by matriv** [comment]
@mergifyio backport 5.2

**Comment by matriv** [comment]
https://github.com/Mergifyio backport 5.3

**Pull request merged**
