### PR TITLE
Use {} for if statement (even if block is one line)

### PR DESCRIPTION
**Pull request by andreidan**
## Checklist

 - [ ] User relevant changes are recorded in ``CHANGES.txt``
 - [ ] Touched code is covered by tests
 - [ ] Documentation has been updated if necessary
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mfussenegger** [comment]
Can we enable a checkstyle rule for this?

**Comment by andreidan** [comment]
> Can we enable a checkstyle rule for this?

We can, but I'm not sure if we should as most of the idea generated `equals` methods will fail to pass the rule. Which might be something we can live with, but I'm not entirely sure if we should do it.

**Comment by seut** [comment]
I think we should decide to not allow that by a checkrule before we change it for some parts of the code by dedicated commits. Otherwise it would be only partly implement which I don't see a point in doing. Personally I'm even fine having one-liner without it.

**Comment by andreidan** [comment]
> I think we should decide to not allow that by a checkrule before we change it for some parts of the code by dedicated commits. Otherwise it would be only partly implement which I don't see a point in doing. Personally I'm even fine having one-liner without it.

I think it can be a source of bugs and I don't see how fixing individual instances at a time can hurt (as fixing every occurrence implies deeper analysis due to generated code). Given the "severity and scale" of this change I'm also fine with dropping it

**Comment by mfussenegger** [comment]
I think we should either enforce it or not bother about it. Otherwise we end up having style discussions on PRs which I think we should avoid.

 If the intellij generated code is a problem we could probably check-in some adapted templates? We already have codeStyle stuff in the `idea` folder anyway.

**Pull request closed without merging**
