### PR TITLE
Backport retry on failed replication due to transient errors

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

See commits

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by seut — APPROVED** [review]
Any reason not to backport the `GlobalCheckpointListenersIT` https://github.com/elastic/elasticsearch/commit/5e96d3e59aeff620257ceea460b8d46741b7f46d#diff-7fddb047e1a7dfdb2a61b1accb00b1ed790c8af9647147aa0552a4503f209392R44 as well?

**Comment by mfussenegger** [comment]
> Any reason not to backport the `GlobalCheckpointListenersIT` [elastic/elasticsearch@5e96d3e#diff-7fddb047e1a7dfdb2a61b1accb00b1ed790c8af9647147aa0552a4503f209392R44](https://github.com/elastic/elasticsearch/commit/5e96d3e59aeff620257ceea460b8d46741b7f46d#diff-7fddb047e1a7dfdb2a61b1accb00b1ed790c8af9647147aa0552a4503f209392R44) as well?

I thought they were just moved from IndexShardIT - which we didn't have before either. It's also not clear to me what those tests verify in addition to the new unit tests - but I can add them.

**Comment by seut** [comment]
> I thought they were just moved from IndexShardIT - which we didn't have before either. It's also not clear to me what those tests verify in addition to the new unit tests - but I can add them.

I didn't look into these tests in details, I was just curious. Fine for me to leave them out if they do not create any new coverage/value.

**Comment by mfussenegger** [comment]
retest this please

Flaky MetadataTrackerITest

**Pull request merged**
