### PR TITLE
Bump Postgres Wire Protocol version to 11 so client tools stop complaining

### PR DESCRIPTION
**Pull request by robd003**
## Summary of the changes / Why this improves CrateDB
Postgres 10 has been deprecated ( https://www.postgresql.org/support/versioning/ )
Closes ticket https://github.com/crate/crate/issues/13398

## Checklist

 - [X] Added an entry in `CHANGES.txt` for user facing changes
 - [X] Updated documentation & `sql_features` table for user facing changes
 - [X] Touched code is covered by tests
 - [X] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [X] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by seut** [comment]
ok to test

**Review by seut — APPROVED** [review]
@robd003 Thank you a lot for jumping on this.

**Comment by robd003** [comment]
Always happy to help @seut

Any chance we could get https://github.com/crate/crate/pull/12624 merged in before 5.2 is released?

**Comment by robd003** [comment]
@seut looks like all tests passed, can this get merged in?

**Comment by BaurzhanSakhariev** [comment]
>  can this get merged in?

sure, sorry for the delay

**Comment by robd003** [comment]
Thanks @BaurzhanSakhariev ! Happy new years to the entire Crate team

**Pull request merged**
