### PR TITLE
Documentation: Markup and typo fixes, and layout improvements

### PR DESCRIPTION
**Pull request by amotl**
## About

A few copy-editing improvements to the documentation. Spotted while proof-reading and inspecting the outcome of GH-14487.

### CODE REVIEW

**Review by hlcianfagna — COMMENTED** [review]
Thanks @amotl , the changes look good to me, but please note the wording on `docs/concepts/clustering.rst` changed in 5.4 so this may conflict during the backport to 5.3

**Review by matriv — APPROVED** [review]
Thx @amotl. I'd say that if backporting to 5.3 is not easy, to skip it, since the content has been updated for master and 5.4, as @hlcianfagna has pointed out.

**Comment by amotl** [comment]
Thanks for your warnings. I've pulled the fixes to the "Optimistic Concurrency Control" page into GH-14492 instead.

**Comment by hlcianfagna** [comment]
> Thanks for your warnings. I've pulled the fixes to the "Optimistic Concurrency Control" page into [GH-14492](https://github.com/crate/crate/pull/14492) instead.

What about the clustering page?

**Comment by amotl** [comment]
> What about the clustering page?

Oh. I mixed it up, but the mistake has been corrected now. GH-14492 just pulls the changes to the **clustering page** from this patch.

**Review by hlcianfagna — APPROVED** [review]
Thank you @amotl

**Pull request merged**
