### PR TITLE
Add 4.3.2 to fromId to fix IndexShardTests.testMinimumCompatVersion

### PR DESCRIPTION
**Pull request by mfussenegger**
## Summary of the changes / Why this improves CrateDB

Missed this when adding the 4.3.2 release
We should follow up on this and handle unknown patch versions in a
better way like it is done here

https://github.com/elastic/elasticsearch/commit/0df08dd4587c8f9774dad348f7795c677d24fb4b#diff-dbb9c323ecfad4a779336fe48a6dae8c1c30547e8e166e1e695ce0422ab90c93R200

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by amotl — APPROVED** [review]
Thanks. 👍 

P.S.: What about all those Codecov warnings? I didn't spot them before when looking into PR diffs here and just wanted to note they are pretty noisy. I know them from other projects and this is probably their very intention to either make us improve test coverage or to add annotations for ignoring them to specific files or spots within the code base. Just curious why they only recently popped up here...?

**Comment by amotl** [comment]
Q: Does this actually justify putting out a 4.3.3 hotfix release including this update?

**Comment by mfussenegger** [comment]
> Does this actually justify putting out a 4.3.3 hotfix release including this update?

No there is nothing broken with 4.3.2. In the 4.3 branch the handling is correct: https://github.com/crate/crate/commit/d8600e555401f29d62b9beeb580dca9e61ac3ca6

It was only missing in the master branch.


> Just curious why they only recently popped up here...?

No idea why it is sometimes popping up and sometimes not.

**Comment by amotl** [comment]
Ok. Thanks for the clarification on all topics.

**Pull request merged**
