### PR TITLE
Add storage class setting to S3 repository 

### PR DESCRIPTION
**Pull request by proddata**
## Summary of the changes / Why this improves CrateDB

Added the ability to set a `storage_class`  for S3 repositories.
Since the implementation was already part of the forked S3 plugin, only the ability to set it was added.

S3 Plugin Tests covering storage class setting:
- https://github.com/crate/crate/blob/2c09fef429a2de2f8531526f1db4a8c0e3895937/plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/
- https://github.com/crate/crate/blob/2c09fef429a2de2f8531526f1db4a8c0e3895937/plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobStoreTests.java#L82C15-L108

closes https://github.com/crate/crate/issues/14298

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by proddata** [comment]
```sql
CREATE TABLE my_table AS SELECT i FROM generate_series(1,100,1);
CREATE REPOSITORY mys3repo type s3 with (storage_class='standard_ia', access_key='xxx', secret_key='xxx', bucket='xxx' );
CREATE SNAPSHOT mys3repo.mysnap ALL;
```

image

**Review by seut — APPROVED** [review]
👍 Thanks!

We having a feature freeze on the master already. But given that this is not very inverse but just exposes an existing feature, this could be merged despite of this. @mfussenegger @matriv wdyt?

**Comment by matriv** [comment]
I agree to merge it, thx @proddata!

One question: Are invalid values for the settings handled by S3 API?

**Comment by proddata** [comment]
> I agree to merge it, thx @proddata!
> 
> One question: Are invalid values for the settings handled by S3 API?

They are handled and tested by the S3 plugin

**Review by mfussenegger — APPROVED** [review]

**Comment by proddata** [comment]
unrelated failure, retest this please

**Pull request merged**
