### PR TITLE
integrate enterprise config docs into rest of config docs

### PR DESCRIPTION
**Pull request by nslater**
we don't separate off enterprise feature documentation. instead, it lives in the main docs, integrated with core feature documentation

this pr makes a change to the feature configuration documentation so that it mirrors this

thanks to @matriv for confirming all of these settings are node specific

### CODE REVIEW

**Comment by matriv** [comment]
@nslater Please check sphinx errors: https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fcrate_on_pr/detail/crate_on_pr/916/pipeline#step-51-log-363

**Comment by nslater** [comment]
retest this please

**Comment by nslater** [comment]
retest this please

**Comment by nslater** [comment]
please retest this

**Comment by nslater** [comment]
retest this please

**Pull request merged**
