### PR TITLE
Update intellij to jdk 22

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

Follow-up https://github.com/crate/crate/commit/b0b0b95f9b8c24bb4814f1e3db0187767c462218

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by matriv — APPROVED** [review]

**Comment by mfussenegger** [comment]
Is there a way to get intellij to automatically pick this up from the pom.xml?

**Comment by mkleen** [comment]
retest this please

**Comment by matriv** [comment]
> Is there a way to get intellij to automatically pick this up from the pom.xml? (Not intending to block this PR, just curious if we can avoid this for future updates)

Looked into it shortly, but couldn't find a way.

**Comment by mkleen** [comment]
> > Is there a way to get intellij to automatically pick this up from the pom.xml? (Not intending to block this PR, just curious if we can avoid this for future updates)
> 
> Looked into it shortly, but couldn't find a way.

I think this would require generating the idea project from the pom. We went in the other direction explicitly adding a idea project to the repo already.

**Pull request merged**
