### PR TITLE
fix version upgrade failure from 4.7 to nightly, due to blob index mapping

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
found by [crate-qa jenkins failure](https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/12/pipeline/), partial log attached below.

The issue is that the blob indices have no `mappingMetadata` (null) but missing a null check while upgrading `indexMetadata`.
Handle it similar to https://github.com/crate/crate/blob/34b25f0fca0be54d9a4be7845c5f1075349d28a9/server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java#L168-L174

---

```
(test_upgrade.StorageCompatibilityTest) ... [2022-02-08T20:39:08,251][WARN ][o.e.d.c.s.Settings       ] [aB91Af1abdAb-1] [node.max_local_storage_nodes] setting was deprecated in CrateDB and will be removed in a future release! See the breaking changes documentation for the next major version.

[2022-02-08T20:39:08,288][INFO ][o.e.e.NodeEnvironment    ] [aB91Af1abdAb-1] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [136.7gb], net total_space [149.9gb], types [ext4]

[2022-02-08T20:39:08,288][INFO ][o.e.e.NodeEnvironment    ] [aB91Af1abdAb-1] heap size [512mb], compressed ordinary object pointers [true]

[2022-02-08T20:39:08,482][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] node name [aB91Af1abdAb-1], node ID [ZMXh2XDJSlaE5_uT8djrOA], cluster name [aB91Af1abdAb]

[2022-02-08T20:39:08,521][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] version[4.8.0-SNAPSHOT], pid[25938], build[ee0cc45/2022-02-08T00:05:55Z], OS[Linux/5.4.0-96-generic/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.2/17.0.2+8]

[2022-02-08T20:39:08,522][WARN ][o.e.n.Node               ] [aB91Af1abdAb-1] version [4.8.0-SNAPSHOT] is a pre-release version of CrateDB and is not suitable for production

[2022-02-08T20:39:09,470][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] no modules loaded

[2022-02-08T20:39:09,472][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [cr8-copy-s3]

[2022-02-08T20:39:09,472][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [crate-azure-discovery]

[2022-02-08T20:39:09,472][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [crate-functions]

[2022-02-08T20:39:09,472][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [crate-jmx-monitoring]

[2022-02-08T20:39:09,472][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [crate-lang-js]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [es-analysis-common]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [es-analysis-phonetic]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [es-repository-azure]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [io.crate.plugin.SrvPlugin]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [io.crate.udc.plugin.UDCPlugin]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin]

[2022-02-08T20:39:09,473][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin]

[2022-02-08T20:39:09,474][INFO ][o.e.p.PluginsService     ] [aB91Af1abdAb-1] loaded plugin [org.elasticsearch.transport.Netty4Plugin]

[2022-02-08T20:39:10,481][WARN ][o.e.d.c.s.Settings       ] [aB91Af1abdAb-1] [gateway.expected_nodes] setting was deprecated in CrateDB and will be removed in a future release! See the breaking changes documentation for the next major version.

[2022-02-08T20:39:10,481][WARN ][o.e.d.c.s.Settings       ] [aB91Af1abdAb-1] [gateway.recover_after_nodes] setting was deprecated in CrateDB and will be removed in a future release! See the breaking changes documentation for the next major version.

[2022-02-08T20:39:10,788][INFO ][o.e.d.DiscoveryModule    ] [aB91Af1abdAb-1] using discovery type [zen] and seed hosts providers [settings]

[2022-02-08T20:39:12,226][INFO ][psql                     ] [aB91Af1abdAb-1] PSQL SSL support is disabled.

[2022-02-08T20:39:12,481][INFO ][i.c.n.c.PipelineRegistry ] [aB91Af1abdAb-1] HTTP SSL support is disabled.

[2022-02-08T20:39:12,568][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] initialized

[2022-02-08T20:39:12,576][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] starting ...

[2022-02-08T20:39:12,807][INFO ][psql                     ] [aB91Af1abdAb-1] publish_address {127.0.0.1:5432}, bound_addresses {127.0.0.1:5432}

[2022-02-08T20:39:12,827][INFO ][o.e.h.n.Netty4HttpServerTransport] [aB91Af1abdAb-1] publish_address {127.0.0.1:4200}, bound_addresses {127.0.0.1:4200}

[2022-02-08T20:39:12,856][INFO ][o.e.t.TransportService   ] [aB91Af1abdAb-1] publish_address {127.0.0.1:4300}, bound_addresses {127.0.0.1:4300}

[2022-02-08T20:39:13,039][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [aB91Af1abdAb-1] uncaught exception in thread [main]

org.elasticsearch.bootstrap.StartupException: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.metadata.MappingMetadata.getSourceAsMap()" because "mappingMetadata" is null

	at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:30) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	at io.crate.bootstrap.CrateDB.init(CrateDB.java:162) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[crate-server.jar:?]

	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[crate-cli.jar:?]

	at org.elasticsearch.cli.Command.main(Command.java:90) ~[crate-cli.jar:?]

	at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.metadata.MappingMetadata.getSourceAsMap()" because "mappingMetadata" is null

	at io.crate.metadata.upgrade.MetadataIndexUpgrader.createUpdatedIndexMetadata(MetadataIndexUpgrader.java:66) ~[crate-server.jar:?]

	at io.crate.metadata.upgrade.MetadataIndexUpgrader.createUpdatedIndexMetadata(MetadataIndexUpgrader.java:57) ~[crate-server.jar:?]

	at io.crate.metadata.upgrade.MetadataIndexUpgrader.apply(MetadataIndexUpgrader.java:47) ~[crate-server.jar:?]

	at io.crate.metadata.upgrade.MetadataIndexUpgrader.apply(MetadataIndexUpgrader.java:37) ~[crate-server.jar:?]

	at org.elasticsearch.cluster.metadata.MetadataIndexUpgradeService.lambda$new$0(MetadataIndexUpgradeService.java:74) ~[crate-server.jar:?]

	at org.elasticsearch.cluster.metadata.MetadataIndexUpgradeService.upgradeIndexMetadata(MetadataIndexUpgradeService.java:97) ~[crate-server.jar:?]

	at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:205) ~[crate-server.jar:?]

	at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:188) ~[crate-server.jar:?]

	at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:122) ~[crate-server.jar:?]

	at org.elasticsearch.node.Node.start(Node.java:865) ~[crate-server.jar:?]

	at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:204) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:268) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) ~[crate-app.jar:4.8.0-202202080005-ee0cc45]

	... 6 more

[2022-02-08T20:39:13,071][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] stopping ...

[2022-02-08T20:39:13,121][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] stopped

[2022-02-08T20:39:13,121][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] closing ...

[2022-02-08T20:39:13,133][INFO ][o.e.n.Node               ] [aB91Af1abdAb-1] closed
```

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
tried upgrading 4.6 to 4.7. confirmed that a blob index from 4.6 has a `default` `mappingMetadata` and upgrades to 4.7 without a problem.
could be related to [def0b7b](https://github.com/crate/crate/pull/10501/commits/def0b7b0d979d5803a35b69d8d922eeaad37a1db)

**Review by mfussenegger — APPROVED** [review]
Maybe worth adding a unit test if it's not too much effort.  We have the crate-qa test that already caught this, so not really required but might help shorten the feedback loop in case of future regressions

Otherwise lgtm

**Comment by jeeminso** [comment]
Thank you, will try to add a test and a changes entry.

**Comment by mfussenegger** [comment]
> Thank you, will try to add a test and a changes entry.

If I understood it correctly, the changes entry won't be needed as this happens on an upgrade from 4.7 to 4.8 and 4.8 isn't out yet?

**Comment by jeeminso** [comment]
Hello @mfussenegger, I was unsure of the scope of the testcase suggestion. The test I just added is more of a hardcoded null valued `mappingMetadata` scenario, which covers less than the crate-qa test that caught this problem. I think I should write an integration test that creates a blob table (or the sub-logic that creates the `indexMapping`) and try to feed its `IndexMapping` to the `IndexUpgrader`. This way upgrades to nightly should be covered.

**Comment by mfussenegger** [comment]
> Hello @mfussenegger, I was unsure of the scope of the testcase suggestion. The test I just added is more of a hardcoded null valued `mappingMetadata` scenario, which covers less than the crate-qa test that caught this problem. I think I should write an integration test that creates a blob table (or the sub-logic that creates the `indexMapping`) and try to feed its `IndexMapping` to the `IndexUpgrader`. This way upgrades to nightly should be covered.

I think the test you added is perfect. We don't need another integration test because the crate-qa already covers that part

**Pull request merged**
