### PR TITLE
Add `relations` to `sys.snapshots`

### LINKED ISSUE #14087: `tables` column in `sys.snapshots` is missing quotes
### CrateDB version

5.3.0

### CrateDB setup information

_No response_

### Problem description

Table names in `sys.snapshots`'s `tables` array column aren't quoted, making it hard to use its values.

### Steps to Reproduce

```sql
CREATE TABLE doc."I-need-quotes" (a INTEGER);

CREATE REPOSITORY demo_repository TYPE s3 WITH (bucket = '...', base_path = 'debug', access_key = '...', secret_key = '...');

CREATE SNAPSHOT demo_repository.s1 TABLE doc."I-need-quotes";

SELECT tables[1]
FROM sys.snapshots
WHERE name = 's1';
-- returns doc.I-need-quotes 
```

In a situation where I want to automate dropping tables before a restore, I may want to write queries such as:
```sql
SELECT 'DROP TABLE ' || t
FROM (
  SELECT UNNEST(tables) AS t
  FROM sys.snapshots
  WHERE name = 's1'
);
-- returns DROP TABLE doc.I-need-quotes (will fail, missing quotes)

-- or
SELECT 'DROP TABLE ' || QUOTE_IDENT(t)
FROM (
  SELECT UNNEST(tables) AS t
  FROM sys.snapshots
  WHERE name = 's1'
);
-- returns DROP TABLE "doc.I-need-quotes" (will fail, incorrectly quoted)

-- only working alternative
SELECT 'DROP TABLE ' || QUOTE_IDENT(SPLIT_PART(t, '.', 1)) || '.' || QUOTE_IDENT(SPLIT_PART(t, '.', 2))
FROM (
  SELECT UNNEST(tables) AS t
  FROM sys.snapshots
  WHERE name = s1'
);
```

### Actual Result

See above.

### Expected Result

Return a properly quoted name (`doc."I-need-quotes"`) in `tables` that can easily be used further. Alternatively, split up `table_name` and `schema_name` into separate columns, so `QUOTE_IDENT` can get applied to them.

### PR DESCRIPTION
**Pull request by seut**
The new column ~`table_relations`~ `relations` contains an array of objects including the `table_schema` and `table_name` of all tables inside the snapshot.

Closes #14087.

**Do not merge until master is on `5.9`.**

### CODE REVIEW

**Review by mfussenegger — APPROVED** [review]
I'm a bit unsure about the naming because it is not clear what the difference between `tables` and `table_relations` is but I don't really have a better idea. 

`table_objects` maybe? Would highlight that it is merely a structural difference

**Comment by seut** [comment]
> I'm a bit unsure about the naming because it is not clear what the difference between `tables` and `table_relations` is but I don't really have a better idea.
> 
> `table_objects` maybe? Would highlight that it is merely a structural difference

Yes I also wasn't sure about the naming and could not come up with a better name. What about only `relations`?

**Comment by matriv** [comment]
> > I'm a bit unsure about the naming because it is not clear what the difference between `tables` and `table_relations` is but I don't really have a better idea.
> > `table_objects` maybe? Would highlight that it is merely a structural difference
> 
> Yes I also wasn't sure about the naming and could not come up with a better name. What about only `relations`?

It's not nice, but since we don't want to change `tables` for bwc, how about `tables_as_object`?

**Comment by seut** [comment]
As agreed on in an internal chat, the new column should be named `relations`.
I've pushed a fixup commit which renames it.

**Review by mfussenegger — APPROVED** [review]

**Comment by seut** [comment]
retest this please

Unrelated flaky MetadataTrackerITest failure.

**Pull request merged**
