### PR TITLE
JMX Monitoring documentation improvements

### PR DESCRIPTION
**Pull request by jayeff**
## Summary of the changes / Why this improves CrateDB

- use correct placeholders
- remove duplicate docker image name
- use double quotes for CRATE_JAVA_OPTS as backslash does not work with
  single quotes

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by norosa — APPROVED** [review]
looks great! thanks!

**Comment by jayeff** [comment]
retest this please

**Comment by jayeff** [comment]
@norosa FYI: I just rebased my commit on current master and force pushed. Last test run had a failed check

```
BlobPathITest > testDataIsDeletedSpecificIndexBlobPath FAILED
java.lang.RuntimeException at [C81272B36C493795:EC119A262107020]:0
Caused by: java.nio.file.NoSuchFileException at UnixException.java:92
```

I could get the test to run again (I thought "retest this please" should trigger a rerun of the checks 🤔).

I hope it's fine that I rebased and force pushed.

**Comment by jayeff** [comment]
hm.. still failing 🤷

**Comment by mkleen** [comment]
retest this please

**Comment by norosa** [comment]
@jayeff I can't help with the Java error. but @mkleen probably can :)

**Comment by mkleen** [comment]
> @jayeff I can't help with the Java error. but @mkleen probably can :)

https://github.com/crate/crate/pull/11150

**Comment by seut** [comment]
@mergifyio rebase

**Comment by seut** [comment]
@Mergifyio rebase

**Pull request merged**
