### PR TITLE
Add tests to verify analyzers do not normalize nondeterministic func

### PR DESCRIPTION
**Pull request by jeeminso**

### CODE REVIEW

**Comment by jeeminso** [comment]
TODO: double check if they fail without https://github.com/crate/crate/pull/15924

**Comment by jeeminso** [comment]
retest this please

**Review by BaurzhanSakhariev — APPROVED** [review]
Thanks! 

A also confirmed that without https://github.com/crate/crate/pull/15924/ it gets normalized to Literal

**Comment by jeeminso** [comment]
@mergifyio backport 5.7

**Pull request merged**
