### PR TITLE
Documentation Theme: Update to `crate-docs-theme>=0.37.0.dev0`, introducing dark mode

### PR DESCRIPTION
**Pull request by amotl**
## About
Use the new documentation theme that introduces dark mode. Thanks, @msbt.

## Preview
https://crate--17001.org.readthedocs.build/en/17001/

## References
- https://github.com/crate/crate-docs-theme/pull/546
- https://github.com/crate/cratedb-guide/pull/136

### CODE REVIEW

**Comment by seut** [comment]
I humble to merge in a change that is not even merge into the docs theme yet. Any reason for this, shouldn't we merge&release first?

**Comment by amotl** [comment]
Sure. The patch is mostly there to check if everything is in order prior to the release, and doesn't need to be merged.

**Comment by amotl** [comment]
crate-docs-theme 0.37.0 has been released.

**Comment by amotl** [comment]
crate-docs-theme 0.37.1.dev0 has been released, including a fix for dark mode.

- https://github.com/crate/crate-docs-theme/pull/554

**Pull request closed without merging**
