### PR TITLE
Fix error handling for unknown object keys from aliasSymbols

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Fixes:
```
cr> create table t (obj_dynamic object);
CREATE OK, 1 row affected (1.605 sec)

cr> set error_on_unknown_object_key = 'false';
SET OK, 0 rows affected (0.009 sec)

cr> select alias['u'] from (select obj_dynamic['u'] as alias from t) tbl;
ColumnUnknownException[Column alias['u'] unknown]  <-- not expected since `alias['u']` is child of a dynamic object and the setting it set to false.
```

There is a fall back logic to use subscript function with appropriate column policy, but the column policy is not available.

The approach to address this issue is to allow resolving a sub-column from the source query whose outputs contain only the parent column. The sub-column is then added to the source's outputs as well.

i.e.:
Resolve `alias['u']` from
```
select alias['u'] from (select obj_dynamic['u'] as alias from t) tbl;
```
as `obj_dynamic['u']['u']`(a reference) as if the `analyzedRelation` for
```
(select obj_dynamic['u'] as alias from t)
```
includes `(obj_dynamic['u']['u'] AS alias['u'])` in its outputs. Then actually adds `obj_dynamic['u']['u']` to the outputs.

A regression caused by https://github.com/crate/crate/pull/17052.

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
This is WIP to fix error handling of unknown object key

**Comment by jeeminso** [comment]
Hi @mfussenegger , this PR basically expands on the optimization step in `QueriedSelectRelation.getField`. Please review if I am going in a wrong direction.

**Comment by seut** [comment]
@jeeminso 
This looks like the wrong approach to me as I think we want to keep using subscript functions in such cases.
Won't this be simply solved by not applying the column policy logic if the type it `UNDEFINED` at https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java#L759? 

Example:

```
                if ((currentType == UndefinedType.INSTANCE) == false) {
                    ColumnPolicy parentPolicy = baseType.columnPolicy();
                    for (String p : parts) {
                        if (ArrayType.unnest(currentType) instanceof ObjectType objectType) {
                            parentPolicy = objectType.columnPolicy();
                            currentType = objectType.innerType(p);
                        }
                    }
                    if (parentPolicy == ColumnPolicy.STRICT ||
                        (parentPolicy == ColumnPolicy.DYNAMIC && context.errorOnUnknownObjectKey())) {
                        throw e;
                    }
                }
```

**Comment by jeeminso** [comment]
We must check if `error_on_unknown_key` is set to `false` even if the type is `UNDEFINED` since it could be a child of `DYNAMIC`. But a child of `IGNORED` is also typped `UNDEFINED` in which case we must ignore `error_on_unknown_key`.

**Comment by jeeminso** [comment]
We allocate subscript functions within `ExpressionAnalyzer.visitSubscriptExpression`. I think I could try to experiment if we can expand `fieldProvider.resolveField` method with one more parameter which is a fall back logic to subscript function. That way the parent policy is available when allocating the subscript function.

**Pull request closed without merging**
