### PR TITLE
Implement LTRIM() and RTRIM() functions

### LINKED ISSUE #7800: add Commonly used system functions
Some commonly useful system functions are very necessary for the database.
Most sinario will be applied to these function，so expect official  add to the system library.

- [x] REPLACE
- [x] LPAD/RPAD
- [ ] TRIM/RTRIM/LTRIM

regard!
thanks!

### PR DESCRIPTION
**Pull request by verkhovin**
Tried to implement LTRIM and RTRIM scalar functions in order to finally resolve #7800

### CODE REVIEW

**Comment by seut** [comment]
@verkhovin 
Thanks a lot for this contribution!
Looks really great. May we ask to also support passing in charsToTrim into both functions to be fully compatible with postgresql ltrim/rtrim functions?

**Comment by seut** [comment]
ok to test

**Comment by verkhovin** [comment]
@seut just to be sure. do you mean something like `ltrim('aaastr', 'a')` (result is `str`)?
Yes, I can do it. Should i do it in the scope of the same PR?

**Comment by seut** [comment]
> just to be sure. do you mean something like ltrim('aaastr', 'a') (result is str)?

Yes exactly.

> Should i do it in the scope of the same PR?

Yes but if your prefer a dedicated PR it's also totally fine.
Thanks a lot!

**Comment by verkhovin** [comment]
@seut Ok. I'll try to implement it soon. I'll append it to the current PR.

**Comment by verkhovin** [comment]
@seut Please, take a look. I'll squash all changes to one commit after passing the review if it needed.

**Comment by verkhovin** [comment]
@seut Please, take a look. I'll squash all changes to one commit after passing the review if it needed.

**Comment by seut** [comment]
@verkhovin 
Looks great, thanks a lot!
I'll take care of merging and adjusting some small bits (documentation formatting) asap.

**Comment by seut** [comment]
retest this please

```
* Get more help at https://help.gradle.org

The message received from the daemon indicates that the daemon has disappeared.

Build request sent: Build{id=f30b1774-1daa-4b0a-bb9d-f6c72a78c75b, currentDir=/var/lib/jenkins/workspace/CrateDB/crate_on_pr}

Attempting to read last messages from the daemon log...

Daemon pid: 32252

  log file: /var/lib/jenkins/.gradle/daemon/6.0-20191006230018+0000/daemon-32252.out.log

----- Last  20 lines from daemon log file - daemon-32252.out.log -----
```

**Comment by seut** [comment]
@verkhovin 
I've slightly changed the internal `trim` function so that all variants uses the same implementation. Commits are squashed and merged.
Thanks again for this nice contribution!

**Comment by verkhovin** [comment]
@seut 
Thank you!

**Pull request merged**
