### PR TITLE
bp: Fix Snapshot Corruption in Edge Case

### PR DESCRIPTION
**Pull request by mkleen**
https://github.com/elastic/elasticsearch/commit/e244d65869c2864f372af066724f1bf1f5c729a1

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mfussenegger** [comment]
Looks like the actual fix was already included in https://github.com/crate/crate/commit/f5505cbfa113aa2a5612d910fde2e29bd919e06d and this just moves (changes?) the xcontent representation?

**Review by mfussenegger — APPROVED** [review]

**Comment by mkleen** [comment]
> Looks like the actual fix was already included in [f5505cb](https://github.com/crate/crate/commit/f5505cbfa113aa2a5612d910fde2e29bd919e06d) and this just moves (changes?) the xcontent representation?

yes, it was already applied. I was just after the xcontent change for conistency.

**Comment by mfussenegger** [comment]
> > Looks like the actual fix was already included in [f5505cb](https://github.com/crate/crate/commit/f5505cbfa113aa2a5612d910fde2e29bd919e06d) and this just moves (changes?) the xcontent representation?
> 
> yes, it was already applied. I was just after the xcontent change for consistency.

:+1: 
Might want to add that remark to the commit message for future git-archeology

**Comment by mkleen** [comment]
> > > Looks like the actual fix was already included in [f5505cb](https://github.com/crate/crate/commit/f5505cbfa113aa2a5612d910fde2e29bd919e06d) and this just moves (changes?) the xcontent representation?
> > 
> > 
> > yes, it was already applied. I was just after the xcontent change for consistency.
> 
> 👍
> Might want to add that remark to the commit message for future git-archeology

Good Idea, thanks.

**Pull request merged**
