### PR TITLE
Use cause to determine if node with primary is closing.

### PR DESCRIPTION
**Pull request by kovrus**
## Summary of the changes / Why this improves CrateDB

Backport of https://github.com/elastic/elasticsearch/pull/39723

## Checklist

 - [ ] User relevant changes are recorded in ``CHANGES.txt``
 - [x] Touched code is covered by tests
 - [ ] Documentation has been updated if necessary
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by kovrus** [comment]
Shall we partially move the `ReplicationOperationTests` test over? 🤔   

https://github.com/elastic/elasticsearch/pull/39723/files#diff-2b129e689e50214868cf0f663b470462L206

**Comment by seut** [comment]
> Shall we partially move over the ReplicationOperationTests test? 

Maybe even the whole test class?

**Comment by seut** [comment]
@kovrus The `ReplicationOperationTests` do exists now at master, anything else stopping us from finishing this up?

**Comment by kovrus** [comment]
@seut nope. rebasing it.

**Pull request merged**
