### PR TITLE
Allowing Null Column on Create Table(Pull Request for Issue #14633)

### PR DESCRIPTION
**Pull request by dshunter107**
## Summary of the changes / Why this improves CrateDB
This is my first time submitting on this project, and I am relatively new to programming. I had to learn ANTLR in order to work on this issue. 

This is for issue https://github.com/crate/crate/issues/14633. This is my first draft of this. I chose the
option of putting the Null option into Antlr. The program recognizes the
Null and puts it as a column constraint.

I also create a test to see that the java object structure creates the
table. I would like some feedback, especially on the "do nothing"
portion of the recommendation for this issue.

How would you want the "do nothing" portion to be implemented? Would you
prefer that the corresponding Java object not be created?

Also, would there ever be a situation where a programmer would want that
classification to be present (even though the default is null).

## Checklist
no user facing changes. 
 - [ n] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [y ] Updated documentation & `sql_features` table for user facing changes
 - [y ] Touched code is covered by tests
 - [y] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [y ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by dshunter107** [comment]
Hello, I think I accidentally merged something when I was trying to get my version of the repository up-to-date with the crate repository.

**Comment by matriv** [comment]
@dshunter107 First of all thank you for working on this!
First of all, I'd kindly ask you to work on a branch in your fork, and not on `master`, so please close this PR, create a branch with your changes and open a new PR from that branch.

Then please remove the test here: [TestSqlParser.java](https://github.com/crate/crate/pull/14814/files#diff-3923c2f83809a9379cae62e93537beb148f3d59ecf0ecf6f094a40cf2a92b5ff)
and add some `null` "constraints" in `TestStatementBuilder`, you can use a couple of existing tests in `testCreateTableStmtBuilder()`, just add `null` to some columns.
Please add `null` to a couple of tests in `testAlterTableStmtBuilder()`.

Then you will see that you need to implement:
```
@Override
public Void visitNullColumnConstraint(NullColumnConstraint<?> node, Integer context) {
    return null;
}
```
in `SqlFormatter` to make it work (we don't add anything to the output as `NULL` is the default behaviour and we don't need to expose it.

After that you need to take care during Analysis of both `CREATE TABLE...` and `ALTER TABLE ADD column...`, that `NULL` cannot be used in combination with `PRIMARY KEY`. You can implement this check in `TableElementsAnalyzer` and please add a test in `CreateAlterTableStatementAnalyzerTest` and  in `AlterTableAddColumnAnalyzerTest` .

**Review by matriv — CHANGES_REQUESTED** [review]
@dshunter107 First of all thank you for working on this!
First of all, I'd kindly ask you to work on a branch in your fork, and not on `master`, so please close this PR, create a branch with your changes and open a new PR from that branch.

Then please remove the test here: [TestSqlParser.java](https://github.com/crate/crate/pull/14814/files#diff-3923c2f83809a9379cae62e93537beb148f3d59ecf0ecf6f094a40cf2a92b5ff)
and add some `null` "constraints" in `TestStatementBuilder`, you can use a couple of existing tests in `testCreateTableStmtBuilder()`, just add `null` to some columns.
Please add `null` to a couple of tests in `testAlterTableStmtBuilder()`.

Then you will see that you need to implement:
```
@Override
public Void visitNullColumnConstraint(NullColumnConstraint<?> node, Integer context) {
    return null;
}
```
in `SqlFormatter` to make it work (we don't add anything to the output as `NULL` is the default behaviour and we don't need to expose it.

After that you need to take care during Analysis of both `CREATE TABLE...` and `ALTER TABLE ADD column...`, that `NULL` cannot be used in combination with `PRIMARY KEY`. You can implement this check in `TableElementsAnalyzer` and please add a test in `CreateAlterTableStatementAnalyzerTest` and  in `AlterTableAddColumnAnalyzerTest` .

**Comment by dshunter107** [comment]
Hello @Matriv, 

Thank you very much for the feedback. I was able to learn a lot from your comments. I have worked on the code, and I am ready to try another pull request. I am now working on a branch in my fork, but there is one thing I am a little confused about. 

Should I try to do a pull request on a random branch that is currently in crate? Or should I go from my branch to master? I am guessing that I need to put it in a branch, but I am not sure which one to put it in.

**Comment by matriv** [comment]
Happy to help @dshunter107 !

You should open your PR from your branch in your fork directly to `master` branch of crate repo.

**Pull request closed without merging**
