### PR TITLE
Clarify DataType.sanitizeValue and DataType.valueForInsert

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Resolves https://github.com/crate/crate/issues/14178

The two cannot be merged because for example `TimeTZType.INSTANCE.valueForInsert()` throws an `UnsupportedOperationException` since a `timetz` cannot be inserted while `TimeTZType.INSTANCE.sanitizeValue()` does not.

In order to make clear distinct of the two, I renamed `sanitizeValue` > `sanitizeType` and `valueForInsert` > `sanitizeValue` to characterize one is meant for types and the other is for values.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
What do you think @mfussenegger ?

**Comment by mfussenegger** [comment]
> The two cannot be merged because for example TimeTZType.INSTANCE.valueForInsert() throws an UnsupportedOperationException since a timetz cannot be inserted while TimeTZType.INSTANCE.sanitizeValue() does not.

insert support be primarily handled via the `storageSupport` property (and the indexer and reader availability). We don't need to rely on `valueForInsert` throwing an exception for that.


> In order to make clear distinct of the two, I renamed sanitizeValue > sanitizeType and valueForInsert > sanitizeValue to characterize one is meant for types and the other is for values.

Both operate on values. To me this rename makes the difference somehow _less_ clear. 
Maybe it helps to come up with a name if we first attempt to state the difference in a sentence or two?

**Comment by jeeminso** [comment]
> insert support be primarily handled via the storageSupport property (and the indexer and reader availability). We don't need to rely on valueForInsert throwing an exception for that.

I initially thought in this direction but `ValidatedRawInsertSource` invoking `valueForInsert` stopped me from moving further. I will proceed with this approach.

> Both operate on values. To me this rename makes the difference somehow less clear.
Maybe it helps to come up with a name if we first attempt to state the difference in a sentence or two?

Thanks, I thought the new names represent the method level comments better. I will proceed with your first comment first (to merge `valueForInsert` logic into `StorageSupport`)

**Comment by mfussenegger** [comment]
> (to merge valueForInsert logic into StorageSupport)

That's not what I suggested. I merely wanted to point out that we don't necessarily need `valueForInsert` to throw an unsupported error if storage support is missing.

**Comment by jeeminso** [comment]
Failed attempt, closing.

**Pull request closed without merging**
