### PR TITLE
Add Google Cloud Storage Repository [wip]

### PR DESCRIPTION
**Pull request by bergwerf**
## Summary of the changes / Why this improves CrateDB

Google Cloud Storage (GCS) is currently not supported as backend for snapshots. It is not possible to use it via the S3 plugin because it is not fully S3 compatible (see https://github.com/crate/crate/issues/13879). This contribution implements a minimal Google Cloud Storage repository plugin.

## Problems

- [x] What should the Java package name be? (currently `io.crate.gcs`)
- [x] What should the Crate repository type name be? (currently `gcs`)
- [ ] How should testing be implemented? (currently there are no tests)
- [ ] Clarify the role of `BlobContainer.children` (see https://community.crate.io/t/question-about-blobcontainer-children/1499) and implement if essential.
- [ ] Are explicit settings for credentials (instead of using the environment variables supported by the Google Cloud Storage client library) preferred?
- [ ] The Azure plugin needs to be updated to resolve a Google Guava dependency conflict. Can this be resolved in this PR or should a separate PR be opened?
- [ ] The plugin should be loaded (`./gradlew :app:run` does *NOT* load the plugin by default, it also doesn't load the Azure plugin, a list of default plugins is hardcoded in `BootstrapProxy`, it is unclear how the plugin discovery mechanism works)

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by bergwerf** [comment]
This is my initial proposal for a Google Cloud Storage plugin. I need some directions on how to resolve the problems outlined above.

**Comment by bkleef** [comment]
@bergwerf this functionality would also be very useful for us! Nice work! 👍

**Comment by mfussenegger** [comment]
>  What should the Java package name be? (currently io.crate.gcs)

`io.crate.gcs` is okay

> What should the Crate repository type name be? (currently gcs)

`gcs` sounds good

> How should testing be implemented? (currently there are no tests)

I assume there is no self-contained and locally runnable gcs implementation similar to minio? Then I guess we'll have to resort to best effort unit tests with some mocking.

 Clarify the role of BlobContainer.children (see https://community.crate.io/t/question-about-blobcontainer-children/1499) and implement if essential.

It kinda is about sub-directories.
You could have a look at the opensearch implementation:

https://github.com/opensearch-project/OpenSearch/blob/9b2b3c94728bc7f5f3771b440245a55341940a38/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobContainer.java#L75

https://github.com/opensearch-project/OpenSearch/blob/9b2b3c94728bc7f5f3771b440245a55341940a38/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobStore.java#L186-L198

(You don't need to use any SecurityManager related things that they use. We don't active it, as it's deprecated in new JDKs and going away)

> Are explicit settings for credentials (instead of using the environment variables supported by the Google Cloud Storage client library) preferred?

Yes, Users should be able to set them via `CREATE REPOSITORY`

> The Azure plugin needs to be updated to resolve a Google Guave dependency conflict. Can this be resolved in this PR or should a separate PR be opened?

A separate PR would be preferred

> The plugin should be loaded (./gradlew :app:run does NOT load the plugin by default, it also doesn't load the Azure plugin, a list of default plugins is hardcoded in BootstrapProxy, it is unclear how the plugin discovery mechanism works)

That `./gradlew :app:run` doesn't load plugins is expected. You'll have to build the full tarball if you want to have a version that includes the plugins with:

```
./gradlew installDist
./app/build/install/crate/bin/crate
```


Regarding the default list: That should not be extended. GCS should be loaded dynamically, same as the azure repository.

Loading works via the `PluginsService` and it will need a `plugin-descriptor.properties` file for the discovery & loading mechanism to work.

**Comment by bergwerf** [comment]
> > How should testing be implemented? (currently there are no tests)  
> 
> I assume there is no self-contained and locally runnable gcs implementation similar to minio?

There actually happens to be one:
https://github.com/fsouza/fake-gcs-server

So now the question is; how are automated tests that use a mock server like this one implemented such that they can run alongside all other tests?
(or would we use a manual test program for this?)

> 
> > Clarify the role of BlobContainer.children (see https://community.crate.io/t/question-about-blobcontainer-children/1499) and implement if essential.
> 
> It kinda is about sub-directories.
> You could have a look at the opensearch implementation:
> 
> https://github.com/opensearch-project/OpenSearch/blob/9b2b3c94728bc7f5f3771b440245a55341940a38/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobContainer.java#L75
> 
> https://github.com/opensearch-project/OpenSearch/blob/9b2b3c94728bc7f5f3771b440245a55341940a38/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobStore.java#L186-L198

Funny to see this same kind of thing replicated :). The repository base
classes of OpenSearch are forked from ElasticSearch, just as CrateDB
has code forked from ElasticSearch?

> > Are explicit settings for credentials (instead of using the environment variables supported by the Google Cloud Storage client library) preferred?  
> 
> Yes, Users should be able to set them via `CREATE REPOSITORY`

Ok. Google recommends the use of a so called service account which
has credentials in the form of a JSON file ([1]). There are two ways we
could use this as a repository setting in Crate:

1. A setting containing a path, which is read when the repository is
created.

2. A setting containing a JSON string.

The second option does not seem like a very elegant solution. What do
you think? We could also simply support both options.

[1]: https://github.com/googleapis/google-cloud-java#using-a-service-account-recommended

**Comment by mfussenegger** [comment]
> So now the question is; how are automated tests that use a mock server like this one implemented such that they can run alongside all other tests? (or would we use a manual test program for this?)

We usually create a python test case that launches the mock server process and a CrateDB node. See `blackbox/test_s3.py` for an example.


> Funny to see this same kind of thing replicated :). The repository base classes of OpenSearch are forked from ElasticSearch, just as CrateDB has code forked from ElasticSearch?

CrateDB is more of a hard fork due to different direction (more full buy-in into SQL with it's own engine, long before ElasticSearch added a light SQL layer too)
OpenSearch was a fork due to the License switch of ElasticSearch and tries to keep the interface - although afaik they now also move in slightly different directions (E.g. with segment replication).

So yes, both share Elasticsearch components. And the repository plugin interfaces remained quite stable/unchanged so far.

> Ok. Google recommends the use of a so called service account which has credentials in the form of a JSON file ([1]). 

How does the JSON file look like?

If it consists of a key/account name, we could use these as `WITH` options and internally create the JSON

Users with permissions to create a repository may not have access to the filesystem on a server (and rolling out files on all nodes more tedious), so it would help if the users can setup the repository without that.

**Comment by mfussenegger** [comment]
I think you could resolve the version conflict by forcing the version by adding a new entry in `gradle/dependencies.gradle`. Guava usually doesn't have breaking changes, so it's likely that both the azure dependency and google-cloud-storage would work with 30.1.1

If that's the case you can leave the azure plugin as is for now.

**Comment by bergwerf** [comment]
About the service account key, it contains a private key and a couple of other details. Below is an example.
```json
{
  "type": "service_account",
  "project_id": "project-id",
  "private_key_id": "0123456789abcdef0123456789abcdef01234567",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...BASE64...\n-----END PRIVATE KEY-----\n",
  "client_email": "service-account-id@project-id.iam.gserviceaccount.com",
  "client_id": "012345678901234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service-account-id%40project-id.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
```
I don't think it's a good idea to take it apart, and doing so doesn't have much benefit. It could be a masked string setting.

**Comment by bergwerf** [comment]
I ended up having to force a whole bunch of versions:
```
force "com.google.guava:guava:${versions.google_guava}"
force "com.google.http-client:google-http-client:${versions.google_http_client}"
force "com.google.http-client:google-http-client-gson:${versions.google_http_client_gson}"
force "com.google.errorprone:error_prone_annotations:${versions.google_errorprone}"
force "com.google.j2objc:j2objc-annotations:${versions.j2objc_annotations}"
force "org.checkerframework:checker-qual:${versions.checker_qual}"
force "io.grpc:grpc-context:${versions.grpc_context}"
```

Now `./gradlew installDist` finishes successfully (I had to run `./gradlew clean` to get rid of old JARs).

I can run `./app/build/install/crate/bin/crate`, and in the log I can see that the plugin is loaded.

However, I cannot inspect the instance or execute queries via https://github.com/crate/crate-admin. I can if I specify `-Cpath.home=../sandbox/crate` (which must be run from the `./app` directory otherwise `../server/src/test/resources/keystore.pcks12` cannot be found), but then the plugin is not loaded. How should I proceed?

**Comment by mfussenegger** [comment]
> About the service account key, it contains a private key and a couple of other details. Below is an example.


I think we should have separate options for the keys.

```sql
CREATE REPOSITORY repo1 TYPE gcs WITH (project_id = ?, private_key_id = ?, private_key = ?, ...)
```

Ideally with sensible defaults where possible (e.g. auth_uri, auth_provider_x509_cert_url, universe_domain, etc..)


> However, I cannot inspect the instance or execute queries via https://github.com/crate/crate-admin.

Are you trying to run crate-admin as separate project?
It's included in the installDist build and should be available under `http://localhost:4200` if you run `./app/build/install/crate/bin/crate` and have no other instance running locally.

You shouldn't have to add any extra options.

**Comment by bergwerf** [comment]
> I think we should have separate options for the keys.

I'm personally not a huge fan of this, because I couldn't find documentation from Google about what is supposed to be in the service account key object. I imagine the contents could change in the future, with different possible combinations of key/values. Their client library consumes the whole JSON object at-once, so it doesn't expect the user (programmer) to take it apart and re-assemble it.

Apart from this argument, it would also simply be easier to implement storing the whole key file as a single setting. What do you think?

**Comment by seut** [comment]
@bergwerf 

> > I think we should have separate options for the keys.
> 
> I'm personally not a huge fan of this, because I couldn't find documentation from Google about what is supposed to be in the service account key object. I imagine the contents could change in the future, with different possible combinations of key/values. Their client library consumes the whole JSON object at-once, so it doesn't expect the user (programmer) to take it apart and re-assemble it.
> 
> Apart from this argument, it would also simply be easier to implement storing the whole key file as a single setting. What do you think?

We'd really prefer using each setting of the JSON provided by google as a dedicated setting, like @mfussenegger described. This would align to existing other repository implementation and also adds benefits of early format validation (ok not a good argument when one downloads the complete payload).


JFYI: OpenSearch is doing it similar (https://github.com/opensearch-project/OpenSearch/blob/main/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageClientSettings.java).

**Comment by bergwerf** [comment]
@mkleen Cool, thanks!

**Pull request closed without merging**
