### PR TITLE
Backport changes for newest crate-docs-theme, plus RST fix

### PR DESCRIPTION
**Pull request by mechanomi**
I noticed the 2.3 release branch wasn't building on RTD any more. this changeset fixes that problem

### CODE REVIEW

**Comment by mfussenegger** [comment]
Same here as in the other PR, we'd have to add a Jenkinsfile for tests to pass

**Comment by mechanomi** [comment]
see https://github.com/crate/crate/pull/10338

**Comment by mechanomi** [comment]
related 1.2 backport PR here: https://github.com/crate/crate/pull/10337

**Comment by mechanomi** [comment]
@mfussenegger I backported the Jenkinsfile from the 3.3 release branch. the build fails. should we attempt to get the build working or should we drop docs support for 2.3?

**Comment by mechanomi** [comment]
dropping 2.3 from our hosted docs versions. closing

**Pull request closed without merging**
