### PR TITLE
Add SSL/TLS transport security

### PR DESCRIPTION
**Pull request by salyh**
This PR adds SSL/TLS transport layer security so that cluster communication as well as connections to the cluster via CrateClient are secured by TLS. 

Setup is done in crate.yml
<pre>
###################################### Security ####################################

# Enable or disable transport layer security (default: false)
#security.ssl.transport.node.enabled: true

# Enable or disable SSL hostname verfification (default: true)
#security.ssl.transport.node.hostname_verification.enabled: false

# Enable or disable hostname resolving for hostname verfification (default: true)
# This settings has no effect if hostname_verification is disabled
#security.ssl.transport.node.hostname_verification.resolve_host_name: false

# If true then the nodes have to trust each other, if false then only the client node has to trust the server node
# (default: true)
#security.ssl.transport.node.need_clientauth: false

# Path to the keystore (default is value of javax.net.ssl.keyStore)
# This setting is mandatory if javax.net.ssl.keyStore is not set
#security.ssl.transport.node.keystore.path: null

# Keystore password (default is value of javax.net.ssl.keyStorePassword or 'changeit' if not set)
#security.ssl.transport.node.keystore.password: changeit

# Keystore type (default is value of javax.net.ssl.keyStoreType or 'JKS' if not set)
# JKS or PKCS12 are supported
#security.ssl.transport.node.keystore.type: PKCS12

# Path to the truststore (default is value of javax.net.ssl.trustStore)
# This setting is mandatory if javax.net.ssl.trustStore is not set
# Can be the same as security.ssl.transport.node.keystore.path
#security.ssl.transport.node.truststore.path: null

# Truststore password (default is value of javax.net.ssl.trustStorePassword or 'changeit' if not set)
#security.ssl.transport.node.truststore.password: changeit

# Truststore type (default is value of javax.net.ssl.trustStoreType or 'JKS' if not set)
# JKS or PKCS12 are supported
#security.ssl.transport.node.truststore.type: PKCS12

# SSL context cache size (default: 1000)
# A value of zero means unlimited (WARNING: this can cause memory leaks)
#security.ssl.transport.node.session.cache_size: 1000

# SSL context session timeout expressed in seconds (default: 86400, which means 24h)
# A value of zero means unlimited (WARNING: this can cause memory leaks)
#security.ssl.transport.node.session.timeout: 86400
</pre>

Than connect:
<code>
CrateClient client = new CrateClient(settings, true).addTransportAddress(new InetSocketTransportAddress("localhost", 4300));
</code>

For setting up the keystore and truststore together with a certificate authority (CA) look here:
<code>
security/pki-scripts/example.sh
</code>
Using a root CA make it possible to add new nodes to the cluster without a cluster restart.

Note: Running tests with ./gradlew test itest fails because of a bogus gradle dependency error, in IDEA its working well. ./gradlew test itest fails anyhow on master too :-)

### CODE REVIEW

**Comment by dobe** [comment]
hi @salyh 

thanks for your PR, this would be a great addition to crate. however it would be nice to have your security additions as a plugin to crate. we already planned to allow plugins for crate, however we have not finalized how we will support plugins. but this should happen the next few weeks along with the actual implementation. 

your code uses the elasticsearch plugin mechanism, which makes it a good candidate for a seperate project to be used as a plugin to crate. once we are done with the plugin architecture in crate, i think it will be just a  minor effort to adapt your code. just tell me if this would be ok for you - we would also keep you posted asap once we have nailed down the plugin architecture in crate. your code could also serve as one of the first crate plugin examples in our documentation then.

regards, bernd

**Comment by salyh** [comment]
Hi Bernd, 

sounds great, lets do it this way

-Hendrik

**Comment by salyh** [comment]
oh, forgot: Commit 9ca57afafcf51915a2ebb5197da9926582be3db5 provides a fix for udc (NPE and TLS). So this is unrelated to the things discussed above (would be better if i had opened a separate PR for that, sorry)

**Comment by bogensberger** [comment]
Hi @salyh 

we released crate 0.49.0 testing which contains the crate
plugin mechanism: https://cdn.crate.io/downloads/releases/crate-0.49.0.tar.gz

There is also an example plugin: https://github.com/crate/crate-example-plugin
and here is the documentation for the plugin mechanism: https://crate.io/docs/en/0.49.0/plugins.html.
If you have any questions feel free to ask.

Regards, Philipp

**Comment by salyh** [comment]
I looked into the plugin mechanism and found the following issues:
* PluginLoader is a singleton which loads settings only once, so its not possible to start more than one node with different settings in one JVM (classloader actually). This is bad for testing. Why make PluginLoader not a Module (or Component) to benefit from dependency injection and let guice manage singletons?
* CrateClient does not load plugins (ES TransportClient does, so why not the CrateClient). For the SSL stuff this is really required.
* As a plugin developer I would like to access the unittest suite of crate (respective es/lucene) to create randomized unittests. In the plugin example [CrateTestServer.java](https://github.com/crate/crate-example-plugin/blob/master/src/test/java/io/crate/CrateTestServer.java) is provided but it lacks of randomized testing and it starts crate in a separate JVM (thas great for integration testing IMHO but bad for unittests cause its to slow and not easy to handle and bad to debug). Seems there is no kind of test-jar for that in maven like http://www.elastic.co/guide/en/elasticsearch/reference/1.5/using-elasticsearch-test-classes.html

I have a working (but not perfect) solution for the first two points above. If you're interested i prepare a patch/PR for that.

Thanks
Hendrik

**Comment by seut** [comment]
@salyh 
Thanks for your reports related to our new plugin infrastructure.

We've just pushed a commit for supporting multiple PluginLoader instances with different settings inside one JVM, this should solve your first issue. https://github.com/crate/crate/commit/60be358d6df9041107a904c2919c5dcbf58d71d8
FYI: loading the PluginLoader via guice would require a non-trivial patch in ES and because we think the use-case is mostly if not all test related we don't want to dig in that currently ;) If you have another smart solution around, feel free to submit a PR.

Our published Java client JAR uses shaded libraries currently to solve conflict issues with other loaded libraries e.g. a Elasticsearch client JAR. We do not have a perfect solution right now on how plugins can be developed which could be loaded into both, server and client. We will discuss this asap, please be patient.

We've already talked about publishing a dedicated crate-testing JAR which will include all test helpers crate is using for its tests, we'll put this on our backlog, again please be patient ;)
On the other hand, I don't really understand why one would like to start a Crate instance inside a UnitTest as this would lead more to a integration test, not?

**Pull request closed without merging**
