### PR TITLE
Improve optimizer logging

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

This improves the logging for the iterative optimizer on log level TRACE. This really helps when debugging the optimizer and could be considered as pre-cursor for  https://github.com/crate/crate/issues/14397.

Example:

```
SELECT * FROM t1, t2 WHERE t1.x = t2.y and t1.x > 1;
```
from
```
[2023-08-31T16:37:54,421][TRACE][i.c.p.o.i.IterativeOptimizer] [Alplerspitz] Rule 'MoveFilterBeneathJoin' transformed the logical plan
16:37:54.421 [cratedb[Alplerspitz][netty-worker][T#3]] TRACE io.crate.planner.optimizer.iterative.IterativeOptimizer - Rule 'MoveFilterBeneathJoin' transformed the logical plan
[2023-08-31T16:37:54,422][TRACE][i.c.p.o.i.IterativeOptimizer] [Alplerspitz] Rule 'MoveConstantJoinConditionsBeneathNestedLoop' transformed the logical plan
16:37:54.422 [cratedb[Alplerspitz][netty-worker][T#3]] TRACE io.crate.planner.optimizer.iterative.IterativeOptimizer - Rule 'MoveConstantJoinConditionsBeneathNestedLoop' transformed the logical plan
[2023-08-31T16:37:54,423][TRACE][i.c.p.o.i.IterativeOptimizer] [Alplerspitz] Rule 'RewriteNestedLoopJoinToHashJoin' transformed the logical plan
16:37:54.423 [cratedb[Alplerspitz][netty-worker][T#3]] TRACE io.crate.planner.optimizer.iterative.IterativeOptimizer - Rule 'RewriteNestedLoopJoinToHashJoin' transformed the logical plan
[2023-08-31T16:37:54,423][TRACE][i.c.p.o.i.IterativeOptimizer] [Alplerspitz] Rule 'MergeFilterAndCollect' transformed the logical plan
16:37:54.423 [cratedb[Alplerspitz][netty-worker][T#3]] TRACE io.crate.planner.optimizer.iterative.IterativeOptimizer - Rule 'MergeFilterAndCollect' transformed the logical plan

```

to

```
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Optimize plan: 
 Filter[(x > 1)] (rows=0)
  └ NestedLoopJoin[INNER | (x = y)] (rows=unknown)
    ├ Collect[doc.t1 | [x] | true] (rows=unknown)
    └ Collect[doc.t2 | [y] | true] (rows=unknown)
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Rule optimizer_move_filter_beneath_join transformed the logical plan: 
NestedLoopJoin[INNER | (x = y)] (rows=unknown)
  ├ Filter[(x > 1)] (rows=0)
  │  └ Collect[doc.t1 | [x] | true] (rows=unknown)
  └ Collect[doc.t2 | [y] | true] (rows=unknown)
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Rule optimizer_move_constant_join_conditions_beneath_nested_loop transformed the logical plan: 
NestedLoopJoin[INNER | (x = y)] (rows=unknown)
  ├ Filter[(x > 1)] (rows=0)
  │  └ Collect[doc.t1 | [x] | true] (rows=unknown)
  └ Collect[doc.t2 | [y] | true] (rows=unknown)
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Rule optimizer_rewrite_nested_loop_join_to_hash_join transformed the logical plan: 
HashJoin[(x = y)] (rows=unknown)
  ├ Filter[(x > 1)] (rows=0)
  │  └ Collect[doc.t1 | [x] | true] (rows=unknown)
  └ Collect[doc.t2 | [y] | true] (rows=unknown)
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Rule optimizer_merge_filter_and_collect transformed the logical plan: 
Collect[doc.t1 | [x] | (x > 1)] (rows=unknown)
[2023-08-31T14:27:54,563][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Optimize plan: 
 HashJoin[(x = y)] (rows=unknown)
  ├ Collect[doc.t1 | [x] | (x > 1)] (rows=unknown)
  └ Collect[doc.t2 | [y] | true] (rows=unknown)
```

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
Just by looking at how `Memo`, `GoupReference` and `GroupReferenceResolver` interact one another, I think `Memo` can take over `GroupReferenceResolver` and `GroupReference` can hold a reference to a `Memo` such that `PrintContext` does not need to carry `GroupReferenceResolver`. WDYT?

**Comment by mkleen** [comment]
@jeeminso The new commit use the memo in the iterative optimizer directly to extract the plan which makes everything a lot simpler.

**Review by jeeminso — APPROVED** [review]
LGTM 👍

**Comment by jeeminso** [comment]
Just something I noticed, the plan is not updated here.

```
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Rule optimizer_move_filter_beneath_join transformed the logical plan: 
NestedLoopJoin[INNER | (x = y)] (rows=unknown)
  ├ Filter[(x > 1)] (rows=0)
  │  └ Collect[doc.t1 | [x] | true] (rows=unknown)
  └ Collect[doc.t2 | [y] | true] (rows=unknown)
[2023-08-31T14:27:54,562][TRACE][i.c.p.o.i.IterativeOptimizer] [Monte Susino] Rule optimizer_move_constant_join_conditions_beneath_nested_loop transformed the logical plan: 
NestedLoopJoin[INNER | (x = y)] (rows=unknown)
  ├ Filter[(x > 1)] (rows=0)
  │  └ Collect[doc.t1 | [x] | true] (rows=unknown)
  └ Collect[doc.t2 | [y] | true] (rows=unknown)
```

**Comment by mkleen** [comment]
> Just something I noticed (should be unrelated to this PR), the plan is not updated here.
 I know, not every rule application transforms the plan. Sometimes only a marker flag is set.

**Pull request merged**
