### PR TITLE
More backports

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

See individual commits.

Note on https://github.com/crate/crate/pull/13189/commits/d36b2045e54592434da8177814046edbc5ba423b:
I decided to not support snapshots for mixed clusters and left out `createSnapshotLegacy` intentionally.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mkleen** [comment]
retest this please

**Comment by mkleen** [comment]
retest this please

io.crate.integrationtests.ObjectColumnTest.updateToDynamicObject

**Review by matriv — COMMENTED** [review]
As discussed, please add a note to the commit that `createSnapshotLegacy` is skipped by intentionally.
Also, why didn't you mark as `[s]` those intermediate commits, I see a couple that are `data stream` related which we won't backport.

**Comment by mkleen** [comment]
> As discussed, please add a note to the commit that `createSnapshotLegacy` is skipped by intentionally. Also, why didn't you mark as `[s]` those intermediate commits, I see a couple that are `data stream` related which we won't backport.

The note is added. I skipped a few backports to collect all the snapshot related backports together. The remaining backports will be updated/backported later.

**Review by matriv — APPROVED** [review]
LGTM, thank you!

**Comment by mkleen** [comment]
retest this please

**Comment by mkleen** [comment]
retest this please

```
io.crate.integrationtests.TransportSQLActionTest.test_types_with_storage_can_be_inserted_and_queried
Failing for the past 1 build (Since
#4431 )
Took 1.2 sec.
Error Message

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

Stacktrace

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at __randomizedtesting.SeedInfo.seed([C0C2400F806461FE:E5DCBD735E3F1340]:0)
	at io.crate.integrationtests.TransportSQLActionTest.test_types_with_storage_can_be_inserted_and_queried(TransportSQLActionTest.java:2018)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by mkleen** [comment]
retest this please

**Pull request merged**
