### PR TITLE
Moving Multi node / zone docs

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
@mfussenegger Continuing our discussions, I'm creating a new 'scale' section for our main docs and would love to move these to there, I don't think these are tested, so pretty easy I hope?

### CODE REVIEW

**Comment by mfussenegger** [comment]
yep there are no tests in those. So I guess it's fine to move them.

How do we ensure not to break direct links? I think especially the multi node setup stuff has been linked to quite often (also in blog posts afaik)

**Comment by ChrisChinchilla** [comment]
@mfussenegger I'm doing some significant re-organising to create a better 'user flow', so there will likely need to be quite a few redirects created. That's the main way, of course, also covering versions.

This wont happen immediately, is it better to merge this into master when I'm done setting up things in the new location?

**Comment by mfussenegger** [comment]
yep would be better to merge this after the new location and redirect is setup. Otherwise if we do a new release and buiild new docs users would run into 404s

**Comment by ChrisChinchilla** [comment]
@mfussenegger +1, will park this here for now and come back to it when things are in place.

**Comment by ChrisChinchilla** [comment]
@mfussenegger This is now ready to be completed, and I rebased with master.

**Comment by mfussenegger** [comment]
ack

**Pull request merged**
