### PR TITLE
Ensure equi-join condition refers to two columns from two different relations

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
Fixes https://github.com/crate/crate/issues/15324. Occurs on `3.0`, possibly before. 

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
Maybe I should also let hash join to be able to handle such scenarios?

**Comment by jeeminso** [comment]
```
cr> EXPLAIN SELECT * FROM t0 inner JOIN t1 ON c0 = c0;
+--------------------------------------------------+
| QUERY PLAN                                       |
+--------------------------------------------------+
| HashJoin[(c0 = c0)] (rows=unknown)               |
|   ├ Collect[doc.t0 | [c0] | true] (rows=unknown) |
|   └ Collect[doc.t1 | [c1] | true] (rows=unknown) |
+--------------------------------------------------+

cr> SELECT * FROM t0 inner JOIN t1 ON c0 = c0;
+----+----+
| c0 | c1 |
+----+----+
|  0 |  1 |
+----+----+
```
Since this works, I will re-work on fixing hash join.

**Comment by jeeminso** [comment]
> Maybe I should also let hash join to be able to handle such scenarios?

Such cases are not valid : https://github.com/crate/crate/blob/fd981f1274dfe196a13429cb49533bb2a0c597a7/server/src/main/java/io/crate/planner/operators/HashJoin.java#L301

re-opening.

**Comment by mkleen** [comment]
This makes sense because `c1 = c1` is not a valid equi-join condition and therefore the join should not result in a hash-join. While looking at the original query from the issue the following improvements come to my mind:

```
cr> explain SELECT * FROM t0 LEFT  JOIN t1 ON ((t1.c1)=(t1.c1)) WHERE (NOT ((t1.c1) IS NULL));
+----------------------------------------------------------------+
| QUERY PLAN                                                     |
+----------------------------------------------------------------+
| NestedLoopJoin[INNER | (c1 = c1)] (rows=unknown)               |
|   ├ Collect[doc.t0 | [c0] | true] (rows=unknown)               |
|   └ Collect[doc.t1 | [c1] | (NOT (c1 IS NULL))] (rows=unknown) |
+----------------------------------------------------------------+
```
- The condition `c1 = c1` could be removed because it is always true
- This is not an inner-join, but a cross-join

However, this could be a follow-up.

**Comment by mkleen** [comment]
Commit message could be rephrased to something like 'Ensure equi-join condition refers to two columns from two different relations`

**Review by mkleen — APPROVED** [review]

**Comment by jeeminso** [comment]
> Commit message could be rephrased to something like `Ensure equi-join condition refers to two columns from two different relations`

Thank you, updated.

**Pull request merged**
