### PR TITLE
Unary/Binary/TripleScalar implementations do not need to be STRICTNULL

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
The definition of `NULLABLE` is clear from https://github.com/crate/crate/pull/16181. A function is `nullable` if `null -> null` AND no other inputs result in nulls. Hence revisiting https://github.com/crate/crate/pull/15452 and reverting several lines.

## Checklist

 - [ ] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
I have been looking into `array_avg` function which seems to be the only function currently marked wrong but it behaves correctly...

**Comment by mfussenegger** [comment]
This got superseded by https://github.com/crate/crate/pull/16303 right? Or is there still a part of this that you'd like to get in?

**Comment by jeeminso** [comment]
> > I believe scalars technically do not need to be strictnulls.
> 
> Isn't the point that strictnull allows us to optimize the query?
> 
> https://github.com/crate/crate/blob/969d56d2caa7f051b14cdabd6e1ae8d1e69dc2e6/server/src/main/java/io/crate/expression/predicate/NotPredicate.java#L166-L170

Yes, sorry I was not clear. I wanted to remove the asserts that I added such that Unary/Binary/TripleScalar implemenations do not need to be strictnull.

**Comment by mfussenegger** [comment]
> For example, pg_get_partkeydef was recently unmarked from strictnull and because of the assert it could no longer implement UnaryScalar

That's fine.
The `*Scalar` implementations do take care of the strict null handling.

E.g.:

https://github.com/crate/crate/blob/969d56d2caa7f051b14cdabd6e1ae8d1e69dc2e6/server/src/main/java/io/crate/expression/scalar/UnaryScalar.java#L62-L64

or

https://github.com/crate/crate/blob/969d56d2caa7f051b14cdabd6e1ae8d1e69dc2e6/server/src/main/java/io/crate/expression/scalar/arithmetic/BinaryScalar.java#L56-L61

**Comment by jeeminso** [comment]
Thanks for clarifying, closing.

**Pull request closed without merging**
